import type {State,RecipeId,Ingredient,Recipe,SupplierId,Contract} from './engine';
export type FactoryId='quay'|'riverside'|'northline';
export type PayTier='trainee'|'standard'|'senior';
export type Campaign='none'|'local'|'sampling'|'gifting'|'origin';
export type BuyerId='cafes'|'department';
export interface FactoryState {id:FactoryId;ready:number;workers:number;pay:PayTier;qualityLead:boolean;expanded:boolean;paused:boolean}
export interface GrowthState {chapter:'opening'|'growth'|'endless';reviewWeek:number;awarded:boolean;factories:FactoryState[];assignment:Record<RecipeId,FactoryId>;purchasing:Record<Ingredient,{enabled:boolean;supplier:SupplierId;target:number}>;reserve:number;brand:number;campaign:Campaign;response:'price'|'service'|'brand';buyers:Record<BuyerId,{enabled:boolean;recipe:RecipeId;terms:'fast'|'standard'|'extended';next:number;trust:number;delivered:number;missed:number}>;partnerships:('retail'|'boutique')[]}
export const FACTORIES=[{id:'quay' as FactoryId,name:'San Francisco Workshop',price:0,hours:100,rent:0,expansion:2200,extra:70,week:1},{id:'riverside' as FactoryId,name:'Oakland Factory',price:4200,hours:120,rent:140,expansion:1800,extra:60,week:18},{id:'northline' as FactoryId,name:'Turin Works',price:6500,hours:160,rent:180,expansion:2600,extra:80,week:27}];
export const PAY={trainee:{name:'Developing team',salary:76,hours:50},standard:{name:'Experienced team',salary:95,hours:60},senior:{name:'Senior team',salary:120,hours:70}};
export const CAMPAIGNS=[{id:'none' as Campaign,name:'Organic growth',cost:0,segment:'',lift:0,brand:0},{id:'local' as Campaign,name:'Local awareness',cost:110,segment:'All',lift:.18,brand:1},{id:'sampling' as Campaign,name:'Everyday sampling',cost:90,segment:'Everyday',lift:.15,brand:2},{id:'gifting' as Campaign,name:'Gift discovery',cost:130,segment:'Gifting',lift:.2,brand:2},{id:'origin' as Campaign,name:'Origin storytelling',cost:140,segment:'Connoisseur',lift:.18,brand:3}];
export const BUYERS=[{id:'cafes' as BuyerId,name:'San Francisco Café Network',description:'Smaller regular orders for everyday chocolate. Reliable delivery builds volume.',qty:40,quality:60,allowed:['dark','milk'] as RecipeId[],premium:4},{id:'department' as BuyerId,name:'Aster Department Stores',description:'Higher-margin signature ranges, stricter quality and a larger cash gap.',qty:30,quality:70,allowed:['orange','praline','origin','truffle','gianduja','tea'] as RecipeId[],premium:6}];
export function defaultGrowth(s:{mode:string;week:number;marketing:boolean;plan:Record<RecipeId,number>}):GrowthState{return {chapter:s.mode==='sandbox'&&s.week>16?'growth':'opening',reviewWeek:Math.max(36,s.week+19),awarded:false,factories:[{id:'quay',ready:1,workers:0,pay:'standard',qualityLead:false,expanded:false,paused:false}],assignment:{dark:'quay',milk:'quay',orange:'quay',praline:'quay',origin:'quay',truffle:'quay',gianduja:'quay',tea:'quay'},purchasing:Object.fromEntries(['cocoa','sugar','milk','nuts','citrus','tea'].map(i=>[i,{enabled:false,supplier:'dock',target:i==='cocoa'?150:i==='sugar'?80:40}])) as GrowthState['purchasing'],reserve:1500,brand:0,campaign:s.marketing?'local':'none',response:'service',buyers:{cafes:{enabled:false,recipe:'milk',terms:'standard',next:s.week,trust:50,delivered:0,missed:0},department:{enabled:false,recipe:'orange',terms:'standard',next:s.week,trust:50,delivered:0,missed:0}},partnerships:[]}}
const cents=(n:number)=>Math.round(n*100)/100;
export function machineHours(s:State,f:FactoryState){return FACTORIES.find(x=>x.id===f.id)!.hours+(f.id==='quay'&&s.upgrades.includes('capacity')?65:0)+(f.expanded?FACTORIES.find(x=>x.id===f.id)!.extra:0)}
export function staffHours(s:State,f:FactoryState){const training=s.choices['growth-lead']==='mentor'&&s.week>=19?1.1:s.choices['growth-lead']==='expert'?1.2:1;return Math.floor(((f.id==='quay'?165:0)+f.workers*PAY[f.pay].hours)*training)}
export function factoryCapacity(s:State,f:FactoryState){return f.ready>s.week||f.paused?0:Math.min(machineHours(s,f),staffHours(s,f))}
export function factoryPayroll(f:FactoryState){return cents(((f.id==='quay'?80:0)+f.workers*PAY[f.pay].salary+(f.qualityLead?100:0))*(f.paused?.5:1))}
export function payroll(s:State){return cents(s.growth.factories.filter(f=>f.ready<=s.week).reduce((a,f)=>a+factoryPayroll(f),0)+(s.choices['growth-lead']==='expert'?60:0))}
export function growthOverhead(s:State){return cents(payroll(s)-80+s.growth.factories.filter(f=>f.ready<=s.week).reduce((a,f)=>a+FACTORIES.find(x=>x.id===f.id)!.rent*(f.paused?.4:1),0)+CAMPAIGNS.find(c=>c.id===s.growth.campaign)!.cost)}
export function siteHours(s:State,recipes:Recipe[],id:FactoryId){const rs=recipes.filter(r=>s.growth.assignment[r.id]===id&&s.plan[r.id]>0&&(!r.unlock||s.research.includes(r.unlock)));return cents(rs.reduce((a,r)=>a+r.hours*s.plan[r.id],0)+(s.upgrades.includes('flexibility')?0:Math.max(0,rs.length-1)*8))}
export function siteQuality(s:State,r:Recipe){const f=s.growth.factories.find(f=>f.id===s.growth.assignment[r.id]);return f?.qualityLead?3:0}
export function rivalEvent(s:State){if(s.week>=21&&s.week<=23)return {name:'Voss everyday price campaign',segment:'Everyday',penalty:.12,end:23};if(s.week>=28&&s.week<=30)return {name:'Voss gift-store exclusivity',segment:'Gifting',penalty:.15,end:30};if(s.week>=33&&s.week<=36)return {name:'Regional shelf-space contest',segment:'All',penalty:.1,end:36};return null}
export function rivalMultiplier(s:State,r:Recipe){const event=rivalEvent(s);if(!event||(event.segment!=='All'&&event.segment!==r.segment))return 1;const counter=s.growth.response==='price'?s.prices[r.id]<=r.price*.95:s.growth.response==='brand'?s.growth.brand>=45:Object.values(s.growth.buyers).some(b=>b.enabled&&b.trust>=74);return 1-event.penalty*(counter?.25:1)}
export function brandMultiplier(s:State,r:Recipe){const c=CAMPAIGNS.find(c=>c.id===s.growth.campaign)!;return (1+Math.min(.2,s.growth.brand/500))*(1+((c.segment==='All'||c.segment===r.segment)?c.lift:0))*rivalMultiplier(s,r)}
export function buyerOutcome(s:State,c:Contract,success:boolean){if(c.id==='paris-tasting'&&success){s.growth.brand=Math.min(100,s.growth.brand+10);if(!s.growth.partnerships.includes('boutique'))s.growth.partnerships.push('boutique')}if(!c.buyerId)return;const b=s.growth.buyers[c.buyerId];b.trust=Math.max(0,Math.min(100,b.trust+(success?12:-20)));if(success){b.delivered++;s.growth.brand=Math.min(100,s.growth.brand+2)}else{b.missed++;b.next=Math.max(b.next,s.week+3)}}
export function buyerQuote(s:State,id:BuyerId,recipes:Recipe[]){const b=s.growth.buyers[id],d=BUYERS.find(x=>x.id===id)!,r=recipes.find(r=>r.id===b.recipe)!;const factor=b.terms==='fast'?.95:b.terms==='extended'?1.06:1;return {qty:Math.ceil(d.qty*(b.delivered>=4?1.25:b.delivered>=2?1.1:1)),unitPrice:cents((r.price+d.premium+(b.delivered>=4?1:0))*factor),deposit:b.terms==='fast'?0:.2,delay:b.terms==='fast'?0:b.terms==='extended'?2:1,minQuality:r.id==='origin'?85:d.quality}}
export function queueBuyerOrders(s:State,recipes:Recipe[]){if(s.week<20)return;for(const d of BUYERS){const b=s.growth.buyers[d.id];if(!b.enabled||s.week<b.next||s.contracts.some(c=>c.buyerId===d.id&&c.status==='active')||s.contracts.filter(c=>c.status==='active').length>=3)continue;const q=buyerQuote(s,d.id,recipes),id=`standing-${d.id}-${s.week}`;if(s.contracts.some(c=>c.id===id))continue;s.contracts.push({id,client:d.name,recipe:b.recipe,...q,due:s.week+1,accepted:true,status:'active',reward:2,buyerId:d.id,fee:.05});const deposit=cents(q.qty*q.unitPrice*q.deposit);s.cash=cents(s.cash+deposit);s.book.deposits=cents(s.book.deposits+deposit);b.next=s.week+3;s.log.unshift({week:s.week,text:`Standing order: ${d.name}, ${q.qty} cases due W${s.week+1}. Deposit $${deposit}.`})}}
export function growthGoals(s:State){return {factories:s.growth.factories.filter(f=>!f.paused&&f.ready<=s.week&&factoryCapacity(s,f)>0).length,buyers:Object.values(s.growth.buyers).filter(b=>b.enabled&&b.delivered>=2&&b.trust>=60).length,profit:cents(s.reports.slice(0,4).reduce((a,r)=>a+r.profit,0)),weeks:s.reports.length}}
export type GrowthAction={type:'staff';factory:FactoryId;workers:number;pay:PayTier;qualityLead:boolean}|{type:'factory';id:FactoryId}|{type:'factory-expand';id:FactoryId}|{type:'factory-pause';id:FactoryId}|{type:'assign';recipe:RecipeId;factory:FactoryId}|{type:'purchase-rule';ingredient:Ingredient;enabled:boolean;supplier:SupplierId;target:number}|{type:'reserve';amount:number}|{type:'campaign';id:Campaign}|{type:'rival-response';response:GrowthState['response']}|{type:'buyer';id:BuyerId;enabled:boolean;recipe:RecipeId;terms:'fast'|'standard'|'extended'}|{type:'partnership';id:'retail'|'boutique'};
export const GROWTH_ACTIONS=['staff','factory','factory-expand','factory-pause','assign','purchase-rule','reserve','campaign','rival-response','buyer','partnership'];
export function applyGrowthAction(s:State,a:GrowthAction,recipes:Recipe[]):string{
 const spend=(cost:number)=>{if(s.cash<cost)throw Error('Not enough cash. Keep a reserve for stock and salaries.');s.cash=cents(s.cash-cost);s.book.investments=cents(s.book.investments+cost)};
 if(a.type==='staff'){const f=s.growth.factories.find(f=>f.id===a.factory);if(s.week<9||!f||!Number.isInteger(a.workers)||a.workers<0||a.workers>8||!Object.keys(PAY).includes(a.pay)||typeof a.qualityLead!=='boolean')throw Error('Staffing opens in week 9. Choose 0–8 hires at an owned factory.');const cost=Math.max(0,a.workers-f.workers)*150+Math.max(0,f.workers-a.workers)*PAY[f.pay].salary*.5+(a.qualityLead&&!f.qualityLead?250:0);spend(cents(cost));f.workers=a.workers;f.pay=a.pay;f.qualityLead=a.qualityLead;return `Staffing saved. Recruitment/severance $${cents(cost)}; weekly payroll $${factoryPayroll(f)}. Changes apply this week once the factory is ready.`}
 if(a.type==='factory'){const d=FACTORIES.find(f=>f.id===a.id);if(!d||s.week<d.week||s.growth.factories.some(f=>f.id===a.id)||s.reputation<60)throw Error('This factory is not available yet. Build 60 reputation and reach its opening week.');if(a.id==='northline'&&!s.travel.visited.includes('turin'))throw Error('Visit Turin to establish the local factory connection first.');if(a.id==='northline'&&s.growth.factories.filter(f=>f.ready<=s.week).length<2)throw Error('Commission a second factory before acquiring Turin Works.');spend(d.price);s.growth.factories.push({id:a.id,ready:s.week+2,workers:0,pay:'standard',qualityLead:false,expanded:false,paused:false});return `${d.name} acquired. Ready week ${s.week+2}; hire staff and assign products before production.`}
 if(a.type==='factory-expand'){const f=s.growth.factories.find(f=>f.id===a.id),d=FACTORIES.find(f=>f.id===a.id);if(!f||!d||f.expanded||f.ready>s.week||s.week<17)throw Error('Expand a commissioned factory from week 17 onward.');spend(d.expansion);f.expanded=true;return `Factory expanded by ${d.extra} machine hours. Staffing may now limit output.`}
 if(a.type==='factory-pause'){const f=s.growth.factories.find(f=>f.id===a.id);if(!f||f.id==='quay')throw Error('The original workshop stays open.');f.paused=!f.paused;return f.paused?'Factory mothballed: no production, 50% payroll and 40% premises cost. Move its product plans.':'Factory reopened. Full payroll, premises and capacity resume.'}
 if(a.type==='assign'){if(!recipes.some(r=>r.id===a.recipe)||!s.growth.factories.some(f=>f.id===a.factory))throw Error('Choose a product and an owned factory.');s.growth.assignment[a.recipe]=a.factory;return 'Factory assignment saved. Shared ingredient stock is consumed only once.'}
 if(a.type==='purchase-rule'){if(a.ingredient==='tea'&&a.enabled&&!s.travel.learned.includes('kyoto-tea'))throw Error('Discover the Uji tea supplier before enabling tea replenishment.');if(s.week<6||!['cocoa','sugar','milk','nuts','citrus','tea'].includes(a.ingredient)||!['dock','coop','estate'].includes(a.supplier)||!Number.isInteger(a.target)||a.target<0||a.target>1000||typeof a.enabled!=='boolean')throw Error('Purchasing rules open week 6. Choose a whole target from 0–1,000 kg.');s.growth.purchasing[a.ingredient]={enabled:a.enabled,supplier:a.supplier,target:a.target};return 'Weekly purchasing rule saved. It runs after arrivals at the start of each week.'}
 if(a.type==='reserve'){if(!Number.isFinite(a.amount)||a.amount<0||a.amount>100000)throw Error('Choose a reserve between $0 and $100,000.');s.growth.reserve=cents(a.amount);return 'Cash reserve saved. Automatic purchasing also protects payroll, overhead and planned conversion costs.'}
 if(a.type==='campaign'){if(!CAMPAIGNS.some(c=>c.id===a.id)||s.week<5)throw Error('Brand campaigns open week 5.');s.growth.campaign=a.id;s.marketing=a.id==='local';return 'Weekly campaign saved. Its budget is included in the forecast until you change it.'}
 if(a.type==='rival-response'){if(!['price','service','brand'].includes(a.response)||s.week<21)throw Error('Competitive responses open week 21.');s.growth.response=a.response;return 'Response saved. Meet its displayed condition to reduce rival penalties by 75%.'}
 if(a.type==='buyer'){const d=BUYERS.find(b=>b.id===a.id),r=recipes.find(r=>r.id===a.recipe);if(s.week<20||!d||!r||!d.allowed.includes(a.recipe)||(r.unlock&&!s.research.includes(r.unlock))||!['fast','standard','extended'].includes(a.terms)||typeof a.enabled!=='boolean')throw Error('Standing buyers open week 20. Select an unlocked product suited to the buyer.');const b=s.growth.buyers[a.id];b.enabled=a.enabled;b.recipe=a.recipe;b.terms=a.terms;queueBuyerOrders(s,recipes);return a.enabled?'Standing agreement saved. New orders recur every three weeks; existing accepted terms stay fixed.':'Future standing orders paused. Existing commitments still need delivery.'}
 if(a.type==='partnership'){if(s.week<23||!['retail','boutique'].includes(a.id)||s.growth.partnerships.includes(a.id)||Object.values(s.growth.buyers).reduce((n,b)=>n+b.delivered,0)<2)throw Error('Deliver two standing orders and reach week 23 to unlock distribution partnerships.');spend(a.id==='retail'?1200:1500);s.growth.partnerships.push(a.id);s.growth.brand=Math.min(100,s.growth.brand+8);return 'Partnership signed. Its regional market is now available to open.'}
 throw Error('Unknown growth action.');
}
