import type {State, Recipe, RecipeId, Ingredient, SupplierId, Contract} from './engine';
import type {FactoryId} from './growth';
import {DESTINATIONS} from './travel.ts';
import type {Destination} from './travel';

export interface JourneyState {enabled:boolean;chapter:number;decisions:Record<string,string>;analyst:boolean;operations:boolean;recoveryUsed:boolean;identity:{founder:string;business:string;crest:string};completed:boolean;setbackUntil:number}
export const defaultJourney=(enabled=true):JourneyState=>({enabled,chapter:0,decisions:{},analyst:false,operations:false,recoveryUsed:false,identity:{founder:'',business:'Cacao House',crest:'cacao'},completed:false,setbackUntil:0});
export function capabilities(s:State){const c=s.v3?.enabled?s.v3.chapter:-1;return {purchasing:c>=1||(!s.v3?.enabled&&s.week>=6),people:c>=2||(!s.v3?.enabled&&s.week>=9),travel:c>=2||(!s.v3?.enabled&&s.week>=3),research:c>=1||(!s.v3?.enabled&&s.week>=2),brand:c>=3||(!s.v3?.enabled&&s.week>=5),buyers:c>=6||(!s.v3?.enabled&&s.week>=20),factories:c>=6||(!s.v3?.enabled&&s.week>=18),analyst:!!s.v3?.analyst,remote:!!s.v3?.operations}}
export function canHireManager(s:State,role:'analyst'|'operations'){return !s.v3[role]&&(role==='analyst'?capabilities(s).people:(s.v3.enabled?s.v3.chapter>=7:true)&&s.growth.factories.length>=2)}
export const factoryPlace=(id:FactoryId):'sf'|'oakland'|'turin'=>id==='quay'?'sf':id==='riverside'?'oakland':'turin';
export function canManageFactory(s:State,id:FactoryId){return !s.v3?.enabled||!!s.v3.operations||(!s.travel.trip&&s.travel.location===factoryPlace(id))}
const done=(s:State,id:string)=>s.contracts.some(c=>(c.id===id||c.id.startsWith(id+'-retry-'))&&c.status==='fulfilled');
const option=(id:string,label:string,detail:string)=>({id,label,detail});
export function journeyView(s:State){
 const c=s.v3.chapter,learned=(id:string)=>s.travel.learned.includes(id),deliveries=Object.values(s.growth.buyers).reduce((n,b)=>n+b.delivered,0);
 const chapters=[
 {title:'A house worth keeping',person:'Nadia Vale',text:'The ferry-side workshop is yours to revive. Its owner left a book of unfinished recipes and one wish: build a house whose makers, growers and customers know each other. Claire Moreau buys chocolate for boutiques in Paris. She is looking for an independent maker to develop a hazelnut chocolate for a tasting order. Complete a local customer order first; Captain Leda will then introduce you to her.',objective:'Meet Nadia at the San Francisco workshop to begin with a local customer order.',place:'sf',ready:true,progress:'Your opening production plan makes 55 dark and 35 milk cases.',options:[option('begin','Open the workshop','Keep your $3,200 working cash. Your loan has no forced week-16 deadline.')]},
 {title:'Keep a small promise',person:'Captain Leda',text:'The ferry canteen needs chocolate that arrives when promised. This first delivery is your introduction, not a race to expand. Buy stock, make the cases and let the crew dispatch them. After this delivery, Leda will introduce you to Claire Moreau, the Paris boutique buyer who wants to taste your hazelnut chocolate.',objective:'Complete one customer order, then meet Leda in San Francisco.',place:'sf',ready:s.fulfilled>=1,progress:`${s.fulfilled} customer orders completed. Accept a waterfront commission from Orders.`,options:[option('reserve','Keep the introduction simple','A $400 earned launch grant stays in working capital.'),option('growers','Invest in traceability · $300','Receive the $400 grant, invest $300, and gain +5 batch quality and +8 reputation.')]},
 {title:'An invitation with a missing recipe',person:'Claire Moreau',text:'Claire Moreau buys chocolate for Paris boutiques. She wants 25 cases of your own gianduja—a hazelnut chocolate—at quality 80 or higher for a tasting order. A successful delivery earns an introduction to Paris distribution. A maker in Turin knows the method; an exporter in Guayaquil can help you find the right cacao.',objective:'Travel to Paris and meet Claire Moreau about her hazelnut-chocolate tasting order.',place:'paris',ready:learned('paris-brief'),progress:learned('paris-brief')?'Claire’s brief is in your notebook.':'Discover “Meet the boutique buyer” in Paris.',options:[option('craft','Promise a careful tasting','Claire will wait for the right recipe. No artificial deadline until you accept her order.')]},
 {title:'What Turin can teach',person:'Luca Ferrero',text:'Luca shares a gianduja method, but warns that more expensive ingredients do not automatically make a better bar. Taste his hazelnuts and learn the process. Your pilot will be your own interpretation, made by your own crew.',objective:'Learn gianduja technique and arrange the hazelnut sample in Turin.',place:'turin',ready:learned('turin-technique')&&learned('turin-sample'),progress:`${Number(learned('turin-technique'))+Number(learned('turin-sample'))}/2 Turin discoveries.`,options:[option('patient','Protect the workshop reserve','Keep cash for the cacao journey.'),option('finish','Commission finishing lessons · $250','Permanent +2 quality for gifting recipes; the Paris technique is credited.')]},
 {title:'The harvest has a voice',person:'Inés Sol',text:'Inés compares cacao profiles with you. A port inspection is approaching: new cooperative orders will need an extra week for three weeks after this meeting. You can fund a lasting direct relationship or buy through the existing exchange. Both routes remain viable.',objective:'Compare cacao profiles in Guayaquil, then agree sourcing terms with Inés.',place:'guayaquil',ready:learned('ecuador-profile'),progress:learned('ecuador-profile')?'Cacao profile recorded. Prepare a buffer before leaving.':'Discover “Compare cacao profiles” with Inés.',options:[option('direct','Build the direct relationship · $400','Cooperative purchases cost 12% less, normal lead time falls by one week. Inspection still adds one week temporarily.'),option('exchange','Keep using the exchange','Preserve $400. Use dock stock or order early through the inspection.')]},
 {title:'A box with your name on it',person:'Nadia Vale',text:'Back home, combine Turin’s method and Inés’s cacao profile in an eight-case pilot. Claire’s tasting order needs 25 cases at quality 80. A successful tasting earns a Paris distribution introduction. Voss offers a brief promotion under its name; decide what your house needs.',objective:'Run the gianduja pilot in San Francisco and fulfil Claire’s Paris tasting order.',place:'sf',ready:done(s,'paris-tasting'),progress:done(s,'paris-tasting')?'Claire has accepted your tasting.':'Pilot Gianduja Reserve, accept the Paris tasting, then produce with quality 80+.',options:[option('independent','Keep your name on every box','Gain 6 reputation and 8 brand strength.'),option('licence','Accept a limited Voss licence','Receive $750; lose 6 reputation. Gifting retail demand −10% for three weeks, then the licence ends.')]},
 {title:'Across the bay',person:'Nadia Vale',text:'Claire can introduce a second steady customer, but a promise cannot depend on one crowded room. Oakland has a workshop to commission. Hire a crew, decide which recipes belong there, and bring Nadia to inspect the line. An operations manager can then keep both sites adjustable while you travel.',objective:'Commission and staff Oakland Factory, make a batch there, then meet Nadia.',place:'oakland',ready:s.growth.factories.some(f=>f.id==='riverside'&&f.ready<=s.week&&f.workers>0&&!f.paused)&&s.v3.decisions['oakland-produced']==='yes',progress:s.growth.factories.some(f=>f.id==='riverside')?'Commission for two weeks, hire a worker, assign a recipe here and close a week with a batch.':'Visit Oakland, acquire the factory, and hire its team.',options:[option('training','Fund shared training · $350','All factories gain 10% staffed capacity; no extra recurring salary.'),option('reserve','Keep a payroll reserve','The crew learns on the job. Retain $350 for wages.')]},
 {title:'A different kind of leaf',person:'Aoi Tanaka',text:'Aoi’s Kyoto confectionery uses tea as an ingredient, never as a shortcut to a story. She introduces a supplier in nearby Uji and invites you to develop a tea chocolate. Meanwhile the factories must keep their promises at home.',objective:'Discover tea sourcing and the confectionery technique in Kyoto.',place:'kyoto',ready:learned('kyoto-tea')&&learned('kyoto-technique'),progress:`${Number(learned('kyoto-tea'))+Number(learned('kyoto-technique'))}/2 Kyoto discoveries.`,options:[option('collaborate','Carry the recipe home','Develop balanced or intense Tea Cream in a real pilot at San Francisco.')]},
 {title:'The house learns to keep going',person:'Mara Sen',text:'A launch is a moment; a house is a habit. Mara arranges a tea preview and asks you to serve two standing orders. Choose payment terms you can support. The final Paris gathering is waiting for a house that can keep operating beyond its founder’s travels.',objective:'Pilot Tea Cream, complete the tea preview and deliver two standing orders.',place:'sf',ready:done(s,'tea-preview')&&deliveries>=2,progress:`Tea preview ${done(s,'tea-preview')?'delivered':'pending'} · ${Math.min(2,deliveries)}/2 standing deliveries.`,options:[option('service','Celebrate the crew','Gain 8 reputation and 10 brand strength; unlock the final invitation.')]},
 {title:'The table in Paris',person:'Claire Moreau',text:'Inés’s cacao, Luca’s method, Aoi’s tea and your own crew’s work share one table. Claire has invited the people behind the boxes. Settle the workshop loan, open Paris distribution and deliver the gathering’s tea chocolate before joining them.',objective:'Repay the loan, open Paris distribution and fulfil the House Table commission. Meet Claire in Paris.',place:'paris',ready:s.debt===0&&s.markets.includes('paris')&&done(s,'house-table'),progress:`Loan ${s.debt===0?'settled':`$${Math.ceil(s.debt)} remaining`} · Paris ${s.markets.includes('paris')?'open':'unopened'} · gathering ${done(s,'house-table')?'delivered':'pending'}.`,options:[option('table','Take your seat','Complete the authored story. Keep every factory, relationship and recipe in open-ended play.')]}
 ];
 const entry=chapters[Math.min(c,chapters.length-1)];return {chapter:c,...entry,place:entry.place as 'sf'|Destination,ready:entry.ready&&!s.v3.completed,options:s.v3.completed?[]:entry.options};
}
export type JourneyAction={type:'journey';choice:string}|{type:'hire-manager';role:'analyst'|'operations'}|{type:'identity';founder:string;business:string;crest:string}|{type:'recovery';choice:'bridge'|'sell-stock'};
export const JOURNEY_ACTIONS=['journey','hire-manager','identity','recovery'];
export function applyJourneyAction(s:State,a:JourneyAction){
 const spend=(n:number)=>{if(s.cash<n)throw Error(`This decision needs $${n} available cash.`);s.cash=Math.round((s.cash-n)*100)/100;s.book.story-=n;};
 if(a.type==='identity'){if([a.founder,a.business,a.crest].some(v=>typeof v!=='string'||v.length>60))throw Error('Use names up to 60 characters.');s.v3.identity={founder:a.founder.trim(),business:a.business.trim()||'Cacao House',crest:a.crest.trim()||'cacao'};return 'House identity saved.';}
 if(a.type==='hire-manager'){if(!['analyst','operations'].includes(a.role)||s.v3[a.role])throw Error('This manager is already hired or unavailable.');if(a.role==='analyst'&&!capabilities(s).people)throw Error('Make your first delivery and earn the Paris introduction first.');if(a.role==='operations'&&((s.v3.enabled&&s.v3.chapter<7)||s.growth.factories.length<2))throw Error('Commission Oakland and complete Nadia’s inspection before hiring an operations manager.');spend(a.role==='analyst'?450:900);s.v3[a.role]=true;return a.role==='analyst'?'Analyst hired: $45/week. Rough demand ranges and trends are available.':'Operations manager hired: $90/week. You can now change owned factory settings remotely.';}
 if(a.type==='recovery'){if(!['bridge','sell-stock'].includes(a.choice)||s.v3.recoveryUsed||s.cash>=1000||!s.v3.enabled)throw Error('One recovery decision is available when cash falls below $1,000.');s.v3.recoveryUsed=true;if(a.choice==='bridge'){s.cash+=1800;s.debt+=1980;s.book.credit+=1800;return 'Credit union bridge: $1,800 cash, $1,980 added to the loan. No reputation penalty.';}s.cash+=1200;s.book.story+=1200;s.reputation=Math.max(0,s.reputation-8);s.v3.decisions.recovery='licence';s.v3.setbackUntil=s.week+3;return 'A three-week rescue licence brings $1,200, costs 8 reputation and temporarily reduces gifting demand by 10%.';}
 if(!s.v3.enabled||s.v3.completed)throw Error('This house has no unfinished story meeting.');const v=journeyView(s);if(!v.ready)throw Error(v.objective);if(s.travel.trip||s.travel.location!==v.place)throw Error(`Meet ${v.person} in ${v.place==='sf'?'San Francisco':v.place} to make this decision.`);if(!v.options.some(o=>o.id===a.choice))throw Error('Choose one of the current meeting responses.');
 if(s.v3.chapter===1){s.cash+=400;s.book.story+=400;if(a.choice==='growers'){spend(300);s.choices['choice-growers']='growers';s.reputation=Math.min(100,s.reputation+8);}}
 if(a.choice==='finish'&&!s.travel.learned.includes('paris-technique')){spend(250);s.travel.learned.push('paris-technique');}
 if(s.v3.chapter===4){if(a.choice==='direct'&&!s.travel.learned.includes('ecuador-direct')){spend(400);s.travel.learned.push('ecuador-direct');}s.v3.setbackUntil=s.week+3;s.v3.decisions.inspectionStart=String(s.week+1);}
 if(s.v3.chapter===5){if(a.choice==='licence'){s.cash+=750;s.book.story+=750;s.reputation=Math.max(0,s.reputation-6);s.v3.setbackUntil=s.week+3;}else{s.reputation=Math.min(100,s.reputation+6);s.growth.brand=Math.min(100,s.growth.brand+8);}}
 if(a.choice==='training'){spend(350);s.choices['growth-lead']='mentor';}
 if(a.choice==='service'){s.reputation=Math.min(100,s.reputation+8);s.growth.brand=Math.min(100,s.growth.brand+10);}
 s.v3.decisions[String(s.v3.chapter)]=a.choice;s.v3.chapter++;
 if(a.choice==='table'){s.v3.completed=true;s.status='won';s.growth.awarded=true;s.ending=`${s.v3.identity.business} has a place at the table. Claire presents the first box bearing your house’s name; Inés, Luca and Aoi each recognise their contribution, and Nadia’s crew has kept both workshops running. The loan is settled and the business belongs to you. The authored journey is complete; continue with every recipe, factory and relationship in open-ended play.`;}
 return a.choice==='table'?'The house’s story is complete.':'Meeting recorded. Your next introduction is ready.';
}
export function journeyOffers(s:State):Contract[]{if(!s.v3.enabled||s.v3.completed)return [];const definitions=[{id:'waterfront',client:'Captain Leda · Waterfront introduction',recipe:'dark' as RecipeId,qty:35,unitPrice:22,minQuality:50,chapter:1},{id:'tea-preview',client:'Mara Sen · Tea preview',recipe:'tea' as RecipeId,qty:24,unitPrice:43,minQuality:75,chapter:8},{id:'house-table',client:'Claire Moreau · The House Table',recipe:'tea' as RecipeId,qty:35,unitPrice:46,minQuality:80,chapter:9}];return definitions.filter(d=>s.v3.chapter===d.chapter&&!done(s,d.id)&&!s.contracts.some(c=>(c.id===d.id||c.id.startsWith(d.id+'-retry-'))&&c.status==='active')).map(d=>({...d,id:s.contracts.some(c=>c.id===d.id)?`${d.id}-retry-${s.week}`:d.id,due:s.week+4,delay:1,deposit:.25,reward:6,accepted:false,status:'offer' as const}));}
export function currentNews(s:State){if(!s.v3?.enabled)return [];const block=Math.floor((s.week-1)/8),start=block*8+4,kind=block%3;const items=[];if(s.week<=start+2)items.push({id:`market-${block}`,title:['Cacao port inspection','A season for giving','Warm weather forecast'][kind],text:['New cooperative orders take one extra week; cocoa quotes rise 12%. Order early, use dock stock or draw down a buffer.','Gift buyers are expected to be more active for three weeks; nut quotes rise 8%. Build only the stock you can sell.','Milk and truffle retail demand softens by 15%; citrus gifting demand rises 12%. Adjust the mix before making perishable stock.'][kind],starts:start,ends:start+2,phase:(s.week<start?'ahead':'active') as 'ahead'|'active'});const inspection=Number(s.v3.decisions.inspectionStart);if(inspection&&s.week<=inspection+2)items.push({id:'ines-inspection',title:'Inés’s shipping warning',text:'Cooperative orders placed during this inspection need one extra week. Existing shipments keep their dates. Keep a buffer or use the dock.',starts:inspection,ends:inspection+2,phase:(s.week<inspection?'ahead':'active') as 'ahead'|'active'});if((s.v3.decisions['5']==='licence'||s.v3.decisions.recovery==='licence')&&s.week<=s.v3.setbackUntil)items.push({id:'limited-licence',title:'Voss’s limited licence',text:'Your gifting demand is reduced by 10% while Voss sells the licensed batch. Your factories remain yours; the deal expires automatically.',starts:s.v3.setbackUntil-3,ends:s.v3.setbackUntil,phase:'active' as const});return items;}
export function newsPrice(s:State,i:Ingredient){return currentNews(s).filter(n=>n.phase==='active').reduce((n,e)=>n*(e.id.startsWith('market-')&&e.title==='Cacao port inspection'&&i==='cocoa'?1.12:e.title==='A season for giving'&&i==='nuts'?1.08:1),1)}
export function newsLead(s:State,supplier:SupplierId){return supplier==='coop'&&currentNews(s).some(n=>n.phase==='active'&&(n.title==='Cacao port inspection'||n.id==='ines-inspection'))?1:0}
export function newsDemand(s:State,r:Recipe){return currentNews(s).filter(n=>n.phase==='active').reduce((n,e)=>n*(e.title==='A season for giving'&&r.segment==='Gifting'?1.2:e.title==='Warm weather forecast'?(['milk','truffle'].includes(r.id)?.85:r.id==='orange'?1.12:1):e.id==='limited-licence'&&r.segment==='Gifting'?.9:1),1)}
export function travelPreflight(s:State,to:'sf'|Destination){const d=DESTINATIONS.find(d=>d.id===to),local=['sf','oakland'].includes(to)&&['sf','oakland'].includes(s.travel.location),weeks=local?0:d?.weeks||1,cost=to==='sf'?0:d?.cost||0;const warnings=[`Saved production continues during ${weeks} week${weeks===1?'':'s'} of travel.`,...(!s.v3.operations?['Factory plans and equipment can only be changed on site until an operations manager is hired.']:[]),...s.contracts.filter(c=>c.status==='active'&&c.due<=s.week+weeks).map(c=>`${c.client} is due during this trip (week ${c.due}).`),...(s.cash-cost<1000?['This booking leaves less than $1,000 for stock, wages and overhead.']:[])];return {weeks,cost,warnings};}
export function validateJourney(s:State){const j=s.v3;if(!j||typeof j.enabled!=='boolean'||!Number.isInteger(j.chapter)||j.chapter<0||j.chapter>10||['analyst','operations','recoveryUsed','completed'].some(k=>typeof (j as unknown as Record<string,unknown>)[k]!=='boolean')||!Number.isInteger(j.setbackUntil)||j.setbackUntil<0||!j.decisions||typeof j.decisions!=='object'||Array.isArray(j.decisions)||Object.values(j.decisions).some(v=>typeof v!=='string')||!j.identity||['founder','business','crest'].some(k=>typeof j.identity[k as keyof typeof j.identity]!=='string'||j.identity[k as keyof typeof j.identity].length>60))throw Error('Journey data is damaged.');}
