import type {State,Ingredient,RecipeId} from './engine';
export type Destination='paris'|'turin'|'guayaquil'|'kyoto';
export interface TravelState {location:'sf'|Destination;trip:{to:'sf'|Destination;arrival:number}|null;visited:Destination[];learned:string[];variants:Partial<Record<RecipeId,'balanced'|'intense'>>}
export const DESTINATIONS=[{id:'paris' as Destination,name:'Paris',country:'France',week:3,cost:250,weeks:1,x:51,y:28,role:'Premium buyers & confectionery',description:'Meet a buyer, understand the brief and learn a finishing technique. Paris is a customer and knowledge destination, not a cacao source.'},{id:'turin' as Destination,name:'Turin',country:'Italy',week:5,cost:300,weeks:1,x:53,y:32,role:'Hazelnuts & gianduja technique',description:'Study hazelnut chocolate, arrange a supplier sample and develop your own gianduja recipe.'},{id:'guayaquil' as Destination,name:'Guayaquil',country:'Ecuador',week:8,cost:450,weeks:2,x:27,y:62,role:'Cacao exporters & grower visits',description:'Meet an exporter in Guayaquil and visit growers outside the city. Choose samples or a lasting direct-trade relationship.'},{id:'kyoto' as Destination,name:'Kyoto',country:'Japan · nearby Uji',week:22,cost:650,weeks:2,x:87,y:36,role:'Tea sourcing & a new product family',description:'Work with a fictional confectionery partner and explore nearby Uji tea. Develop tea chocolate for quality-focused buyers.'}];
export const TRAVEL_ACTIVITIES=[{id:'paris-brief',city:'paris' as Destination,name:'Meet the boutique buyer',cost:0,detail:'Get a specific brief: 25 cases of your own gianduja at quality 80+. Complete the sourcing and pilot chain to receive the order.'},{id:'paris-technique',city:'paris' as Destination,name:'Study precision finishing',cost:250,detail:'Permanent +2 quality on gifting recipes. Factory production continues while you learn.'},{id:'turin-sample',city:'turin' as Destination,name:'Arrange a hazelnut sample',cost:120,detail:'12 kg select hazelnuts arrive at your shared storeroom next week. A permanent contact reduces future nut prices by 10%.'},{id:'turin-technique',city:'turin' as Destination,name:'Learn gianduja technique',cost:250,detail:'Discover the method for your own Gianduja Reserve. Combine it with an Ecuador cacao profile and run a pilot at home.'},{id:'ecuador-profile',city:'guayaquil' as Destination,name:'Compare cacao profiles',cost:120,detail:'12 kg select cocoa ships for next week; learn the cacao profile required for your gianduja pilot.'},{id:'ecuador-direct',city:'guayaquil' as Destination,name:'Build a direct-trade relationship',cost:400,detail:'Cooperative orders permanently cost 12% less and travel one week faster, with a minimum one-week lead time. Routine ordering stays remote.'},{id:'kyoto-tea',city:'kyoto' as Destination,name:'Meet the Uji tea supplier',cost:150,detail:'10 kg select tea ships for next week. Tea can then be reordered remotely through your established importers.'},{id:'kyoto-technique',city:'kyoto' as Destination,name:'Work with the confectionery partner',cost:300,detail:'Discover tea-chocolate technique. Run a balanced or intense pilot to launch Kyoto Tea Cream.'}];
export function defaultTravel():TravelState{return {location:'sf',trip:null,visited:[],learned:[],variants:{}}}
export function travelQuality(s:State,r:{id:RecipeId;segment:string}){return (s.travel.learned.includes('paris-technique')&&r.segment==='Gifting'?2:0)+(s.travel.variants[r.id]==='intense'?3:0)}
export function variantIngredients(s:State,r:{id:RecipeId;ingredients:Partial<Record<Ingredient,number>>}){if(s.travel.variants[r.id]!=='intense')return r.ingredients;if(r.id==='gianduja')return {cocoa:.6,sugar:.2,milk:.05,nuts:.7};if(r.id==='tea')return {cocoa:.45,sugar:.2,milk:.3,tea:.12};return r.ingredients}
export function pilotRequirements(s:State,recipe:RecipeId){if(recipe==='gianduja')return ['turin-technique','ecuador-profile'].filter(id=>!s.travel.learned.includes(id));if(recipe==='tea')return ['kyoto-tea','kyoto-technique'].filter(id=>!s.travel.learned.includes(id));return ['unknown recipe']}
export type TravelAction={type:'travel';to:'sf'|Destination}|{type:'visit';id:string}|{type:'pilot';recipe:'gianduja'|'tea';variant:'balanced'|'intense'};
