import {useEffect,useState} from 'react';
import * as E from '../../game/engine';
import type {Action,State,FactoryId,FactoryState,RecipeId,PayTier} from '../../game/engine';
import ProductArt from '../ProductArt';
import NumberField from './NumberField';
import './factory.css';

export type FactorySection='production'|'people'|'equipment'|'inventory'|'standards';
export interface FactoryPanelProps {s:State;factory:FactoryId;section:FactorySection;onSection:(section:FactorySection)=>void;dispatch:(a:Action)=>{ok:boolean;message:string};onNavigate:(place:string)=>void}
const decimal=(n:number)=>Number(n.toFixed(1)).toLocaleString('en-US');
const conversion=(s:State,r:E.Recipe)=>r.labor*(s.upgrades.includes('efficiency')?.75:1)+(s.position[r.id]==='premium'?1.3:s.position[r.id]==='value'?-.7:0);
const labels:Record<FactorySection,string>={production:'Production',people:'People',equipment:'Equipment',inventory:'Stock',standards:'Standards'};

export default function FactoryPanel({s,factory,section,onSection,dispatch,onNavigate}:FactoryPanelProps){
 const [selected,setSelected]=useState<RecipeId>('dark');
 const site=s.growth.factories.find(f=>f.id===factory),definition=E.FACTORIES.find(f=>f.id===factory)!;
 if(!site)return <div className="f3-empty">This factory is not part of your house yet.</div>;
 const recipes=E.RECIPES.filter(r=>E.unlocked(s,r)&&s.growth.assignment[r.id]===factory),caps=E.capabilities(s),manage=E.canManageFactory(s,factory),editable=manage&&s.status==='playing';
 const qualityNeed=E.standardsAvailable(s);
 const sections:FactorySection[]=['production','inventory','equipment',...(caps.people?['people' as const]:[]),...(qualityNeed?['standards' as const]:[])];
 const active=sections.includes(section)?section:'production',r=recipes.find(r=>r.id===selected)||recipes[0];
 const hours=E.siteHours(s,E.RECIPES,factory),capacity=E.factoryCapacity(s,site),machine=E.machineHours(s,site),staff=E.staffHours(s,site),over=hours>capacity;
 const localCases=recipes.reduce((n,r)=>n+s.plan[r.id],0),localWages=recipes.reduce((n,r)=>n+s.plan[r.id]*conversion(s,r),0);
 const siteNeed=Object.fromEntries(E.INGREDIENTS.map(i=>[i,recipes.reduce((n,r)=>n+(E.variantIngredients(s,r)[i]||0)*s.plan[r.id],0)])) as Record<E.Ingredient,number>;
 const additions=E.RECIPES.filter(r=>E.unlocked(s,r)&&s.growth.assignment[r.id]!==factory);
 return <section className="f3-panel" aria-label={`${definition.name} management`}>
  <header className="f3-heading"><span className="f3-kicker">SAVED WEEKLY PLAN</span><span className="f3-status">{site.paused?'Paused':site.ready>s.week?`Ready W${site.ready}`:manage?(!s.travel.trip&&s.travel.location===E.factoryPlace(factory)?'On site':'Via operations manager'):'Visit to manage'}</span></header>
  <nav className="f3-tabs" aria-label="Factory sections">{sections.map(key=><button key={key} type="button" aria-current={active===key?'page':undefined} className={active===key?'is-active':''} onClick={()=>onSection(key)}>{labels[key]}</button>)}</nav>
  <div className={`f3-capacity${over?' f3-over':''}`} aria-label="This factory capacity">
   <div className="f3-capacity-top"><strong>{decimal(hours)} <span>/ {capacity} h planned</span></strong><span>{over?`${decimal(hours-capacity)} h over capacity`:`${decimal(capacity-hours)} h free`}</span></div>
   <div className="f3-meter" role="meter" aria-label="Factory capacity used" aria-valuemin={0} aria-valuemax={Math.max(1,capacity,hours)} aria-valuenow={hours}><i style={{width:`${Math.min(100,capacity?hours/capacity*100:hours?100:0)}%`}}/></div>
   <div className="f3-capacity-bottom"><span>Machines <b>{machine} h</b></span><span>Team <b>{staff} h</b></span><span><b>{localCases}</b> cases</span><span>Conversion <b>{E.money(localWages)}</b></span></div>
  </div>
  {!manage&&active!=='inventory'?<div className="f3-empty"><h3>Visit this factory to make changes</h3><p>Its saved production plan continues while you are away.</p><button type="button" className="f3-primary" onClick={()=>onNavigate(E.factoryPlace(factory))}>Go to {definition.name}</button></div>:<>
   {active==='production'&&<div className="f3-stack">
    <p className="f3-note">Weekly plan · 20 bars per case · quantities repeat until changed. Each week makes what available ingredients and factory capacity allow.</p>{over&&<p className="f3-warning">{site.ready>s.week?`Commissioning until week ${site.ready}: this site makes no cases yet.`:site.paused?'This site is paused and makes no cases.':staff===0?'Hire a team before this site can produce.':'Capacity limits this site’s output in saved recipe priority order.'} Other factories keep running and your saved targets remain.</p>}
    <div className="v3-chips" aria-label="Factory recipe">{recipes.map(product=><button key={product.id} className={r?.id===product.id?'selected':''} onClick={()=>setSelected(product.id)}>{product.name} · {s.plan[product.id]}</button>)}</div>
    {(r?[r]:[]).map(product=>{const qty=s.plan[product.id],preview=E.productPreview(s,product),others=recipes.filter(x=>x.id!==product.id&&s.plan[x.id]>0),otherHours=others.reduce((n,x)=>n+s.plan[x.id]*x.hours,0),changeover=s.upgrades.includes('flexibility')?0:others.length*8,room=Math.max(0,Math.floor((capacity-otherHours-changeover)/product.hours));return <article className="f3-recipe" key={product.id}>
     <div className="f3-recipe-head"><div className="f3-art"><ProductArt recipe={product.id} small/></div><div><h3>{product.name}</h3><p>{product.segment} · {product.hours} h / case</p></div></div>
     <NumberField label={`${product.name} cases`} value={qty} min={0} max={400} sliderMax={Math.max(1,Math.min(400,Math.floor(capacity/product.hours)))} onChange={qty=>dispatch({type:'plan',recipe:product.id,qty})} disabled={!editable||site.paused||site.ready>s.week} suffix="cases / week"/>
     <div className="f3-row-metrics"><span className={qty>room?'f3-warning':''}>{qty>room?`${qty-room} cases over site capacity`:`Room for ${Math.max(0,room-qty)} more cases`}</span><span>{decimal(qty*product.hours)} process h</span><span>{preview.shortages.length?'~':''}${preview.cost.toFixed(2)} / case</span></div>
     {preview.shortages.length>0&&qty>0&&<button className="f3-text f3-warning" onClick={()=>onSection('inventory')}>Ingredients short · review stock →</button>}
     {qualityNeed&&<button className="f3-text" onClick={()=>{setSelected(product.id);onSection('standards')}}>Quality {preview.quality}/100 · adjust standards →</button>}
    </article>})}
    {!recipes.length&&<p className="f3-empty">Assign a recipe to start this factory’s production plan.</p>}
    {additions.length>0&&<label className="f3-select">Assign a recipe to this factory<select aria-label="Assign recipe to this factory" value="" disabled={!editable} onChange={e=>{const id=e.target.value as RecipeId;if(id)dispatch({type:'assign',recipe:id,factory})}}><option value="">Choose an unlocked recipe…</option>{additions.map(r=><option key={r.id} value={r.id}>{r.name} · from {E.FACTORIES.find(f=>f.id===s.growth.assignment[r.id])!.name}</option>)}</select><small>Moves its saved weekly quantity with it.</small></label>}
    {!s.upgrades.includes('flexibility')&&recipes.filter(r=>s.plan[r.id]>0).length>1&&<p className="f3-note">Changeovers use {(recipes.filter(r=>s.plan[r.id]>0).length-1)*8} h in this plan.</p>}
   </div>}
   {active==='inventory'&&<div className="f3-stack"><div className="f3-subheading"><h3>Shared storeroom</h3><span>Used by every factory</span></div>{E.INGREDIENTS.filter(i=>siteNeed[i]>0||recipes.some(r=>E.variantIngredients(s,r)[i])).map(i=>{const all=E.needed(s)[i],short=Math.max(0,all-s.stock[i].qty),incoming=s.orders.filter(o=>o.ingredient===i);return <article className="f3-stock" key={i}><div className="f3-subheading"><h4>{i}</h4><strong>{decimal(s.stock[i].qty)} kg in stock</strong></div><div className="f3-row-metrics"><span>This factory <b>{decimal(siteNeed[i])} kg</b></span><span>All plans <b>{decimal(all)} kg</b></span></div>{short>0&&<p className="f3-warning">{decimal(short)} kg short across the house</p>}{incoming.length>0&&<p className="f3-note">Incoming: {incoming.map(o=>`${decimal(o.qty)} kg W${o.arrival}`).join(' · ')}</p>}</article>})}<button className="f3-primary" onClick={()=>onNavigate('suppliers')}>Replenish ingredients →</button>{recipes.some(r=>s.goods.some(g=>g.recipe===r.id))&&<><h3>Finished chocolate · shared stock</h3>{recipes.map(r=>{const goods=s.goods.filter(g=>g.recipe===r.id),qty=goods.reduce((n,g)=>n+g.qty,0);return qty>0?<div className="f3-stock" key={r.id}><strong>{r.name}</strong><span>{qty} cases · oldest made W{Math.min(...goods.map(g=>g.born))}</span></div>:null})}</>}</div>}
   {active==='people'&&caps.people&&<People key={factory} s={s} site={site} editable={editable} qualityNeed={qualityNeed} dispatch={dispatch}/>}
   {active==='equipment'&&<div className="f3-stack"><div className="f3-subheading"><h3>On this site</h3><span>{machine} machine hours / week</span></div>{factory==='quay'&&!s.upgrades.includes('capacity')&&<Upgrade s={s} id="capacity" editable={editable} dispatch={dispatch}/>}<div className="f3-stock"><strong>{definition.name}</strong><p>{site.expanded?`Expansion installed · +${definition.extra} h`:`Expansion adds ${definition.extra} machine hours.`}</p>{!site.expanded&&site.ready<=s.week&&<button className="f3-primary" disabled={!editable||s.cash<definition.expansion} onClick={()=>dispatch({type:'factory-expand',id:factory})}>Expand · {E.money(definition.expansion)}</button>}</div><h3>House equipment</h3><p className="f3-note">These improvements apply to every factory.</p>{E.UPGRADES.filter(u=>u.id!=='capacity'&&(s.upgrades.includes(u.id)||E.canManageFactory(s,'quay'))).map(u=><Upgrade key={u.id} s={s} id={u.id} editable={editable&&E.canManageFactory(s,'quay')} dispatch={dispatch}/>)}{!E.canManageFactory(s,'quay')&&<button className="f3-secondary" onClick={()=>onNavigate(E.factoryPlace('quay'))}>Visit San Francisco for house equipment →</button>}{factory!=='quay'&&<div className="f3-stock"><strong>{site.paused?'Reopen this factory':'Pause this factory'}</strong><p>While paused: no production, half payroll, 40% premises cost.</p><button className="f3-secondary" disabled={!editable} onClick={()=>dispatch({type:'factory-pause',id:factory})}>{site.paused?'Resume operations':'Pause operations'}</button></div>}</div>}
   {active==='standards'&&qualityNeed&&r&&<div className="f3-stack"><label className="f3-select">Recipe<select value={r.id} onChange={e=>setSelected(e.target.value as RecipeId)}>{recipes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><Standards s={s} recipe={r} editable={editable} dispatch={dispatch}/></div>}
  </>}
 </section>;
}

function Upgrade({s,id,editable,dispatch}:{s:State;id:E.UpgradeId;editable:boolean;dispatch:FactoryPanelProps['dispatch']}){
 const u=E.UPGRADES.find(u=>u.id===id)!,owned=s.upgrades.includes(id),detail={capacity:'+65 h at San Francisco · +$55 / week',efficiency:'25% lower conversion wages and energy',quality:'+12 quality for all recipes',flexibility:'Remove the 8 h changeover per extra recipe'}[id];
 return <article className="f3-upgrade"><div><h4>{u.name}</h4><p>{detail}</p></div>{owned?<span className="f3-status">Installed</span>:<button className="f3-secondary" disabled={!editable||s.cash<u.cost} onClick={()=>dispatch({type:'upgrade',id})}>Install · {E.money(u.cost)}</button>}</article>;
}

function People({s,site,editable,qualityNeed,dispatch}:{s:State;site:FactoryState;editable:boolean;qualityNeed:boolean;dispatch:FactoryPanelProps['dispatch']}){
 const [workers,setWorkers]=useState(site.workers),[pay,setPay]=useState<PayTier>(site.pay),[lead,setLead]=useState(site.qualityLead);
 useEffect(()=>{setWorkers(site.workers);setPay(site.pay);setLead(site.qualityLead)},[site.workers,site.pay,site.qualityLead]);
 const draft={...site,workers,pay,qualityLead:lead},cost=Math.max(0,workers-site.workers)*150+Math.max(0,site.workers-workers)*E.PAY[site.pay].salary*.5+(lead&&!site.qualityLead?250:0),changed=workers!==site.workers||pay!==site.pay||lead!==site.qualityLead,payroll=E.factoryPayroll(draft);
 return <div className="f3-stack"><div className="f3-subheading"><h3>This factory’s team</h3><strong>{E.money(E.factoryPayroll(site))} / week</strong></div>{site.id==='quay'&&<p className="f3-note">Founding crew: 165 h · $80 / week included.</p>}<NumberField label="Additional workers" value={workers} min={0} max={8} onChange={setWorkers} disabled={!editable} hint="Each hire costs $150. Severance is half a week’s salary."/><label className="f3-select">Team pay<select value={pay} disabled={!editable} onChange={e=>setPay(e.target.value as PayTier)}>{Object.entries(E.PAY).map(([id,p])=><option value={id} key={id}>{p.name} · {E.money(p.salary)} / worker · {p.hours} h</option>)}</select></label>{(qualityNeed||site.qualityLead)&&<label className="f3-check"><input type="checkbox" checked={lead} disabled={!editable} onChange={e=>setLead(e.target.checked)}/><span><strong>Quality lead · +3 quality</strong><small>$250 hiring fee · $100 / week</small></span></label>}<div className="f3-preview"><div><span>Staffed hours</span><strong>{E.staffHours(s,draft)} h</strong></div><div><span>Weekly payroll</span><strong>{E.money(payroll)}</strong></div><div><span>Weekly change</span><strong>{payroll-E.factoryPayroll(site)>=0?'+':''}{E.money(payroll-E.factoryPayroll(site))}</strong></div><div><span>Pay now</span><strong>{E.money(cost)}</strong></div></div>{cost>s.cash&&<p className="f3-warning">Need {E.money(cost-s.cash)} more cash to save this team.</p>}<button className="f3-primary" disabled={!editable||!changed||cost>s.cash} onClick={()=>dispatch({type:'staff',factory:site.id,workers,pay,qualityLead:lead})}>{changed?'Save factory team':'Team saved'}</button></div>;
}

function Standards({s,recipe:r,editable,dispatch}:{s:State;recipe:E.Recipe;editable:boolean;dispatch:FactoryPanelProps['dispatch']}){
 const preview=E.productPreview(s,r),rank=s.productionPriority.indexOf(r.id),contracts=s.contracts.filter(c=>c.status==='active'&&c.recipe===r.id);
 return <><div className="f3-preview"><div><span>Allocated quality</span><strong>{preview.quality} / 100</strong></div><div><span>{preview.shortages.length?'Cost estimate':'Production cost'}</span><strong>{preview.shortages.length?'~':''}${preview.cost.toFixed(2)} / case</strong></div></div>{contracts.map(c=><p className={preview.quality<c.minQuality?'f3-warning':'f3-note'} key={c.id}>{c.client} needs quality {c.minQuality}+.</p>)}<label className="f3-select">Product finish<select disabled={!editable} value={s.position[r.id]} onChange={e=>dispatch({type:'position',recipe:r.id,position:e.target.value as State['position'][RecipeId]})}><option value="value">Value · −8 quality · −$0.70 / case</option><option value="balanced">Standard finish</option><option value="premium">Premium · +5 quality · +$1.30 / case</option></select></label><p className="f3-note">Cocoa grades: standard &lt;75 · select 75–89 · premium 90+.</p>{E.INGREDIENTS.filter(i=>E.variantIngredients(s,r)[i]).map(i=>{const policy=s.ingredientPolicy[r.id][i];return <div className="f3-grade" key={i}><h4>{i}</h4><label className="f3-select">Preferred grade<select aria-label={`${r.name} ${i} preferred grade`} disabled={!editable} value={policy.preferred} onChange={e=>dispatch({type:'policy',recipe:r.id,ingredient:i,...policy,preferred:e.target.value as E.Grade|'any'})}><option value="any">Blend any available grade</option>{E.GRADES.map(g=><option key={g} value={g}>{g}</option>)}</select></label>{policy.preferred!=='any'&&<label className="f3-select">If unavailable<select aria-label={`${r.name} ${i} fallback`} disabled={!editable} value={policy.fallback} onChange={e=>dispatch({type:'policy',recipe:r.id,ingredient:i,...policy,fallback:e.target.value as E.IngredientPolicy['fallback']})}><option value="any">Allow another grade</option><option value="lower">Allow lower grades</option><option value="none">Stop production</option></select></label>}</div>})}{preview.fallback&&<p className="f3-warning">Fallback ingredients are included in this plan.</p>}{preview.shortages.map(x=><p className="f3-warning" key={x}>{x}</p>)}{preview.shortages.length>0&&<p className="f3-note">Missing ingredients use their last average cost in this estimate.</p>}<details className="f3-advanced"><summary>Shared ingredient priority</summary><p className="f3-note">Preferred grades are reserved first; fallback stock follows this house-wide order.</p><div className="f3-priority"><span>Priority {rank+1} of {E.RECIPES.length}</span><button className="f3-secondary" aria-label={`Raise ${r.name} allocation priority`} disabled={!editable||rank===0} onClick={()=>dispatch({type:'priority',recipe:r.id,direction:-1})}>↑ Higher</button><button className="f3-secondary" aria-label={`Lower ${r.name} allocation priority`} disabled={!editable||rank===E.RECIPES.length-1} onClick={()=>dispatch({type:'priority',recipe:r.id,direction:1})}>↓ Lower</button></div></details></>;
}
