import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../game/engine.ts';
const clone=x=>structuredClone(x);
const apply=(s,a)=>{const r=E.act(s,a);assert.equal(r.ok,true,r.message);return r.state};
function fixture(recipe='milk',quality=70,qty=55){return {recipe,quality,qty,born:1,cost:10}}
test('overspending, invalid amounts, locked recipe and insufficient stock are atomic',()=>{let s=E.newGame();for(const a of [{type:'buy',supplier:'dock',ingredient:'cocoa',qty:500},{type:'buy',supplier:'dock',ingredient:'cocoa',qty:-1},{type:'buy',supplier:'dock',ingredient:'cocoa',qty:NaN},{type:'plan',recipe:'orange',qty:3},{type:'price',recipe:'dark',price:Infinity},{type:'repay',amount:4000}]){const before=E.serialize(s),r=E.act(s,a);assert.equal(r.ok,false);assert.equal(r.state,s);assert.equal(E.serialize(s),before)}s.stock.cocoa.qty=0;assert.equal(E.act(s,{type:'advance'}).ok,false)});
test('capacity and wages block week close without consuming inventory',()=>{let s=apply(E.newGame(),{type:'plan',recipe:'dark',qty:120});assert.equal(E.act(s,{type:'advance'}).ok,false);s=E.newGame();s.cash=10;assert.equal(E.act(s,{type:'advance'}).ok,false);});
test('opening production conserves ingredients and reconciles cash',()=>{const s=E.newGame(),r=apply(s,{type:'advance'}),p=r.reports[0];assert.equal(r.stock.cocoa.qty,16.75);assert.equal(r.stock.sugar.qty,9);assert.equal(r.stock.milk.qty,14.5);assert.equal(r.cash,Number((s.cash+p.retail-p.labor-p.overhead).toFixed(2)));assert.equal(p.produced,90);assert.equal(r.week,2);assert.ok(E.INGREDIENTS.every(i=>r.stock[i].qty>=0))});
test('due-week production dispatches before the deadline penalty',()=>{let s=E.newGame();s.week=4;s=apply(s,{type:'accept',id:'ferry'});s=apply(s,{type:'advance'});assert.equal(s.contracts[0].status,'fulfilled');assert.equal(s.fulfilled,1);assert.equal(s.reports[0].penalties,0)});
test('retail cannot consume qualifying stock reserved for an incomplete commission',()=>{let s=E.newGame();s.week=3;s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'accept',id:'hotel'});s.goods=[{...fixture('milk',70,30),born:3},{...fixture('milk',54,55),born:3}];s=apply(s,{type:'advance'});assert.equal(s.contracts[0].status,'active');assert.equal(s.goods.filter(g=>g.quality>=62).reduce((a,g)=>a+g.qty,0),30);assert.ok(s.reports[0].sold>0);});
test('eligible contract auto-ship and deposit plus balance equal face value',()=>{let s=apply(E.newGame(),{type:'accept',id:'ferry'});const deposit=s.cash-3200;s=apply(s,{type:'advance'});assert.equal(deposit+s.reports[0].contract,35*22);assert.equal(s.fulfilled,1);assert.equal(E.act(s,{type:'deliver',id:'ferry'}).ok,false);assert.equal(E.act(s,{type:'accept',id:'ferry'}).ok,false)});
test('delayed balances are collected once in their listed closing week',()=>{let s=E.newGame();s.week=3;s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'accept',id:'hotel'});s.goods=[fixture()];s=apply(s,{type:'deliver',id:'hotel'});assert.equal(s.receivables[0].due,5);assert.equal(s.receivables[0].amount,1100);s=apply(s,{type:'advance'});assert.equal(s.reports[0].collections,0);s=apply(s,{type:'advance'});assert.equal(s.reports[0].collections,0);s=apply(s,{type:'advance'});assert.equal(s.reports[0].collections,1100);assert.equal(s.receivables.length,0);s=apply(s,{type:'advance'});assert.equal(s.reports[0].collections,0)});
test('missing deadline returns deposit, applies penalty and reputation loss once',()=>{let s=E.newGame();s.week=4;s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'accept',id:'ferry'});s=apply(s,{type:'advance'});assert.equal(s.contracts[0].status,'failed');assert.equal(s.reports[0].penalties,92.4);assert.equal(s.reports[0].refunds,192.5);assert.equal(s.reports[0].profit,-322.4);assert.equal(s.reputation,29);s=apply(s,{type:'advance'});assert.equal(s.reports[0].penalties,0)});
test('shipments blend price/quality and the signalled storm shifts new orders',()=>{let s=E.newGame();s.week=6;s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'buy',supplier:'coop',ingredient:'cocoa',qty:20});assert.equal(s.orders[0].arrival,9);const cash=s.cash;for(let n=0;n<3;n++)s=apply(s,{type:'advance'});assert.equal(s.orders.length,0);assert.equal(s.stock.cocoa.qty,100);assert.equal(s.stock.cocoa.quality,72.4);assert.equal(s.cash,cash-3*230)});
test('research, upgrades, choices and emergency finance cannot be claimed twice',()=>{let s=E.newGame();s.cash=10000;s.week=4;for(const a of [{type:'upgrade',id:'capacity'},{type:'credit'},{type:'choice',id:'choice-growers',choice:'growers'}]){s=apply(s,a);assert.equal(E.act(s,a).ok,false)}s=apply(s,{type:'research',id:'citrus'});assert.equal(E.act(s,{type:'research',id:'praline'}).ok,false);s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'advance'});assert.ok(s.research.includes('citrus'));assert.equal(E.act(s,{type:'research',id:'citrus'}).ok,false)});
test('bankruptcy takes precedence over a campaign review',()=>{let s=E.newGame();s.week=16;s.cash=1;s.debt=0;s.fulfilled=4;s.signature=1;s.reputation=80;s.markets=['quay','hill'];s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'advance'});assert.equal(s.status,'lost');assert.ok(s.ending.includes('Cash'))});
test('campaign victory requires all charter conditions and continues to sandbox',()=>{let s=E.newGame();s.week=16;s.cash=5000;s.debt=0;s.fulfilled=4;s.signature=1;s.reputation=80;s.markets=['quay','hill'];s.plan.dark=0;s.plan.milk=0;const win=apply(s,{type:'advance'});assert.equal(win.status,'won');assert.equal(apply(win,{type:'continue'}).mode,'sandbox');for(const key of ['debt','fulfilled','signature','reputation','markets']){const v=clone(s);if(key==='markets')v.markets=['quay'];else v[key]=key==='debt'?1:key==='fulfilled'?3:key==='reputation'?64:0;assert.equal(apply(v,{type:'advance'}).status,'lost',key)}});
test('versioned saves round-trip and reject damaged chronology, duplicates and numbers',()=>{const s=apply(E.newGame(),{type:'advance'});assert.deepEqual(E.deserialize(E.serialize(s)),s);for(const mutate of [p=>p.version=999,p=>p.state.cash=null,p=>p.state.markets=['quay','quay'],p=>p.state.fulfilled=-1,p=>p.state.goods=[fixture('dark',70,1),{...fixture('dark',70,1),born:999}],p=>p.state.plan.orange=1,p=>delete p.state.reports[0].openingCash]){let p=JSON.parse(E.serialize(s));mutate(p);assert.throws(()=>E.deserialize(JSON.stringify(p)))}assert.throws(()=>E.deserialize('not json'))});
test('same state/action inputs are deterministic and source state is unmodified',()=>{const s=E.newGame(),raw=E.serialize(s),a={type:'advance'};assert.deepEqual(E.act(s,a),E.act(s,a));assert.equal(E.serialize(s),raw)});
test('forecast accounts for auto-dispatch and penalties',()=>{let s=apply(E.newGame(),{type:'accept',id:'ferry'});const f=E.forecast(s),r=apply(s,{type:'advance'});assert.equal(f.sales,1170);assert.equal(f.contractCash,577.5);assert.equal(f.closing,r.cash);s=E.newGame();s.week=4;s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'accept',id:'ferry'});assert.equal(E.forecast(s).penalties,284.9)});
function playCampaign(seed=42,signature='orange'){
 let s=E.newGame('campaign',seed);
 for(let week=1;week<=16;week++){
  if(week===1)s=apply(s,{type:'accept',id:'ferry'});
  if(week===2){s=apply(s,{type:'upgrade',id:'quality'});s=apply(s,{type:'research',id:signature==='orange'?'citrus':'praline'});}
  if(week===3)s=apply(s,{type:'accept',id:'hotel'});
  if(week===4){s=apply(s,{type:'choice',id:'choice-growers',choice:'growers'});s=apply(s,{type:'expand',id:'hill'});}
  if(week===5)s=apply(s,{type:'upgrade',id:'capacity'});
  if(week===6&&signature==='orange'){s=apply(s,{type:'accept',id:'citrus-fair'});s=apply(s,{type:'plan',recipe:'dark',qty:50});s=apply(s,{type:'plan',recipe:'milk',qty:30});s=apply(s,{type:'plan',recipe:'orange',qty:48});}
  if(week===7&&signature==='orange')s=apply(s,{type:'plan',recipe:'orange',qty:0});
  if(week===8){s=apply(s,{type:'accept',id:'rail-order'});s=apply(s,{type:'plan',recipe:'dark',qty:75});s=apply(s,{type:'choice',id:'choice-rival',choice:'independent'});}
  if(week===10&&signature==='praline'){s=apply(s,{type:'accept',id:'salon'});s=apply(s,{type:'plan',recipe:'dark',qty:50});s=apply(s,{type:'plan',recipe:'milk',qty:30});s=apply(s,{type:'plan',recipe:'praline',qty:40});}
  if(week===11&&signature==='praline')s=apply(s,{type:'plan',recipe:'praline',qty:0});
  const needed=E.needed(s);for(const i of E.INGREDIENTS){const missing=Math.ceil(needed[i]-s.stock[i].qty);if(missing>0)s=apply(s,{type:'buy',supplier:'dock',ingredient:i,qty:missing});}
  if(week===16)s=apply(s,{type:'repay',amount:s.debt});
  s=apply(s,{type:'advance'});
  assert.ok(E.INGREDIENTS.every(i=>s.stock[i].qty>=0));assert.ok(s.goods.every(g=>g.qty>=0));
 }
 return s;
}
test('complete citrus and praline campaign routes win across 20 demand seeds',()=>{for(const signature of ['orange','praline'])for(let seed=0;seed<20;seed++){const s=playCampaign(seed,signature);assert.equal(s.status,'won',`${signature} seed ${seed}: ${s.ending}`);assert.equal(s.debt,0);assert.equal(s.signature,1);assert.equal(s.fulfilled,4);assert.deepEqual(E.deserialize(E.serialize(s)),s);}});
test('manual and automatic dispatch recognize identical contract income and cost once',()=>{let base=E.newGame();base.plan.dark=0;base.plan.milk=0;base.goods=[fixture('dark',70,35)];base=apply(base,{type:'accept',id:'ferry'});const automatic=apply(base,{type:'advance'}),manual=apply(apply(base,{type:'deliver',id:'ferry'}),{type:'advance'});assert.equal(manual.cash,automatic.cash);assert.equal(manual.reports[0].profit,automatic.reports[0].profit);assert.equal(manual.reports[0].contractRevenue,770);assert.equal(manual.reports[0].costOfSales,350);assert.equal(manual.reports[0].profit,190);const next=apply(manual,{type:'advance'});assert.equal(next.reports[0].contractRevenue,0)});
test('week-opening cash reconciles every planning action and settlement flow',()=>{let s=E.newGame();s.week=4;s=apply(s,{type:'buy',supplier:'dock',ingredient:'cocoa',qty:10});s=apply(s,{type:'accept',id:'ferry'});s=apply(s,{type:'credit'});s=apply(s,{type:'repay',amount:100});s=apply(s,{type:'choice',id:'choice-growers',choice:'growers'});s=apply(s,{type:'upgrade',id:'efficiency'});s=apply(s,{type:'advance'});const r=s.reports[0];const closing=r.openingCash-r.purchases-r.investments+r.deposits-r.repayments+r.credit+r.story+r.retail+r.contract+r.collections-r.labor-r.overhead-r.penalties-r.refunds;assert.equal(Number(closing.toFixed(2)),r.closingCash);assert.equal(s.book.openingCash,s.cash)});
test('bars expire after exactly three selling weeks; ganache after one',()=>{let s=E.newGame('sandbox');s.plan.dark=0;s.plan.milk=0;s.prices.dark=80;s.goods=[fixture('dark',70,1000)];for(let n=0;n<3;n++)s=apply(s,{type:'advance'});assert.equal(s.goods.length,0);assert.ok(s.reports[0].spoiled>0);let t=E.newGame('sandbox');t.research=['truffle'];t.plan.dark=0;t.plan.milk=0;t.prices.truffle=80;t.goods=[fixture('truffle',70,1000)];t=apply(t,{type:'advance'});assert.equal(t.goods.length,0);assert.ok(t.reports[0].spoiled>0);});
test('lower-grade dispatch preserves scarce premium stock for a stricter contract',()=>{let s=E.newGame();s.plan.dark=0;s.plan.milk=0;s.goods=[fixture('dark',90,30),fixture('dark',60,35)];const c={client:'Fixture',recipe:'dark',unitPrice:22,minQuality:80,due:4,delay:1,deposit:0,accepted:true,status:'active',reward:1};s.contracts=[{...c,id:'high',qty:60},{...c,id:'low',qty:35,minQuality:50}];s=apply(s,{type:'advance'});assert.equal(s.contracts[1].status,'fulfilled');assert.equal(s.goods.filter(g=>g.quality===90).reduce((a,g)=>a+g.qty,0),30);});
test('malformed collections receive intentional save errors rather than runtime TypeErrors',()=>{for(const mutate of [s=>s.research=null,s=>s.contracts=[null],s=>s.goods=[null],s=>s.orders=[null],s=>s.reports=[{week:1,rows:[null]}]]){const p=JSON.parse(E.serialize(E.newGame()));mutate(p.state);assert.throws(()=>E.deserialize(JSON.stringify(p)),e=>e instanceof Error&&!(e instanceof TypeError));}});
function gradesFixture(){const s=E.newGame();s.research=['origin'];s.plan.dark=20;s.plan.milk=0;s.plan.origin=20;s.ingredientLots=s.ingredientLots.filter(l=>l.ingredient!=='cocoa');s.ingredientLots.push({id:'standard-cocoa',ingredient:'cocoa',grade:'standard',qty:50,cost:7,quality:54},{id:'premium-cocoa',ingredient:'cocoa',grade:'premium',qty:21,cost:10,quality:96});s.stock.cocoa={qty:71,cost:7.89,quality:66.42};return s}
test('preferred premium ingredients are reserved before earlier products use fallback or blends',()=>{let s=gradesFixture();s=apply(s,{type:'policy',recipe:'origin',ingredient:'cocoa',preferred:'premium',fallback:'none'});const before=E.serialize(s),p=E.allocateProduction(s);assert.equal(p.products.origin.quality,96);assert.equal(p.products.dark.quality,54);assert.equal(p.products.origin.usage.filter(x=>x.ingredient==='cocoa').reduce((a,x)=>a+x.qty,0),21);assert.equal(E.serialize(s),before);const next=apply(s,{type:'advance'});assert.equal(next.stock.cocoa.qty,34);assert.equal(next.stock.cocoa.quality,54);assert.equal(next.reports[0].rows.find(r=>r.recipe==='origin').quality,96);assert.equal(E.deserialize(E.serialize(next)).ingredientLots[0].id,next.ingredientLots[0].id)});
test('strict grade shortage blocks atomically and allowed fallback changes realized quality',()=>{let s=E.newGame();s=apply(s,{type:'policy',recipe:'dark',ingredient:'cocoa',preferred:'premium',fallback:'none'});const before=E.serialize(s),result=E.act(s,{type:'advance'});assert.equal(result.ok,false);assert.match(result.message,/grade policy/);assert.equal(E.serialize(s),before);s=apply(s,{type:'policy',recipe:'dark',ingredient:'cocoa',preferred:'premium',fallback:'lower'});const p=E.allocateProduction(s).products.dark;assert.equal(p.fallback,true);assert.equal(p.quality,70);assert.equal(E.act(s,{type:'advance'}).ok,true)});
test('competing explicit grade reservations respect saved production priority',()=>{let s=gradesFixture();for(const recipe of ['dark','origin'])s=apply(s,{type:'policy',recipe,ingredient:'cocoa',preferred:'premium',fallback:'any'});let p=E.allocateProduction(s);assert.equal(p.products.dark.quality,96);assert.ok(p.products.origin.quality<96);while(s.productionPriority[0]!=='origin')s=apply(s,{type:'priority',recipe:'origin',direction:-1});p=E.allocateProduction(s);assert.equal(p.products.origin.quality,96);assert.equal(p.products.dark.quality,54);assert.deepEqual(E.deserialize(E.serialize(s)).productionPriority,s.productionPriority)});
test('fractional allocation conserves ingredient quantity and acquisition value',()=>{let s=gradesFixture();s.plan.dark=17;s.plan.origin=13;const allocation=E.allocateProduction(s),used=Object.values(allocation.products).flatMap(p=>p.usage),beforeValue=s.ingredientLots.reduce((n,l)=>n+l.qty*l.cost,0),usedValue=used.reduce((n,l)=>n+l.qty*l.cost,0);const next=apply(s,{type:'advance'});const afterValue=next.ingredientLots.reduce((n,l)=>n+l.qty*l.cost,0);assert.ok(Math.abs(beforeValue-usedValue-afterValue)<1e-8);assert.ok(Math.abs(s.stock.cocoa.qty-next.stock.cocoa.qty-(17*.8+13*1.05))<1e-8);assert.deepEqual(E.deserialize(E.serialize(next)),next)});
test('contract warning identifies quality failure from permitted fallback',()=>{let s=E.newGame();s.week=11;s.research=['origin'];s.plan.dark=0;s.plan.milk=0;s.plan.origin=35;s=apply(s,{type:'accept',id:'origin-club'});s=apply(s,{type:'policy',recipe:'origin',ingredient:'cocoa',preferred:'premium',fallback:'lower'});assert.match(E.gradeWarnings(s)[0],/fallback ingredients produce 70.*requires 85/);const preview=E.forecast(s),next=apply(s,{type:'advance'});assert.equal(preview.contractCash,0);assert.equal(next.contracts[0].status,'active');assert.equal(next.reports[0].rows.find(r=>r.recipe==='origin').quality,70)});
test('repeat purchases preserve per-ingredient supplier and quantity; failed repeat is atomic',()=>{let s=E.newGame();s=apply(s,{type:'buy',supplier:'estate',ingredient:'cocoa',qty:11});s=apply(s,{type:'buy',supplier:'dock',ingredient:'sugar',qty:9});const reloaded=E.deserialize(E.serialize(s));s=apply(reloaded,{type:'repeat',ingredient:'cocoa'});assert.equal(s.orders.length,2);assert.equal(s.orders[1].supplier,'estate');assert.equal(s.orders[1].quality,96);assert.equal(s.orders[1].qty,11);s=apply(s,{type:'repeat',ingredient:'sugar'});assert.equal(s.stock.sugar.qty,63);assert.deepEqual(s.repeatOrders.sugar,{supplier:'dock',qty:9});s.cash=0;const before=E.serialize(s),result=E.act(s,{type:'repeat',ingredient:'cocoa'});assert.equal(result.ok,false);assert.equal(result.state,s);assert.equal(E.serialize(s),before);assert.equal(E.act(s,{type:'repeat',ingredient:'nuts'}).ok,false)});
test('delayed premium orders preserve grade and arrive without raw-material expiry',()=>{let s=E.newGame();s.plan.dark=0;s.plan.milk=0;s=apply(s,{type:'buy',supplier:'estate',ingredient:'cocoa',qty:20});const paid=s.orders[0].cost;for(let n=0;n<3;n++)s=apply(s,{type:'advance'});const lot=s.ingredientLots.find(l=>l.grade==='premium');assert.equal(lot.qty,20);assert.equal(lot.quality,96);assert.equal(lot.cost,paid);assert.equal(s.stock.cocoa.qty,100);assert.equal(s.orders.length,0)});
test('v2 migration preserves assets and historic outcomes without inventing source grades',()=>{const old=E.newGame();old.week=9;old.version=2;for(const k of ['ingredientLots','ingredientPolicy','productionPriority','repeatOrders','tutorial'])delete old[k];const migrated=E.deserialize(JSON.stringify({version:2,state:old}));assert.equal(migrated.version,3);assert.deepEqual(migrated.stock,old.stock);assert.equal(migrated.cash,old.cash);assert.equal(migrated.tutorial.enabled,false);assert.deepEqual(migrated.repeatOrders,{});assert.ok(migrated.ingredientLots.every(l=>l.id.startsWith('legacy-')));assert.deepEqual(E.deserialize(E.serialize(migrated)),migrated)});
test('damaged lots, preferences, priority and repeat presets reject without repairing v3',()=>{for(const mutate of [s=>s.ingredientLots[0].qty+=1,s=>s.ingredientPolicy.dark.cocoa.preferred='bogus',s=>s.productionPriority[0]='milk',s=>s.repeatOrders.cocoa={supplier:'estate',qty:501},s=>s.tutorial.completed=['bogus']]){const s=E.newGame();mutate(s);assert.throws(()=>E.deserialize(E.serialize(s)),/damaged|match/)}});
test('position demand follows segment preference and never reads acquisition cost',()=>{for(const r of E.RECIPES){const s=E.newGame();s.research=['citrus','praline','origin','truffle'];const values=['value','balanced','premium'].map(position=>E.demand({...s,position:{...s.position,[r.id]:position}},r));if(r.segment==='Everyday')assert.ok(values[0]>values[1]&&values[1]>values[2]);else assert.ok(values[0]<values[1]&&values[1]<values[2]);const before=E.demand(s,r);s.ingredientLots=s.ingredientLots.map(l=>({...l,cost:l.cost*10}));assert.equal(E.demand(s,r),before)}});
test('guide progress survives saves and never restricts real game actions',()=>{let s=apply(E.newGame(),{type:'tutorial',complete:'production'});s=apply(s,{type:'tutorial',enabled:false});s=E.deserialize(E.serialize(s));assert.equal(s.tutorial.enabled,false);assert.deepEqual(s.tutorial.completed,['production']);s=apply(s,{type:'advance'});s=apply(s,{type:'buy',supplier:'coop',ingredient:'milk',qty:10});assert.ok(s.tutorial.completed.includes('supply'));assert.equal(s.week,2)});
test('imported stale serial cannot create duplicate raw lots or shipment IDs',()=>{let s=apply(E.newGame(),{type:'buy',supplier:'dock',ingredient:'cocoa',qty:3});s.serial=0;s=E.deserialize(E.serialize(s));s=apply(s,{type:'buy',supplier:'dock',ingredient:'cocoa',qty:4});assert.equal(new Set(s.ingredientLots.map(l=>l.id)).size,s.ingredientLots.length);s=apply(s,{type:'buy',supplier:'coop',ingredient:'milk',qty:5});s.serial=0;s=apply(s,{type:'buy',supplier:'coop',ingredient:'milk',qty:5});assert.equal(new Set(s.orders.map(l=>l.id)).size,s.orders.length);assert.deepEqual(E.deserialize(E.serialize(s)),s)});
test('rounded quote accepts an exact-cash repeat and rejects one cent less atomically',()=>{let s=E.newGame();s.week=4;s.repeatOrders.cocoa={supplier:'dock',qty:7};s.cash=55.58;assert.equal(E.orderTotal(s,'dock','cocoa',7),55.58);const bought=apply(s,{type:'repeat',ingredient:'cocoa'});assert.equal(bought.cash,0);s.cash=55.57;const before=E.serialize(s);assert.equal(E.act(s,{type:'repeat',ingredient:'cocoa'}).ok,false);assert.equal(E.serialize(s),before)});
