import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as Engine from '../game/engine.ts';
// Existing economy scenarios exercise the preserved legacy rules; V3 has separate journey coverage.
const E={...Engine,newGame:(mode='campaign',seed=42)=>Engine.newGame(mode,seed,'legacy')};
test('growth migrations, factory timing, automation reserves and buyer recovery',()=>{const console={log:()=>{}};

const legacy=fs.readFileSync('docs/qa/revision/legacy-v2-week17.json','utf8');let s;const outcomes=[];
function act(a){const r=E.act(s,a);assert.equal(r.ok,true,r.message);s=r.state;return s}
function check(name,fn){try{fn();outcomes.push({name,passed:true})}catch(e){outcomes.push({name,passed:false,error:e.message})}}
function restock(){for(const i of E.INGREDIENTS){const q=Math.ceil(E.needed(s)[i]-s.stock[i].qty);if(q>0)act({type:'buy',supplier:'dock',ingredient:i,qty:q})}}
check('v2 actual migration',()=>{s=E.deserialize(legacy);assert.equal(s.version,E.SAVE_VERSION);assert.equal(s.cash,8154.33);assert.equal(s.growth.chapter,'growth');assert.deepEqual(E.deserialize(E.serialize(s)),s)});
for(const v of [3,4])check(`representative v${v} migration`,()=>{const p=JSON.parse(E.serialize(E.deserialize(legacy)));p.version=v;p.state.version=v;delete p.state.travel;delete p.state.stock.tea;for(const id of ['gianduja','tea']){delete p.state.plan[id];delete p.state.prices[id];delete p.state.position[id];delete p.state.ingredientPolicy[id];delete p.state.growth.assignment[id]}for(const row of Object.values(p.state.ingredientPolicy))delete row.tea;p.state.productionPriority=p.state.productionPriority.filter(x=>!['gianduja','tea'].includes(x));delete p.state.growth.purchasing.tea;if(v===3){delete p.state.growth;delete p.state.marketPrices}const migrated=E.deserialize(JSON.stringify(p));assert.deepEqual(E.deserialize(E.serialize(migrated)),migrated);assert.equal(migrated.plan.tea,0);assert.equal(migrated.stock.tea.qty,0)});
check('failed acquisition/hiring is atomic',()=>{s=E.deserialize(legacy);s.week=20;s.cash=1;for(const a of [{type:'factory',id:'riverside'},{type:'factory-expand',id:'quay'},{type:'staff',factory:'quay',workers:3,pay:'senior',qualityLead:true}]){const before=E.serialize(s),r=E.act(s,a);assert.equal(r.ok,false);assert.equal(r.state,s);assert.equal(E.serialize(s),before)}});
check('commissioning costs and staffing timing',()=>{s=E.deserialize(legacy);s.week=18;const base=E.overhead(s);act({type:'factory',id:'riverside'});act({type:'staff',factory:'riverside',workers:2,pay:'standard',qualityLead:true});assert.equal(E.overhead(s),base);assert.equal(E.capacity(s),165);restock();act({type:'advance'});assert.equal(E.overhead(s),base);restock();act({type:'advance'});assert.equal(E.capacity(s),285);assert.equal(E.overhead(s),base+190+100+140);act({type:'factory-pause',id:'riverside'});assert.equal(E.capacity(s),165);assert.equal(E.overhead(s),base+145+56)});
check('automatic purchasing respects reserved cash and incoming grade',()=>{s=E.deserialize(legacy);s.week=20;s.cash=2200;act({type:'purchase-rule',ingredient:'cocoa',enabled:true,supplier:'coop',target:200});act({type:'purchase-rule',ingredient:'sugar',enabled:true,supplier:'dock',target:100});act({type:'reserve',amount:500});act({type:'buy',ingredient:'cocoa',supplier:'coop',qty:40});const p=E.purchasingPreview(s),row=p.find(x=>x.ingredient==='cocoa');assert.equal(row.coverage,40);assert.equal(row.wanted,160);const total=p.reduce((n,x)=>n+x.cost,0),labor=E.forecast(s).labor;assert.ok(total<=s.cash-s.growth.reserve-E.overhead(s)-labor+.01);assert.ok(s.cash-total>=500+E.overhead(s)+labor-.01)});
check('standing order preserves accepted terms on later edit and queues no duplicate',()=>{s=E.deserialize(legacy);s.week=20;act({type:'buyer',id:'cafes',enabled:true,recipe:'milk',terms:'extended'});const contract=structuredClone(s.contracts.find(c=>c.buyerId==='cafes')),cash=s.cash;act({type:'buyer',id:'cafes',enabled:true,recipe:'dark',terms:'fast'});assert.deepEqual(s.contracts.find(c=>c.id===contract.id),contract);assert.equal(s.cash,cash);act({type:'buyer',id:'cafes',enabled:false,recipe:'dark',terms:'fast'});assert.equal(s.contracts.find(c=>c.id===contract.id).status,'active')});
check('buyer miss, cooldown, recovery and delayed proceeds',()=>{s=E.deserialize(legacy);s.week=20;act({type:'plan',recipe:'milk',qty:0});act({type:'buyer',id:'cafes',enabled:true,recipe:'milk',terms:'extended'});restock();act({type:'advance'});restock();act({type:'advance'});assert.equal(s.growth.buyers.cafes.missed,1);assert.equal(s.growth.buyers.cafes.trust,30);assert.equal(s.growth.buyers.cafes.next,24);act({type:'plan',recipe:'milk',qty:50});while(s.week<=24){restock();act({type:'advance'})}assert.equal(s.growth.buyers.cafes.delivered,1);assert.equal(s.growth.buyers.cafes.trust,42);const receivable=s.receivables.find(r=>r.id==='standing-cafes-24');assert.equal(receivable.due,26);assert.equal(s.status,'playing')});
check('conservative single factory path defers review without losing business',()=>{s=E.deserialize(legacy);while(s.week<=37){restock();act({type:'advance'});assert.equal(s.status,'playing');assert.deepEqual(E.deserialize(E.serialize(s)),s)}assert.equal(s.growth.awarded,false);assert.equal(s.growth.reviewWeek,40);assert.ok(s.cash>8154);outcomes.push({conservativeFinal:{cash:s.cash,week:s.week,review:s.growth.reviewWeek}})});
console.log(JSON.stringify(outcomes,null,2));assert.ok(outcomes.every(x=>x.passed!==false),JSON.stringify(outcomes));

});
test('durable weekly settings and combined two-factory shortage allocation',()=>{const console={log:()=>{}};
let s=E.deserialize(fs.readFileSync('docs/qa/revision/legacy-v2-week17.json','utf8'));function act(a){const r=E.act(s,a);assert.ok(r.ok,r.message);s=r.state}function supply(){for(const i of E.INGREDIENTS){const n=Math.ceil(E.needed(s)[i]-s.stock[i].qty);if(n>0)act({type:'buy',supplier:'dock',ingredient:i,qty:n})}}
// Automate complete ordinary weeks, bridging only the initial empty storeroom.
act({type:'reserve',amount:1000});for(const [ingredient,target] of [['cocoa',190],['sugar',110],['milk',50]])act({type:'purchase-rule',ingredient,enabled:true,supplier:'dock',target});supply();const plan=structuredClone(s.plan);let purchases=0;for(let n=0;n<8;n++){assert.deepEqual(s.plan,plan);assert.deepEqual(E.blockers(s),[]);act({type:'advance'});purchases+=s.book.purchases;assert.ok(s.cash>=1000);assert.deepEqual(E.deserialize(E.serialize(s)),s)}assert.ok(purchases>0);console.log('PASS: eight ordinary weeks advance without re-entering production, supply or staff; automatic purchasing spends',purchases,'cash',s.cash);
// Add second factory and two markets; shortage reduces output and preserves saved targets.
act({type:'factory',id:'riverside'});act({type:'staff',factory:'riverside',workers:2,pay:'standard',qualityLead:false});for(let n=0;n<2;n++)act({type:'advance'});act({type:'assign',recipe:'orange',factory:'riverside'});act({type:'plan',recipe:'orange',qty:80});act({type:'buyer',id:'department',enabled:true,recipe:'orange',terms:'standard'});act({type:'campaign',id:'gifting'});const before=E.serialize(s);const blocked=E.act(s,{type:'advance'});assert.equal(blocked.ok,true);assert.equal(blocked.state.reports[0].rows.find(r=>r.recipe==='orange').made,0);assert.equal(blocked.state.plan.orange,80);assert.equal(E.serialize(s),before);supply();const need=E.needed(s),old=structuredClone(s),f=E.forecast(s);act({type:'advance'});const r=s.reports[0],c=s.contracts.find(c=>c.buyerId==='department');assert.equal(c.status,'fulfilled');assert.equal(r.contractRevenue,c.qty*c.unitPrice);assert.equal(r.produced,185);assert.ok(r.sold<=185-c.qty);assert.equal(r.overhead,f.overhead);assert.equal(r.labor,f.labor);assert.deepEqual(E.deserialize(E.serialize(s)),s);console.log('PASS: shortage + standing contract + demand campaign + two factories; produces',r.produced,'retail',r.sold,'contract',c.qty,'without duplicate stock/costs');

});
test('strong expansion strategy reaches a profitable week-36 network win',()=>{const console={log:()=>{}};


const legacy=fs.readFileSync('docs/qa/revision/legacy-v2-week17.json','utf8');
let s=E.deserialize(legacy); const steps=[];
function act(a){const r=E.act(s,a);if(!r.ok)throw Error(`W${s.week} ${JSON.stringify(a)}: ${r.message}`);s=r.state;return s}
function stock(){for(const i of E.INGREDIENTS){const target=Math.ceil(E.needed(s)[i]*1.2),qty=Math.max(0,target-Math.floor(s.stock[i].qty));if(qty)act({type:'buy',supplier:'dock',ingredient:i,qty})}}
for(;s.week<=37;){
 const w=s.week;
 if(w===17){act({type:'upgrade',id:'efficiency'});act({type:'upgrade',id:'flexibility'});act({type:'plan',recipe:'dark',qty:75});act({type:'plan',recipe:'milk',qty:90});}
 if(w===18){act({type:'factory',id:'riverside'});act({type:'staff',factory:'riverside',workers:2,pay:'standard',qualityLead:false});}
 if(w===20){act({type:'assign',recipe:'orange',factory:'riverside'});act({type:'plan',recipe:'orange',qty:80});act({type:'buyer',id:'cafes',enabled:true,recipe:'milk',terms:'fast'});act({type:'buyer',id:'department',enabled:true,recipe:'orange',terms:'extended'});act({type:'expand',id:'rail'});}
 if(w===23){act({type:'partnership',id:'boutique'});act({type:'expand',id:'paris'});act({type:'campaign',id:'gifting'});}
 if(w===24){act({type:'factory-expand',id:'quay'});act({type:'staff',factory:'quay',workers:2,pay:'standard',qualityLead:false});act({type:'plan',recipe:'dark',qty:110});act({type:'plan',recipe:'milk',qty:125});}
 if(w===27){act({type:'factory-expand',id:'riverside'});act({type:'staff',factory:'riverside',workers:3,pay:'standard',qualityLead:false});act({type:'plan',recipe:'orange',qty:130});}
 stock();const before=structuredClone(s),need=E.needed(s),fore=E.forecast(s);act({type:'advance'});const r=s.reports[0];for(const i of E.INGREDIENTS)assert.ok(Math.abs(before.stock[i].qty-need[i]-s.stock[i].qty)<.011,`stock ${i}`);assert.equal(r.produced,Object.values(before.plan).reduce((a,b)=>a+b,0));assert.equal(r.overhead,fore.overhead);assert.equal(r.labor,fore.labor);assert.ok(r.sold<=r.produced+before.goods.reduce((n,g)=>n+g.qty,0));assert.deepEqual(E.deserialize(E.serialize(s)),s);steps.push({w,cash:s.cash,profit:r.profit,produced:r.produced,sold:r.sold,buyers:Object.fromEntries(Object.entries(s.growth.buyers).map(([id,b])=>[id,[b.delivered,b.missed,b.trust]])),status:s.status});if(s.status==='won')act({type:'continue'});if(s.status==='lost')break;
}
console.log(JSON.stringify({path:'strong',steps,goals:E.growthGoals(s),awarded:s.growth.awarded},null,2));


assert.equal(s.growth.awarded,true);assert.equal(s.growth.chapter,'endless');
});
test('international discovery, ingredient pilots, commercial quest and factory access',()=>{const console={log:()=>{}};
let s=E.deserialize(fs.readFileSync('docs/qa/revision/legacy-v2-week17.json','utf8'));const events=[];
const save=()=>{s=E.deserialize(E.serialize(s));return s};
function act(a){const before=E.serialize(s),r=E.act(s,a);assert.ok(r.ok,`W${s.week} ${JSON.stringify(a)}: ${r.message}`);assert.equal(E.serialize(s),before);s=r.state;save();return s}
function reject(a){const before=E.serialize(s),r=E.act(s,a);assert.equal(r.ok,false,JSON.stringify(a));assert.equal(E.serialize(s),before);assert.equal(r.state,s)}
function supplies(){for(const i of E.INGREDIENTS){const n=E.purchaseShortfall(s,i).quantity;if(n>0)act({type:'buy',supplier:'dock',ingredient:i,qty:n})}}
function close(){supplies();act({type:'advance'});events.push({week:s.week,cash:s.cash,location:s.travel.location,trip:s.travel.trip});assert.equal(s.status,'playing')}
function trip(to){const cash=s.cash,week=s.week;act({type:'travel',to});if(to==='sf')assert.equal(s.cash,cash);const arrival=s.travel.trip.arrival;reject({type:'travel',to});reject({type:'visit',id:'paris-brief'});while(s.week<arrival)close();assert.equal(s.travel.location,to);assert.equal(s.travel.trip,null);save()}
reject({type:'buy',ingredient:'tea',supplier:'dock',qty:10});reject({type:'pilot',recipe:'gianduja',variant:'intense'});reject({type:'research',id:'turin'});
act({type:'buy',ingredient:'cocoa',supplier:'coop',qty:150});trip('paris');act({type:'visit',id:'paris-brief'});act({type:'visit',id:'paris-technique'});reject({type:'visit',id:'paris-technique'});assert.equal(E.offers(s).some(c=>c.id==='paris-tasting'),false);
trip('turin');const beforeNuts=E.quote(s,'dock','nuts');act({type:'visit',id:'turin-sample'});assert.ok(Math.abs(E.quote(s,'dock','nuts')-beforeNuts*.9)<.015);const sample=s.orders.find(o=>o.ingredient==='nuts');assert.equal(sample.qty,12);assert.equal(sample.arrival,s.week+1);act({type:'visit',id:'turin-technique'});reject({type:'visit',id:'turin-sample'});reject({type:'pilot',recipe:'gianduja',variant:'intense'});
trip('guayaquil');act({type:'visit',id:'ecuador-profile'});const oldQuote=E.quote(s,'coop','cocoa'),oldLead=E.lead(s,'coop');act({type:'visit',id:'ecuador-direct'});assert.ok(Math.abs(E.quote(s,'coop','cocoa')-oldQuote*.88)<.015);assert.equal(E.lead(s,'coop'),Math.max(1,oldLead-1));reject({type:'visit',id:'ecuador-direct'});reject({type:'pilot',recipe:'gianduja',variant:'intense'});act({type:'buy',ingredient:'cocoa',supplier:'coop',qty:200});assert.equal(s.orders.at(-1).arrival,s.week+1);trip('sf');assert.ok(s.stock.nuts.qty>=12);
act({type:'policy',recipe:'gianduja',ingredient:'cocoa',preferred:'select',fallback:'none'});reject({type:'pilot',recipe:'gianduja',variant:'intense'});act({type:'buy',ingredient:'sugar',supplier:'dock',qty:5});act({type:'buy',ingredient:'milk',supplier:'dock',qty:3});const beforePilot=structuredClone(s),oldGoods=structuredClone(s.goods);act({type:'pilot',recipe:'gianduja',variant:'intense'});const recipe=E.RECIPES.find(r=>r.id==='gianduja');for(const [i,q] of Object.entries(E.variantIngredients(s,recipe)))assert.ok(Math.abs(beforePilot.stock[i].qty-s.stock[i].qty-q*8)<.011);assert.equal(beforePilot.cash-s.cash,180);assert.deepEqual(s.goods,oldGoods);assert.equal(s.travel.variants.gianduja,'intense');assert.ok(s.research.includes('turin'));reject({type:'pilot',recipe:'gianduja',variant:'balanced'});assert.equal(E.offers(s).filter(c=>c.id==='paris-tasting').length,1);
act({type:'accept',id:'paris-tasting'});act({type:'plan',recipe:'dark',qty:50});act({type:'plan',recipe:'milk',qty:30});act({type:'plan',recipe:'gianduja',qty:25});supplies();const brandBefore=s.growth.brand;close();const order=s.contracts.find(c=>c.id==='paris-tasting');assert.equal(order.status,'fulfilled');assert.equal(order.qty,25);assert.equal(s.reports[0].contractRevenue,25*46);assert.equal(E.offers(s).some(c=>c.id==='paris-tasting'),false);reject({type:'deliver',id:'paris-tasting'});const reward={brandBefore,brandAfter:s.growth.brand,partnerships:s.growth.partnerships};assert.equal(s.growth.brand,brandBefore+10);assert.ok(s.growth.partnerships.includes('boutique'));
// Pilot used up select cocoa over time; general blends now allow normal ongoing production.
act({type:'policy',recipe:'gianduja',ingredient:'cocoa',preferred:'select',fallback:'any'});trip('kyoto');act({type:'visit',id:'kyoto-tea'});act({type:'visit',id:'kyoto-technique'});reject({type:'visit',id:'kyoto-tea'});act({type:'buy',ingredient:'tea',supplier:'dock',qty:5});trip('sf');act({type:'buy',ingredient:'cocoa',supplier:'dock',qty:5});act({type:'buy',ingredient:'sugar',supplier:'dock',qty:5});act({type:'buy',ingredient:'milk',supplier:'dock',qty:5});const teaBefore=structuredClone(s);act({type:'pilot',recipe:'tea',variant:'balanced'});const tea=E.RECIPES.find(r=>r.id==='tea');for(const [i,q] of Object.entries(E.variantIngredients(s,tea)))assert.ok(Math.abs(teaBefore.stock[i].qty-s.stock[i].qty-q*8)<.011);assert.equal(teaBefore.cash-s.cash,220);assert.equal(s.travel.variants.tea,'balanced');reject({type:'pilot',recipe:'tea',variant:'intense'});act({type:'plan',recipe:'tea',qty:5});supplies();close();assert.equal(s.reports[0].rows.find(r=>r.recipe==='tea').made,5);
act({type:'factory',id:'riverside'});close();close();const visited=[...s.travel.visited];s.travel.visited=s.travel.visited.filter(x=>x!=='turin');reject({type:'factory',id:'northline'});s.travel.visited=visited;act({type:'factory',id:'northline'});assert.equal(s.growth.factories.find(f=>f.id==='northline').ready,s.week+2);reject({type:'factory',id:'northline'});
console.log(JSON.stringify({pass:true,checks:'Full real-action itinerary, immediate and in-transit save round trips, repeat rejection, buffs, remote ordering, precise 8-case pilot consumption, actual Paris delivery and tea production',events,parisReward:reward,week:s.week,cash:s.cash,visited:s.travel.visited,learned:s.travel.learned,variants:s.travel.variants},null,2));

});test('locked tea automation rejects atomically and forecast includes next standing deposit',()=>{let s=E.deserialize(fs.readFileSync('docs/qa/revision/legacy-v2-week17.json','utf8'));const apply=a=>{const r=E.act(s,a);assert.ok(r.ok,r.message);s=r.state};s.week=20;let before=E.serialize(s);assert.equal(E.act(s,{type:'purchase-rule',ingredient:'tea',enabled:true,supplier:'dock',target:20}).ok,false);assert.equal(E.serialize(s),before);apply({type:'buyer',id:'cafes',enabled:true,recipe:'milk',terms:'standard'});s.growth.buyers.cafes.next=21;apply({type:'plan',recipe:'milk',qty:50});for(const i of E.INGREDIENTS){const n=Math.ceil(E.needed(s)[i]-s.stock[i].qty);if(n>0)apply({type:'buy',ingredient:i,supplier:'dock',qty:n})}const f=E.forecast(s);assert.ok(f.nextPurchases.deposits>0);apply({type:'advance'});assert.ok(Math.abs((s.cash-f.nextCash)-(s.reports[0].retail-f.sales))<.011);assert.equal(s.contracts.filter(c=>c.buyerId==='cafes').length,2)});

test('chapter continuation resumes purchasing and standing orders exactly once',()=>{
 for(const awarded of [false,true]){
  let s=E.deserialize(fs.readFileSync('docs/qa/revision/legacy-v2-week17.json','utf8'));s.week=awarded?37:17;s.status='won';s.growth.awarded=awarded;s.growth.purchasing.cocoa={enabled:true,supplier:'dock',target:200};s.growth.reserve=500;
  if(awarded)s.growth.buyers.cafes={enabled:true,recipe:'milk',terms:'standard',next:37,trust:74,delivered:2,missed:0};
  const before=E.serialize(s),r=E.act(s,{type:'continue'});assert.ok(r.ok);assert.equal(E.serialize(s),before);assert.equal(r.state.status,'playing');assert.equal(r.state.growth.chapter,awarded?'endless':'growth');assert.ok(r.state.stock.cocoa.qty>=200);assert.ok(r.state.book.purchases>0);if(awarded)assert.equal(r.state.contracts.filter(c=>c.id==='standing-cafes-37').length,1);const again=E.act(r.state,{type:'continue'});assert.equal(again.ok,false);assert.equal(again.state,r.state);assert.deepEqual(E.deserialize(E.serialize(r.state)),r.state);
 }
});
