import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../game/engine.ts';
const act=(s,a)=>{const r=E.act(s,a);assert.equal(r.ok,true,r.message);return r.state};
function stock(s,ingredient,qty){s.ingredientLots=s.ingredientLots.filter(l=>l.ingredient!==ingredient);s.stock[ingredient]={...s.stock[ingredient],qty};if(qty)s.ingredientLots.push({id:'fixture-'+ingredient,ingredient,grade:E.gradeFor(s.stock[ingredient].quality),...s.stock[ingredient]});}

test('partial whole batches conserve ingredients and wages, preserve targets and advance travel',()=>{
 let s=E.newGame();s.v3.chapter=2;s.plan.dark=5;s.plan.milk=0;stock(s,'cocoa',1.25);const before=E.serialize(s),a=E.actualProduction(s);assert.equal(a.plan.dark,1);assert.equal(E.serialize(s),before);s=act(s,{type:'travel',to:'paris'});s=act(s,{type:'advance'});assert.equal(s.travel.location,'paris');assert.equal(s.week,2);assert.equal(s.plan.dark,5);assert.equal(s.reports[0].rows[0].planned,5);assert.equal(s.reports[0].rows[0].made,1);assert.equal(s.reports[0].labor,2.8);assert.ok(Math.abs(s.ingredientLots.filter(l=>l.ingredient==='cocoa').reduce((n,l)=>n+l.qty,0)-.45)<1e-8);assert.match(s.reports[0].notes.join(' '),/made 1 of 5/);assert.deepEqual(E.deserialize(E.serialize(s)),s);
});
test('an impossible priority batch releases other ingredients; strict grades never create free product',()=>{
 let s=E.newGame();s.plan.dark=10;s.plan.milk=10;s.productionPriority=['milk',...s.productionPriority.filter(id=>id!=='milk')];stock(s,'milk',0);stock(s,'cocoa',8);assert.equal(E.actualProduction(s).plan.dark,10);assert.equal(E.actualProduction(s).plan.milk,0);s.ingredientPolicy.dark.cocoa={preferred:'premium',fallback:'none'};const f=E.forecast(s);s=act(s,{type:'advance'});assert.equal(s.reports[0].produced,0);assert.equal(s.reports[0].labor,0);assert.equal(s.stock.cocoa.qty,8);assert.equal(s.reports[0].overhead,230);assert.equal(s.cash,f.closing);assert.equal(s.plan.dark,10);
});
test('shared stock follows saved priority across factories without overspending any lot',()=>{
 const s=E.newGame();s.plan.dark=10;s.plan.milk=10;s.productionPriority=['milk',...s.productionPriority.filter(id=>id!=='milk')];s.growth.factories.push({id:'riverside',ready:1,workers:1,pay:'standard',qualityLead:false,expanded:false,paused:false});s.growth.assignment.milk='riverside';stock(s,'cocoa',8);stock(s,'milk',1.5);const actual=E.actualProduction(s);assert.equal(actual.plan.milk,5);assert.equal(actual.plan.dark,6);const next=act(s,{type:'advance'});assert.equal(next.reports[0].produced,11);for(const l of next.ingredientLots)assert.ok(l.qty>0);for(const i of E.INGREDIENTS){const used=Object.values(actual.products).flatMap(p=>p.usage).filter(l=>l.ingredient===i).reduce((n,l)=>n+l.qty,0),remaining=next.ingredientLots.filter(l=>l.ingredient===i).reduce((n,l)=>n+l.qty,0);assert.ok(Math.abs(s.ingredientLots.filter(l=>l.ingredient===i).reduce((n,l)=>n+l.qty,0)-used-remaining)<1e-8);}
});
test('manual sources are city-specific while existing replenishment and shipments continue abroad',()=>{
 let s=E.newGame();s.v3.chapter=2;s=act(s,{type:'purchase-rule',ingredient:'cocoa',enabled:true,supplier:'dock',target:120});s=act(s,{type:'buy',supplier:'coop',ingredient:'cocoa',qty:10});const arrival=s.orders[0].arrival;s=act(s,{type:'travel',to:'paris'});assert.equal(E.manualSources(s).length,0);s=act(s,{type:'advance'});assert.equal(E.manualSources(s).length,0);assert.equal(E.act(s,{type:'buy',supplier:'dock',ingredient:'milk',qty:1}).ok,false);assert.ok(s.stock.cocoa.qty>=120);assert.equal(s.orders[0].arrival,arrival);assert.equal(s.growth.purchasing.cocoa.enabled,true);
 s.travel.location='guayaquil';assert.deepEqual([...new Set(E.manualSources(s).map(x=>x.ingredient))],['cocoa']);s.travel.location='turin';assert.equal(E.manualSources(s).length,0);s.travel.learned.push('turin-sample');assert.equal(E.manualSources(s)[0].ingredient,'nuts');s=act(s,{type:'buy',supplier:'dock',ingredient:'nuts',qty:2});assert.equal(s.orders.at(-1).arrival,s.week+1);s.travel.location='kyoto';assert.equal(E.manualSources(s).length,0);s.travel.learned.push('kyoto-tea');assert.equal(E.manualSources(s)[0].ingredient,'tea');assert.equal(E.manualLead(s,'dock'),2);s.travel.location='sf';assert.ok(E.canSourceManually(s,'dock','milk'));assert.ok(E.canSourceManually(s,'estate','cocoa'));
});
