import test from 'node:test';
import assert from 'node:assert/strict';
const perfect={temperature:.5,agitation:.55,cooling:.7};
test('timed process integrates elapsed active time rather than render frames',async()=>{const {scoreTimedTrial}=await import('../game/v4/activity.ts');const sparse=[{at:0,...perfect},{at:60,...perfect}],dense=Array.from({length:601},(_,i)=>({at:i/10,...perfect}));const handoffs=[{station:'tempering',at:20},{station:'cooling',at:40},{station:'packing',at:55}];assert.deepEqual(scoreTimedTrial(sparse,handoffs),scoreTimedTrial(dense,handoffs));assert.deepEqual(scoreTimedTrial(sparse,handoffs).controls,[1,1,1])});
test('assisted settings and correct handoff order attain the identical timed ceiling',async()=>{const {scoreAssistedTrial,scoreTimedTrial}=await import('../game/v4/activity.ts');assert.deepEqual(scoreAssistedTrial(perfect,['tempering','cooling','packing']).controls,scoreTimedTrial([{at:0,...perfect},{at:60,...perfect}],[{station:'tempering',at:20},{station:'cooling',at:40},{station:'packing',at:55}]).controls);assert.ok(scoreAssistedTrial(perfect,['packing','cooling','tempering']).controls.every(v=>v<1))});
test('paused time is excluded and extended windows broaden timing tolerance without changing the ceiling',async()=>{const {activeTrialSeconds,scoreTimedTrial}=await import('../game/v4/activity.ts');assert.equal(activeTrialSeconds(0,90000,[{start:20000,end:50000}]),60);const samples=[{at:0,...perfect},{at:60,...perfect}],late=[{station:'tempering',at:26},{station:'cooling',at:46},{station:'packing',at:60}];assert.ok(scoreTimedTrial(samples,late,true).controls[0]>scoreTimedTrial(samples,late,false).controls[0]);assert.throws(()=>scoreTimedTrial([{at:0,...perfect},{at:10,...perfect}],late),/complete/i)});

test('paid commissioning derives its profile from timed evidence and assisted settings with the same ceiling',async()=>{
 const {newV4}=await import('../game/v4/saves.ts'),{applyCommand}=await import('../game/v4/commands.ts');
 const act=(s,c)=>{const r=applyCommand(s,c);assert.equal(r.ok,true,r.error);return r.state};
 let base=newV4({founder:'Bilal',business:'Trial House',emblem:'cocoa',primary:'#184f45',accent:'#cd925a'});base=act(base,{id:'line',type:'select-equipment',package:'balanced'});base=act(base,{id:'hire',type:'hire',employeeId:'sam',factoryId:'sf-workshop'});
 const settings={temperature:.5,agitation:.55,cooling:.7},common={type:'process-trial',factoryId:'sf-workshop',recipeRevisionId:'embar62:r1',settings};
 const assisted=act(base,{id:'assisted',...common,mode:'assisted',handoffs:['tempering','cooling','packing']});
 const timed=act(base,{id:'timed',...common,mode:'timed',samples:[{at:0,...settings},{at:60,...settings}],handoffs:[{at:20,station:'tempering'},{at:40,station:'cooling'},{at:55,station:'packing'}]});
 assert.equal(assisted.cashCents,timed.cashCents);for(const key of ['cycleMinutes','expectedYield','consistency','requiredCompetency'])assert.equal(timed.processProfiles[0][key],assisted.processProfiles[0][key]);
 const tooShort=applyCommand(base,{id:'short',...common,mode:'timed',samples:[{at:0,...settings},{at:59,...settings}],handoffs:[]});assert.equal(tooShort.ok,false);assert.deepEqual(tooShort.state,base);
 const practice=act(base,{id:'practice',...common,mode:'assisted',handoffs:['tempering','cooling','packing'],practice:true});assert.deepEqual(practice,base);
});

test('imported assisted and timed process numbers must match their paid source, including retained best results',async()=>{
 const {newV4,deserializeV4}=await import('../game/v4/saves.ts'),{applyCommand}=await import('../game/v4/commands.ts');const act=(s,c)=>{const r=applyCommand(s,c);assert.equal(r.ok,true,r.error);return r.state};
 let s=newV4({founder:'B',business:'Source House',emblem:'cocoa',primary:'#184f45',accent:'#cd925a'});s=act(s,{id:'line',type:'select-equipment',package:'balanced'});s=act(s,{id:'hire',type:'hire',employeeId:'sam',factoryId:'sf-workshop'});
 const settings={temperature:0,agitation:0,cooling:0};for(const mode of ['assisted','timed']){const command={id:'trial:'+mode,type:'process-trial',factoryId:'sf-workshop',recipeRevisionId:'embar62:r1',mode,settings,handoffs:mode==='assisted'?['packing','cooling','tempering']:[],...(mode==='timed'?{samples:[{at:0,...settings},{at:60,...settings}]}:{})};const paid=act(s,command),forged=structuredClone(paid);Object.assign(forged.processProfiles[0],{cycleMinutes:1,expectedYield:1,consistency:100,requiredCompetency:0});assert.equal(deserializeV4(JSON.stringify(forged)).ok,false);assert.equal(deserializeV4(JSON.stringify(paid)).ok,true);const worse=act(paid,{id:'worse:'+mode,type:'commission',factoryId:'sf-workshop',recipeRevisionId:'embar62:r1',mode:'assisted',controls:[0,0,0]});assert.equal(deserializeV4(JSON.stringify(worse)).ok,true)}
});

test('paid process expenses cannot be moved into another region or selling channel on import',async()=>{
 const {newV4,deserializeV4}=await import('../game/v4/saves.ts'),{applyCommand}=await import('../game/v4/commands.ts');let s=newV4({founder:'B',business:'Scope House',emblem:'cocoa',primary:'#184f45',accent:'#cd925a'});for(const c of [{id:'line',type:'select-equipment',package:'balanced'},{id:'hire',type:'hire',employeeId:'sam',factoryId:'sf-workshop'},{id:'trial',type:'commission',factoryId:'sf-workshop',recipeRevisionId:'embar62:r1',mode:'assisted',controls:[1,1,1]}]){const r=applyCommand(s,c);assert.equal(r.ok,true,r.error);s=r.state}for(const scope of [{factoryId:'sf-workshop',regionId:'europe'},{factoryId:'sf-workshop',regionId:'north-america',channelId:'sf-market'}]){const bad=structuredClone(s);bad.ledger.find(e=>e.eventId==='trial').scope=scope;assert.equal(deserializeV4(JSON.stringify(bad)).ok,false)}});
