import test from 'node:test';import assert from 'node:assert/strict';
import {preparedHouse,action} from './helpers/v4-house.mjs';
import {applyCommand} from '../game/v4/commands.ts';
import {deserializeV4,serializeV4} from '../game/v4/saves.ts';
import {scheduleProduction} from '../game/v4/production.ts';
function capital(){const s=preparedHouse(),amount=2000000;s.campaign.stage=3;s.cashCents+=amount;s.events.push({id:'scenario-capital',origin:'action',week:1,type:'equity',signature:'fixture',entityIds:['house'],details:{}});s.ledger.push({id:'scenario-capital',eventId:'scenario-capital',week:1,description:'Equipment scenario capital',postings:[{account:'cash',debitCents:amount,creditCents:0},{account:'equity',debitCents:0,creditCents:amount}]});return s}
const plan={factoryId:'sf-workshop',items:[{recipeRevisionId:'embar62:r1',cases:20}]};
test('paid module upgrades preserve unrelated process certification and consume utility budgets',()=>{const s=capital(),before=scheduleProduction({state:s,factoryId:'sf-workshop'},plan),packing=action(s,{id:'packing-upgrade',type:'upgrade-module',factoryId:'sf-workshop',station:'packing'});assert.equal(s.cashCents-packing.cashCents,90000);assert.equal(packing.factories[0].stations.packing.tier,2);assert.ok(packing.factories[0].stations.packing.minutes>s.factories[0].stations.packing.minutes);assert.equal(scheduleProduction({state:packing,factoryId:'sf-workshop'},plan).rows[0].goodCases,before.rows[0].goodCases);assert.deepEqual(packing.processProfiles,s.processProfiles);assert.equal(deserializeV4(serializeV4(packing)).ok,true);
 const cooling=applyCommand(s,{id:'cooling-blocked',type:'upgrade-module',factoryId:'sf-workshop',station:'cooling'});assert.equal(cooling.ok,false);assert.match(cooling.error,/cooling connection/);assert.deepEqual(cooling.state,s);
 const utilities=action(s,{id:'utilities',type:'upgrade-utilities',factoryId:'sf-workshop'}),upgraded=action(utilities,{id:'cooling-upgrade',type:'upgrade-module',factoryId:'sf-workshop',station:'cooling'});assert.equal(upgraded.factories[0].layout.coolingCapacity,16);const missing=scheduleProduction({state:upgraded,factoryId:'sf-workshop'},plan);assert.equal(missing.rows[0].goodCases,0);assert.match(missing.constraints.join(' '),/certified process/);assert.deepEqual(upgraded.processProfiles,s.processProfiles);const certified=action(upgraded,{id:'new-trial',type:'commission',factoryId:'sf-workshop',recipeRevisionId:'embar62:r1',mode:'assisted',controls:[1,1,1]});assert.ok(scheduleProduction({state:certified,factoryId:'sf-workshop'},plan).rows[0].goodCases>0);assert.equal(deserializeV4(serializeV4(certified)).ok,true)});
test('unpaid equipment capacity, utility upgrades and tier jumps cannot be imported or committed',()=>{const s=capital(),bad=structuredClone(s);bad.factories[0].stations.cooling.minutes+=10000;assert.equal(deserializeV4(JSON.stringify(bad)).ok,false);const early=preparedHouse();assert.equal(applyCommand(early,{id:'too-early',type:'upgrade-module',factoryId:'sf-workshop',station:'packing'}).ok,false);const money=serializeV4(s);const invalid=applyCommand(s,{id:'outside',type:'upgrade-module',factoryId:'sf-workshop',station:'unknown'});assert.equal(invalid.ok,false);assert.equal(serializeV4(invalid.state),money)});

test('paid starter package cannot be rewritten as a larger line',()=>{const s=capital();s.factories[0].packageId='automated';for(const [id,station] of Object.entries(s.factories[0].stations))station.minutes=Math.round(Math.round(1400*(id==='cooling'?.65:id==='packing'?.8:1)));assert.equal(deserializeV4(JSON.stringify(s)).ok,false)});

test('removing initial purchase entity or event cannot disable equipment evidence checks',()=>{for(const mode of ['entities','event']){const s=capital();s.factories[0].packageId='automated';for(const [id,station] of Object.entries(s.factories[0].stations))station.minutes=Math.round(1400*(id==='cooling'?.65:id==='packing'?.8:1));if(mode==='entities')s.events.find(e=>e.type==='select-equipment').entityIds=[];else s.events=s.events.filter(e=>e.type!=='select-equipment');assert.equal(deserializeV4(JSON.stringify(s)).ok,false)}});
