// Local physical cohort, earned-service and native authority regressions.
import test from 'node:test';
import assert from 'node:assert/strict';
import {preparedHouse,action} from './helpers/v4-house.mjs';
import {post,debit,credit,checkLedger,accountBalance} from '../game/v4/finance.ts';
import {resolveWeek} from '../game/v4/tick.ts';
import {applyCommand} from '../game/v4/commands.ts';
import {deserializeV4,serializeV4} from '../game/v4/saves.ts';
function close(s,id){const r=resolveWeek(s,{tickId:id,expectedWeek:s.week});assert.equal(r.ok,true,r.error);return r.state;}
function house(){let s=preparedHouse();s.campaign.stage=5;const e={id:'cohort-test-capital',origin:'action',type:'fixture',week:s.week,signature:'{}',entityIds:[],details:{}};s.events.push(e);post(s,e,'Explicit integration capital',[debit('cash',6000000),credit('equity',6000000)]);s=action(s,{id:'cohort-lead',type:'hire',employeeId:'imani',factoryId:'sf-workshop'});s=action(s,{id:'cohort-standard',type:'write-franchise-standard',leaderId:'imani',assortment:['embar62:r1','velvet-milk:r1'],minimumQuality:65,royaltyBps:700,supply:'local',weeklySupportCents:4500,openingFeeCents:200000,feeEarningWeeks:26,trainingWeeks:2,brief:'Maintain the released recipes and train local operators before each opening.'});s=action(s,{id:'cohort-hub',type:'franchise-support',cityId:'sf',leaderId:'imani',weeklyBudgetCents:450000});s=close(s,'hub-install-1');return close(s,'hub-install-2');}
const proposal={type:'open-franchise-cohort',partnerId:'bay-neighborhood',standardId:'standard:cohort-standard',hubId:'support:cohort-hub',stores:2,priceFactorBps:10000};
test('partner opening advances are deferred obligations, never instant profit or group partner turnover',()=>{let s=house(),before=s.cashCents,revenue=accountBalance(s,'royalty-revenue');s=action(s,{id:'cohort-open',...proposal});assert.equal(s.cashCents,before+400000);assert.equal(accountBalance(s,'royalty-revenue'),revenue);assert.equal(-accountBalance(s,'customer-deposits'),400000+s.contracts.filter(c=>c.status==='accepted').reduce((n,c)=>n+c.depositCents-Math.floor(c.depositCents*c.fulfilledCases/c.cases),0));assert.equal(s.franchiseCohorts[0].partnerCashCents,2*3000000-400000-2*1400000);assert.deepEqual(checkLedger(s),[]);});
test('opening intake stops when paid named support capacity is exhausted and rejects reuse of a partner',()=>{let s=house();s=action(s,{id:'full-cohort',...proposal,stores:8});assert.equal(applyCommand(s,{id:'duplicate-partner',...proposal}).ok,false);assert.equal(applyCommand(s,{id:'wrong-regional-hub',...proposal,partnerId:'paris-curators'}).ok,false);s.employees.find(e=>e.id==='imani').contractedMinutes=120;assert.equal(applyCommand(s,{id:'overloaded-intake',...proposal,partnerId:'oakland-cafe-group',stores:2}).ok,false);});
test('actual supported training and compliant trading earn only royalties and supported fee service installments',()=>{let s=action(house(),{id:'trading-cohort',...proposal});s=close(s,'partner-training-1');assert.equal(s.franchiseCohorts[0].trainingCompletedWeeks,1);s=close(s,'partner-training-2');s=close(s,'partner-trading-1');const row=s.franchiseHistory.at(-1).cohorts[0];assert.ok(row.partnerRevenueCents>0);assert.equal(row.royaltyCents,Math.floor(row.partnerRevenueCents*700/10000));assert.equal(row.feeEarnedCents,Math.floor(400000/26));assert.ok(row.partnerRevenueCents>row.royaltyCents+row.feeEarnedCents);assert.deepEqual(checkLedger(s),[]);assert.equal(deserializeV4(serializeV4(s)).ok,true);});
test('support failure stops trading and fee earning; restored actual support can recover the same cohort',()=>{let s=action(house(),{id:'support-test-oakland-visit',type:'travel',cityId:'oakland'});s=action(s,{id:'first-supported-cohort',...proposal,stores:8});s=action(s,{id:'recoverable-cohort',...proposal,partnerId:'oakland-cafe-group',stores:8});for(let i=0;i<3;i++)s=close(s,'recover-trained:'+i);s=action(s,{id:'cut-support-hours',type:'employment-terms',employeeId:'imani',factoryId:'sf-workshop',minutes:600});s=close(s,'unsupported-close');let row=s.franchiseHistory.at(-1).cohorts[1];assert.equal(row.supportedStores,0);assert.equal(row.partnerRevenueCents,0);assert.equal(row.feeEarnedCents,0);assert.ok(row.exception);s=action(s,{id:'restore-support-hours',type:'employment-terms',employeeId:'imani',factoryId:'sf-workshop',minutes:2400});s=close(s,'restored-close');row=s.franchiseHistory.at(-1).cohorts[1];assert.equal(row.supportedStores,8);assert.equal(row.supportCents,36000);assert.doesNotMatch(row.exception,/support coverage/);assert.ok(s.ledger.some(j=>j.id==='restored-close:cohort:recoverable-cohort:field-support'&&j.postings.some(p=>p.account==='support'&&p.debitCents===36000)));});
test('native authority rejects forged partner capital, fees, weekly royalties and deleted cohort history',()=>{let s=action(house(),{id:'audited-cohort',...proposal});for(let i=0;i<3;i++)s=close(s,'audit-partner:'+i);assert.equal(deserializeV4(serializeV4(s)).ok,true);for(const mutate of [s=>s.franchiseCohorts[0].partnerCashCents+=1000000,s=>s.franchiseCohorts[0].feeRemainingCents=0,s=>s.franchiseHistory.at(-1).cohorts[0].royaltyCents+=100000,s=>s.franchiseHistory=[]]){const changed=structuredClone(s);mutate(changed);assert.equal(deserializeV4(JSON.stringify(changed)).ok,false);}});
test('partner group-income authority is determined by accounts and entities, never a journal suffix',async()=>{const {franchiseCohortEvidenceErrors}=await import('../game/v4/franchise-validation.ts');let s=action(house(),{id:'suffix-audited-cohort',...proposal});for(let i=0;i<3;i++)s=close(s,'suffix-audit:'+i);const tick=s.events.at(-1),cohort=s.franchiseCohorts[0];post(s,tick,'Invented bonus',[debit('cash',100000),credit('royalty-revenue',100000,cohort.id)],'bonus',{regionId:'north-america',channelId:'franchise-royalties'});assert.ok(franchiseCohortEvidenceErrors(s).length>0);});
test('royalty claims without any opening cohort cannot establish group income',async()=>{const {franchiseCohortEvidenceErrors}=await import('../game/v4/franchise-validation.ts');let s=house();const tick=s.events.at(-1);post(s,tick,'Invented franchise income',[debit('cash',100000),credit('royalty-revenue',100000)],'unrelated-suffix');assert.ok(franchiseCohortEvidenceErrors(s).length>0);});
test('native replay rejects jointly forged private sales, stock and group royalties',async()=>{const {franchiseCohortEvidenceErrors}=await import('../game/v4/franchise-validation.ts');let s=action(house(),{id:'physical-audited-cohort',...proposal});for(let i=0;i<3;i++)s=close(s,'physical-audit:'+i);for(const mutate of [row=>row.partnerRevenueCents+=100000,row=>row.closingStock[0].quantity+=10000,row=>row.recipes[0].inputCases+=20,row=>row.supportCents=0]){const changed=structuredClone(s),h=changed.franchiseHistory.at(-1),tick=changed.events.find(e=>e.id===h.tickId);mutate(h.cohorts[0]);tick.details.franchiseActuals=JSON.stringify(h);assert.ok(franchiseCohortEvidenceErrors(changed).length>0);}});
test('rewritten intake cannot move an operator to an unvisited city',async()=>{const{initialFranchiseCohort}=await import('../game/v4/franchise-cohorts.ts');const{franchisePartners}=await import('../game/v4/content/franchise-partners.ts');let s=action(house(),{id:'dated-intake',...proposal}),e=s.events.at(-1),p=JSON.parse(e.signature);p.partnerId='oakland-cafe-group';e.signature=JSON.stringify(p);const partner=franchisePartners.find(q=>q.id===p.partnerId),c=initialFranchiseCohort(p,s.franchiseStandards[0],e.id,e.week);s.franchiseCohorts=[c];e.entityIds=[c.id,p.partnerId,p.standardId,p.hubId];e.details={cohort:JSON.stringify(c),partnerCapitalCents:partner.capitalPerStoreCents*p.stores,partnerFitoutCents:partner.fitoutPerStoreCents*p.stores};assert.equal(deserializeV4(JSON.stringify(s)).ok,false);});
test('an unsigned missing paid support close is rejected even with matching private cards and journal totals',async()=>{const{operatePartner}=await import('../game/v4/partner-week.ts');const{franchisePartners}=await import('../game/v4/content/franchise-partners.ts');const{franchiseCohortEvidenceErrors}=await import('../game/v4/franchise-validation.ts');const before=action(house(),{id:'funded-support',...proposal}),s=close(before,'funded-training'),e=s.events.at(-1),c=before.franchiseCohorts[0],standard=s.franchiseStandards[0],partner=franchisePartners.find(p=>p.id===c.partnerId),result=operatePartner(c,standard,partner,{cityId:partner.cityId,week:e.week,stage:5,grade:c.grade,allowedSupplierIds:s.knownSuppliers,used:new Map(),seed:s.random.seed,tickId:e.id,revisions:s.recipeRevisions,supportedStores:0,supportCents:0});s.franchiseCohorts=[result.cohort];s.franchiseHistory.at(-1).cohorts=[result.row];e.details.franchiseActuals=JSON.stringify(s.franchiseHistory.at(-1));s.ledger=s.ledger.filter(j=>j.id!==e.id+':'+c.id+':field-support');s.cashCents+=9000;assert.ok(franchiseCohortEvidenceErrors(s).length>0);});
test('a partner quality failure damages its own regional consideration more than distant markets, with dated recovery',async()=>{const{franchiseBrandFactor}=await import('../game/v4/franchise-brand.ts');const s=house();s.week=10;s.franchiseCohorts=[{id:'cohort:brand-history',stores:4,openedWeek:3}];s.franchiseHistory=Array.from({length:6},(_,i)=>({week:i+3,cohorts:[{cohortId:'cohort:brand-history',cityId:'sf',compliant:false}]}));assert.ok(franchiseBrandFactor(s,'sf')<franchiseBrandFactor(s,'paris'));assert.ok(franchiseBrandFactor(s,'paris')<1);const bad=franchiseBrandFactor(s,'sf');s.franchiseHistory.push({week:10,cohorts:[{cohortId:'cohort:brand-history',cityId:'sf',compliant:true}]});assert.equal(franchiseBrandFactor(s,'sf'),bad,'Current-week information cannot rewrite earlier consideration');s.week=19;s.franchiseHistory=Array.from({length:8},(_,i)=>({week:i+11,cohorts:[{cohortId:'cohort:brand-history',cityId:'sf',compliant:true}]}));assert.ok(franchiseBrandFactor(s,'sf')>1);s.franchiseCohorts[0].openedWeek=20;assert.equal(franchiseBrandFactor(s,'sf'),1,'Pre-opening training does not invent customer reputation');});
test('a demanding local standard stops unsupported quality promises and recovers through paid training and actual premium lots',()=>{let s=action(house(),{id:'quality-standard',type:'write-franchise-standard',leaderId:'imani',assortment:['embar62:r1','velvet-milk:r1'],minimumQuality:73,royaltyBps:700,supply:'local',weeklySupportCents:4500,openingFeeCents:200000,feeEarningWeeks:26,trainingWeeks:2,brief:'Train this cooperative for a demanding core standard; hold sales until actual paid lots support quality.'});s=action(s,{id:'quality-oak-visit',type:'travel',cityId:'oakland'});s=action(s,{id:'quality-cooperative',...proposal,partnerId:'oakland-cafe-group',standardId:'standard:quality-standard'});for(let i=0;i<3;i++)s=close(s,'quality-held:'+i);assert.equal(s.franchiseHistory.at(-1).cohorts[0].partnerRevenueCents,0);assert.equal(s.franchiseCohorts[0].serviceWeeks,0);assert.equal(s.franchiseCohorts[0].feeRemainingCents,400000);s=action(s,{id:'quality-recovery-policy',type:'franchise-cohort-policy',cohortId:s.franchiseCohorts[0].id,paused:false,priceFactorBps:10000,extraTrainingWeeks:6,grade:'premium'});for(let i=0;i<7;i++)s=close(s,'quality-recovery:'+i);const row=s.franchiseHistory.at(-1).cohorts[0];assert.ok(row.partnerRevenueCents>0);assert.ok(row.recipes.every(r=>r.quality>=73));assert.ok(row.supportCents>0);assert.ok(s.franchiseHistory.some(w=>w.cohorts[0].purchases.some(p=>p.stock.kind==='ingredient'&&p.stock.quality===76)));assert.equal(deserializeV4(serializeV4(s)).ok,true);});
test('deleting consideration authority cannot select obsolete rules for a newly issued partner close',async()=>{const{franchiseBrandFactor}=await import('../game/v4/franchise-brand.ts');let s=action(house(),{id:'consideration-authority',...proposal});for(let i=0;i<3;i++)s=close(s,'consideration-prior:'+i);assert.ok(franchiseBrandFactor(s,'sf')>1);const shadow=structuredClone(s);shadow.franchiseHistory=[];const oldRules=close(shadow,'consideration-old-rules');oldRules.franchiseHistory=[...s.franchiseHistory,...oldRules.franchiseHistory];delete oldRules.events.at(-1).details.franchiseBrandModel;assert.equal(deserializeV4(JSON.stringify(oldRules)).ok,false);const normal=close(s,'consideration-current-rules');assert.equal(deserializeV4(serializeV4(normal)).ok,true);});
test('a few private sales cannot certify every district or earn whole-cohort service under a supply shortage',async()=>{
 const {operatePartner}=await import('../game/v4/partner-week.ts'),{franchisePartners}=await import('../game/v4/content/franchise-partners.ts');
 let s=action(house(),{id:'scarce-districts',...proposal,stores:8});for(let i=0;i<2;i++)s=close(s,'scarce-training:'+i);
 const c=structuredClone(s.franchiseCohorts[0]);c.stock=[];c.partnerCashCents=1000000;const revision=s.recipeRevisions.find(r=>r.id==='embar62:r1');const {catalog}=await import('../game/v4/catalog.ts');const recipe=catalog.recipes.find(r=>r.id===revision.recipeId);
 for(const [i,role]of recipe.roles.entries())c.stock.push({id:'scarce-raw:'+i,kind:'ingredient',varietyId:revision.formula[role.role],quantity:role.gramsPerCase*3,costCents:300,quality:90,arrivalWeek:s.week,expiryWeek:s.week+10,supplierId:'rafi'});
 c.stock.push({id:'scarce-packs',kind:'packaging',packagingId:'ordinary-wrap',quantity:60,costCents:180,quality:68,arrivalWeek:s.week,expiryWeek:s.week+10,supplierId:'rafi'});
 const result=operatePartner(c,s.franchiseStandards[0],franchisePartners.find(p=>p.id===c.partnerId),{cityId:'sf',week:s.week,stage:5,grade:c.grade,allowedSupplierIds:[],used:new Map(),seed:s.random.seed,tickId:'scarce-week',revisions:s.recipeRevisions,supportedStores:8,supportCents:36000,serviceModel:2});
 assert.ok(result.row.partnerRevenueCents>0);assert.equal(result.row.compliant,false);assert.equal(result.row.feeEarnedCents,0);assert.ok(result.row.unservedCases>0);assert.equal(result.row.stores.filter(r=>r.status==='operating').length,0);assert.match(result.row.exception,/service|demand/);
});
test('new partner procurement can split a real large reorder across discovered sources while historical one-offer rules stay replayable',async()=>{const{operatePartner}=await import('../game/v4/partner-week.ts'),{franchisePartners}=await import('../game/v4/content/franchise-partners.ts'),{catalog}=await import('../game/v4/catalog.ts');let s=house();for(const supplierId of ['bay-import','oakland-wholesale']){if(catalog.suppliers.some(p=>p.id===supplierId))s=action(s,{id:'split-discover:'+supplierId,type:'discover-supplier',supplierId});}s=action(s,{id:'split-cohort',...proposal,stores:8});const c=s.franchiseCohorts[0],partner=franchisePartners.find(p=>p.id===c.partnerId),standard=s.franchiseStandards[0],context={cityId:partner.cityId,week:s.week,stage:5,grade:c.grade,allowedSupplierIds:s.knownSuppliers,used:new Map(),seed:s.random.seed,tickId:'split-test',revisions:s.recipeRevisions,supportedStores:8,supportCents:36000},old=operatePartner(c,standard,partner,{...context,used:new Map(),serviceModel:2}),newer=operatePartner(c,standard,partner,{...context,used:new Map(),serviceModel:3});const cocoa=r=>r.row.purchases.filter(p=>p.stock.varietyId==='cocoa-ecuador');assert.ok(cocoa(newer).length>1);assert.ok(cocoa(newer).reduce((n,p)=>n+p.stock.quantity,0)>cocoa(old).reduce((n,p)=>n+p.stock.quantity,0));assert.ok(newer.cohort.partnerCashCents<old.cohort.partnerCashCents,'additional physical stock is paid by the partner');for(let i=0;i<3;i++)s=close(s,'split-native:'+i);assert.equal(s.events.at(-1).details.franchiseServiceModel,4);assert.equal(deserializeV4(serializeV4(s)).ok,true);});
