import test from 'node:test';
import assert from 'node:assert/strict';
import {newV4,serializeV4,deserializeV4} from '../game/v4/saves.ts';
import {applyCommand} from '../game/v4/commands.ts';
import {scheduleProduction} from '../game/v4/production.ts';
import {defaultLayout,handoffMinutesPerCase} from '../game/v4/layout.ts';
const act=(s,c)=>{const r=applyCommand(s,c);assert.equal(r.ok,true,r.error);return r.state};
function prepared(){let s=newV4({founder:'Bilal',business:'Floor house',emblem:'cocoa',primary:'#184f45',accent:'#cd925a'});s=act(s,{id:'line',type:'select-equipment',package:'balanced'});for(const employeeId of ['sam','mira'])s=act(s,{id:'hire:'+employeeId,type:'hire',employeeId,factoryId:'sf-workshop'});s=act(s,{id:'trial',type:'commission',factoryId:'sf-workshop',recipeRevisionId:'embar62:r1',mode:'assisted',controls:[1,1,1]});for(const [varietyId,quantityGrams]of [['cocoa-ecuador',70000],['sugar-refined',60000]])s=act(s,{id:'raw:'+varietyId,type:'purchase',request:{supplierId:'rafi',varietyId,quantityGrams,grade:'standard',warehouseId:'sf-storage'}});return act(s,{id:'packs',type:'purchase-packaging',request:{supplierId:'rafi',packagingId:'ordinary-wrap',quantityUnits:2000,warehouseId:'sf-storage'}})}
test('installed physical floor is saved; paid relocation changes actual handoff labor without invented machine minutes',()=>{const before=prepared(),f=before.factories[0];assert.deepEqual(f.layout,defaultLayout());const plan={factoryId:f.id,items:[{recipeRevisionId:'embar62:r1',cases:20}]},old=scheduleProduction({state:before,factoryId:f.id},plan);const after=act(before,{id:'move',type:'place-module',factoryId:f.id,station:'packing',x:0,y:4});assert.equal(before.cashCents-after.cashCents,5000);assert.ok(handoffMinutesPerCase(after.factories[0].layout)>handoffMinutesPerCase(f.layout));assert.deepEqual(after.factories[0].stations,f.stations);const next=scheduleProduction({state:after,factoryId:f.id},plan);assert.ok(next.rows[0].laborMinutes>old.rows[0].laborMinutes);assert.equal(next.rows[0].goodCases,old.rows[0].goodCases);assert.deepEqual(after.processProfiles,before.processProfiles);assert.equal(deserializeV4(serializeV4(after)).ok,true)});
test('blocked or unsafe physical floors reject atomically and corrupt imports are preserved',()=>{const before=prepared(),bytes=serializeV4(before);for(const request of [{station:'packing',x:4,y:4},{station:'cooling',x:7,y:3},{station:'processing',x:4,y:1,tier:4}]){const r=applyCommand(before,{id:'invalid:'+request.station,type:'place-module',factoryId:'sf-workshop',...request});assert.equal(r.ok,false);assert.equal(serializeV4(r.state),bytes)}const forged=structuredClone(before);forged.factories[0].layout.modules[0].x=9;assert.equal(deserializeV4(JSON.stringify(forged)).ok,false)});
test('a valid-looking unpaid floor cannot replace the purchased, persisted configuration',()=>{const s=prepared(),forged=structuredClone(s);forged.factories[0].layout.modules.find(m=>m.station==='packing').x=0;assert.equal(deserializeV4(JSON.stringify(forged)).ok,false);const moved=act(s,{id:'move-evidence',type:'place-module',factoryId:'sf-workshop',station:'packing',x:0,y:4});delete moved.factories[0].layout;assert.equal(deserializeV4(JSON.stringify(moved)).ok,false)});
