import test from 'node:test';
import assert from 'node:assert/strict';
import {preparedHouse,action} from './helpers/v4-house.mjs';
import {post,debit,credit,accountBalance} from '../game/v4/finance.ts';
import {franchiseStandard,configureFranchiseSupport,franchiseSupportCapacity} from '../game/v4/franchise.ts';
function house(){let s=preparedHouse();s.campaign.stage=5;const e={id:'explicit-franchise-test-capital',origin:'action',type:'fixture',week:s.week,signature:'{}',entityIds:[],details:{}};s.events.push(e);post(s,e,'Explicit integration capital',[debit('cash',3000000),credit('equity',3000000)]);s=action(s,{id:'franchise-commercial-hire',type:'hire',employeeId:'imani',factoryId:'sf-workshop'});s=action(s,{id:'franchise-commercial-hours',type:'employment-terms',employeeId:'imani',factoryId:'sf-workshop',minutes:1200});return s;}
const proposal={type:'write-franchise-standard',assortment:['embar62:r1','velvet-milk:r1'],minimumQuality:65,royaltyBps:700,supply:'local',weeklySupportCents:4500,openingFeeCents:200000,feeEarningWeeks:26,trainingWeeks:2,brief:'Protect a consistent core assortment while allowing local seasonal choices.'};
test('a franchise standard is paid, versioned, released and led by a capable named commercial person',()=>{let s=house();const before=s.cashCents;s=action(s,{id:'standard-one',...proposal,leaderId:'imani'});assert.equal(s.cashCents,before-180000);assert.equal(s.franchiseStandards.length,1);assert.equal(s.franchiseStandards[0].version,1);assert.equal(s.franchiseStandards[0].leaderId,'imani');assert.throws(()=>franchiseStandard(s,{...proposal,leaderId:'sam'},{id:'bad-standard',week:s.week,entityIds:[],details:{}}));assert.throws(()=>franchiseStandard(s,{...proposal,leaderId:'imani',assortment:['unknown']},{id:'bad-assortment',week:s.week,entityIds:[],details:{}}));});
test('support capacity requires a paid installed regional hub and contracted skill, with no double allocated leader',()=>{let s=house();s=action(s,{id:'support-standard',...proposal,leaderId:'imani'});s=action(s,{id:'support-funded',type:'franchise-support',cityId:'sf',leaderId:'imani',weeklyBudgetCents:45000});assert.equal(franchiseSupportCapacity(s,'sf'),0);s.week+=2;assert.equal(franchiseSupportCapacity(s,'sf'),20);assert.equal(accountBalance(s,'commissioning'),436000);assert.throws(()=>configureFranchiseSupport(s,{cityId:'sf',leaderId:'imani',weeklyBudgetCents:10000},{id:'duplicate-support',week:s.week,entityIds:[],details:{}}));s.employees.find(e=>e.id==='imani').contractedMinutes=600;assert.equal(franchiseSupportCapacity(s,'sf'),10);});
test('a standard revision preserves existing standards and cannot print income from a franchise fee',()=>{let s=house();s=action(s,{id:'standard-version-one',...proposal,leaderId:'imani'});const first=structuredClone(s.franchiseStandards[0]);s=action(s,{id:'standard-version-two',...proposal,leaderId:'imani',royaltyBps:800});assert.deepEqual(s.franchiseStandards[0],first);assert.equal(s.franchiseStandards[1].version,2);assert.equal(accountBalance(s,'royalty-revenue'),0);assert.equal(accountBalance(s,'customer-deposits'),0);});

test('native reload rejects rewritten franchise quality or unpaid standards while preserving dated terms',async()=>{const {serializeV4,deserializeV4}=await import('../game/v4/saves.ts');let s=house();s=action(s,{id:'native-standard',...proposal,leaderId:'imani'});s=action(s,{id:'native-support',type:'franchise-support',cityId:'sf',leaderId:'imani',weeklyBudgetCents:45000});assert.equal(deserializeV4(serializeV4(s)).ok,true);const corrupt=structuredClone(s);corrupt.franchiseStandards[0].minimumQuality=1;assert.equal(deserializeV4(JSON.stringify(corrupt)).ok,false);const refund=structuredClone(s),e=refund.events.find(e=>e.id==='native-standard');post(refund,e,'Invented manual refund',[debit('cash',180000),credit('commissioning',180000)],'refund');assert.equal(deserializeV4(JSON.stringify(refund)).ok,false);});
test('unresolved due-week training cannot create a standard that native import rejects',async()=>{const{applyCommand}=await import('../game/v4/commands.ts'),{resolveWeek}=await import('../game/v4/tick.ts');let s=house();s=action(s,{id:'standard-lead-training',type:'train',employeeId:'imani',skill:'quality'});for(let i=0;i<2;i++){const r=resolveWeek(s,{tickId:'standard-training-close:'+i,expectedWeek:s.week});assert.equal(r.ok,true,r.error);s=r.state;}assert.ok(s.training.some(t=>t.employeeId==='imani'));assert.equal(applyCommand(s,{id:'training-unresolved-standard',...proposal,leaderId:'imani'}).ok,false);});
test('a support office cannot rewrite its command identity or erase its prior operating standard',async()=>{const{deserializeV4}=await import('../game/v4/saves.ts');let s=house();s=action(s,{id:'hub-prior-standard',...proposal,leaderId:'imani'});s=action(s,{id:'hub-source',type:'franchise-support',cityId:'sf',leaderId:'imani',weeklyBudgetCents:45000});const rewritten=structuredClone(s),e=rewritten.events.find(e=>e.id==='hub-source');e.signature=JSON.stringify({...JSON.parse(e.signature),id:'unrelated',type:'purchase'});e.entityIds=[];assert.equal(deserializeV4(JSON.stringify(rewritten)).ok,false);const erased=structuredClone(s);erased.franchiseStandards=[];erased.events=erased.events.filter(e=>e.id!=='hub-prior-standard');erased.ledger=erased.ledger.filter(j=>j.eventId!=='hub-prior-standard');erased.cashCents+=180000;assert.equal(deserializeV4(JSON.stringify(erased)).ok,false);});
test('franchise support and factory delegation cannot allocate the same manager in either booking order',async()=>{const{applyCommand}=await import('../game/v4/commands.ts');let s=house();s=action(s,{id:'reverse-rosa-hire',type:'hire',employeeId:'rosa',factoryId:'sf-workshop'});s=action(s,{id:'reverse-standard',...proposal,leaderId:'imani'});s=action(s,{id:'reverse-rosa-hub',type:'franchise-support',cityId:'sf',leaderId:'rosa',weeklyBudgetCents:45000});const r=applyCommand(s,{id:'reverse-rosa-delegation',type:'delegation-policy',factoryId:'sf-workshop',managerId:'rosa',enabled:true,budgetCents:50000,items:[],packaging:[]});assert.equal(r.ok,false);});
