import test from 'node:test';import assert from 'node:assert/strict';
import {newV4,serializeV4,deserializeV4} from '../game/v4/saves.ts';
import {resolveWeek} from '../game/v4/tick.ts';
import {globalEvidenceErrors,datedEnterpriseValue,executives} from '../game/v4/global.ts';
import {preparedHouse,action} from './helpers/v4-house.mjs';
import {post,debit,credit} from '../game/v4/finance.ts';
import {applyCommand} from '../game/v4/commands.ts';
function quarterly(){let s=preparedHouse();s.campaign.stage=6;s.currentCityId='singapore';s.visitedCities.push('singapore');s=action(s,{id:'global-real-buyer-visit',type:'visit-location',cityId:'singapore',locationId:'regional-hub'});s=action(s,{id:'global-real-framework',type:'accept-offer',offerId:'global-everyday'});s.events.push({id:'declared-global-route-fixture',origin:'action',week:1,type:'review-chapter',signature:JSON.stringify({chapterId:'chapter:35'}),entityIds:[],details:{fixture:true}});for(let i=0;i<53;i++){const r=resolveWeek(s,{tickId:'quarter-proof:'+i,expectedWeek:s.week});assert.equal(r.ok,true,r.error);s=r.state;}return s;}
test('quarterly evidence recomputes all global conditions from its dated ledger, output, service and debt',()=>{const s=quarterly();assert.deepEqual(globalEvidenceErrors(s),[]);const event=s.events.find(e=>e.details.globalQuarter&&e.week>=52),q=JSON.parse(event.details.globalQuarter);assert.equal(q.windowWeeks,52);assert.equal(q.eligible,false);for(const field of ['eligible','quality','service','operatingFlowCents','downsideCoverage','profitCents','growth','factor','windowWeeks']){const f=structuredClone(s),e=f.events.find(e=>e.id===event.id),changed=JSON.parse(e.details.globalQuarter);changed[field]=typeof changed[field]==='boolean'?!changed[field]:999999;e.details.globalQuarter=JSON.stringify(changed);assert.ok(globalEvidenceErrors(f).length>0,field+' cannot be invented');}const missing=structuredClone(s);delete missing.events.find(e=>e.id===event.id).details.globalQuarter;assert.ok(globalEvidenceErrors(missing).length>0);const before=datedEnterpriseValue(s,event);s.loans.push({...s.loans[0],id:'declared-future-loan-fixture',status:'active',installmentCents:999999999});assert.deepEqual(datedEnterpriseValue(s,event),before,'later debt does not rewrite a closed review');});
test('departed or unavailable executives do not grant management gates and executive hours cannot be double allocated locally',()=>{let s=preparedHouse();s.campaign.stage=6;const e={id:'executive-capital-fixture',origin:'action',week:1,type:'fixture',signature:'{}',entityIds:[],details:{}};s.events.push(e);post(s,e,'Declared executive integration capital',[debit('cash',10000000),credit('equity',10000000)]);s=action(s,{id:'hire-executive',type:'hire',employeeId:'rosa',factoryId:'sf-workshop'});s=action(s,{id:'appoint-executive',type:'appoint-executive',employeeId:'rosa',role:'operations'});assert.equal(executives(s).length,1);assert.equal(deserializeV4(serializeV4(s)).ok,true);assert.equal(applyCommand(s,{id:'double-leadership',type:'delegation-policy',factoryId:'sf-workshop',managerId:'rosa',enabled:true,budgetCents:0,items:[],packaging:[]}).ok,false);assert.equal(applyCommand(s,{id:'double-team',type:'configure-team',workplaceId:'sf-workshop',leaderId:'rosa',role:'production',grade:'experienced',headcount:4,minutes:1200}).ok,false);const departed=action(s,{id:'executive-departure',type:'release-employee',employeeId:'rosa'});assert.equal(executives(departed).length,0);assert.equal(deserializeV4(serializeV4(departed)).ok,true);s=action(s,{id:'executive-training',type:'train',employeeId:'rosa',skill:'management'});assert.equal(executives(s).length,0);});
