import test from'node:test';import assert from'node:assert/strict';import{preparedHouse,action}from'./helpers/v4-house.mjs';import{post,debit,credit,accountBalance}from'../game/v4/finance.ts';import{startConsumerCampaign,campaignEffect}from'../game/v4/marketing.ts';
function launch(){let s=preparedHouse();s.campaign.stage=4;const e={id:'campaign-test-capital',origin:'action',type:'fixture',week:1,signature:'{}',details:{},entityIds:[]};s.events.push(e);post(s,e,'Explicit marketing integration equity',[debit('cash',2000000),credit('equity',2000000)]);s=action(s,{id:'campaign-test-site',type:'open-consumer-channel',kind:'ecommerce',cityId:'sf',warehouseId:'sf-storage',format:'online'});s=action(s,{id:"campaign-test-assortment",type:"consumer-policy",channelId:s.consumerChannels[0].id,assortment:["embar62:r1"],weeklyMediaCents:0,shippingSubsidyCents:300,fulfillmentCases:150,deliveryWeeks:1,audience:"online"});return s;}
const proposal=s=>({channelId:s.consumerChannels[0].id,brief:'A winter collection for repeat buyers',audience:'online',objective:'retention',creativeCents:80000,weeklyMediaCents:60000,startWeek:2,durationWeeks:4,measurement:'Contribution after media, parcel cost and returns'});
test('regional campaigns require a paid creative brief, approved audience, launch window and measurement',()=>{let s=launch();s=action(s,{id:'campaign-creative',type:'start-consumer-campaign',...proposal(s)});assert.equal(accountBalance(s,'marketing'),80000);assert.equal(s.consumerCampaigns[0].endWeek,5);assert.equal(campaignEffect(s,s.consumerChannels[0]).mediaCents,0);s.week=2;assert.equal(campaignEffect(s,s.consumerChannels[0]).mediaCents,60000);assert.equal(campaignEffect(s,s.consumerChannels[0]).audience,'online');assert.throws(()=>startConsumerCampaign(s,{...proposal(s),creativeCents:0},{id:'free-creative',week:2,details:{}}));});
test('a finite campaign saturates and fatigues instead of granting permanent universal demand',()=>{let s=launch();s=action(s,{id:'campaign-fatigue',type:'start-consumer-campaign',...proposal(s),durationWeeks:12});const c=s.consumerChannels[0];s.week=2;const early=campaignEffect(s,c);s.week=11;assert.ok(campaignEffect(s,c).strength<early.strength);s.week=14;assert.equal(campaignEffect(s,c).mediaCents,0);assert.equal(campaignEffect(s,c).strength,0);});

test('paid campaigns close ordinary weekly media, stop prospectively and preserve creative costs on native reload',async()=>{const{resolveWeek}=await import('../game/v4/tick.ts'),{deserializeV4,serializeV4}=await import('../game/v4/saves.ts');let s=launch();s=action(s,{id:'marketing-hidden-display',type:'retail-assortment',recipeRevisionIds:[]});s=action(s,{id:'marketing-production',type:'production-plan',plan:{factoryId:'sf-workshop',items:[{recipeRevisionId:'embar62:r1',cases:60}]}});s=action(s,{id:'marketing-actual-brief',type:'start-consumer-campaign',...proposal(s)});const close=id=>{const r=resolveWeek(s,{tickId:id,expectedWeek:s.week});assert.equal(r.ok,true,r.error);s=r.state;};close('marketing-install');assert.equal(accountBalance(s,'marketing'),80000);close('marketing-media');assert.equal(accountBalance(s,'marketing'),140000);assert.ok(s.consumerOrders.some(o=>o.status==='pending'));s=action(s,{id:'marketing-stop',type:'stop-consumer-campaign',campaignId:s.consumerCampaigns[0].id});close('marketing-delivery');assert.equal(accountBalance(s,'marketing'),140000);assert.ok(s.consumerOrders.some(o=>o.status==='delivered'));assert.equal(deserializeV4(serializeV4(s)).ok,true);const bad=structuredClone(s);bad.consumerCampaigns[0].creativeCents=0;assert.equal(deserializeV4(JSON.stringify(bad)).ok,false);});

test('stopping future media cannot refund the creative work already paid for',async()=>{const{deserializeV4}=await import('../game/v4/saves.ts');let s=launch();s=action(s,{id:'sunk-creative',type:'start-consumer-campaign',...proposal(s)});s=action(s,{id:'sunk-stop',type:'stop-consumer-campaign',campaignId:s.consumerCampaigns[0].id});assert.equal(deserializeV4(JSON.stringify(s)).ok,true);const e=s.events.find(e=>e.id==='sunk-stop');post(s,e,'Unpaid return of creative costs',[debit('cash',80000),credit('marketing',80000,s.consumerCampaigns[0].id)],'refund',{regionId:'north-america',channelId:'ecommerce'});assert.equal(deserializeV4(JSON.stringify(s)).ok,false);});
