import test from 'node:test';
import assert from 'node:assert/strict';
import {newV4,serializeV4,deserializeV4} from '../game/v4/saves.ts';
import {applyCommand} from '../game/v4/commands.ts';
import {accountBalance} from '../game/v4/finance.ts';
import {resolveWeek} from '../game/v4/tick.ts';
const fresh=()=>newV4({founder:'B',business:'House',emblem:'cocoa',primary:'#184f45',accent:'#cd925a'});
const act=(s,c)=>{const r=applyCommand(s,c);assert.equal(r.ok,true,r.error);return r.state;};
const request={supplierId:'rafi',packagingId:'ordinary-wrap',quantityUnits:2000,warehouseId:'sf-storage'};
test('packaging uses discovered supplier eligibility, explicit minimums and a separate reconciled physical asset',async()=>{
 const {quotePackaging}=await import('../game/v4/packaging.ts');let s=fresh();assert.equal(quotePackaging(s,{...request,quantityUnits:1}).ok,false);assert.equal(quotePackaging(s,{...request,packagingId:'presentation-box'}).ok,false);assert.equal(quotePackaging(s,{...request,supplierId:'guayas'}).ok,false);const quote=quotePackaging(s,request);assert.equal(quote.ok,true,quote.error);s=act(s,{id:'wraps',type:'purchase-packaging',request,quoteId:quote.quote.id});assert.equal(s.inventory[0].kind,'packaging');assert.equal(s.inventory[0].quantity,2000);assert.equal(accountBalance(s,'packaging-inventory'),quote.quote.totalCents);assert.equal(accountBalance(s,'raw-inventory'),0);assert.equal(deserializeV4(serializeV4(s)).ok,true);
});
test('bulk packaging changes cost, receiving space and protection without granting intrinsic chocolate quality',async()=>{
 const {quotePackaging,packagingFamilies}=await import('../game/v4/packaging.ts');const s=fresh(),small=quotePackaging(s,request),bulk=quotePackaging(s,{...request,quantityUnits:10000});assert.equal(small.ok,true,small.error);assert.equal(bulk.ok,true,bulk.error);assert.ok(bulk.quote.unitGoodsCents<small.quote.unitGoodsCents);assert.ok(bulk.quote.storageMilliliters>small.quote.storageMilliliters);assert.ok(packagingFamilies.find(p=>p.id==='presentation-box').packingExtraMinutesPerCase>packagingFamilies.find(p=>p.id==='ordinary-wrap').packingExtraMinutesPerCase);assert.ok(packagingFamilies.find(p=>p.id==='protective-pack').protection>packagingFamilies.find(p=>p.id==='ordinary-wrap').protection);
});
test('packaging freight remains physical stock in transit and survives arrival and dated history saves',async()=>{
 const {quotePackaging}=await import('../game/v4/packaging.ts');let s=act(fresh(),{id:'bulk-intro',type:'discover-supplier',supplierId:'bay-bulk'});const r={...request,supplierId:'bay-bulk'},quote=quotePackaging(s,r);assert.equal(quote.ok,true,quote.error);s=act(s,{id:'freight',type:'purchase-packaging',request:r});assert.equal(s.inventory[0].locationId.startsWith('transit:'),true);for(let week=1;week<=3;week++){const closed=resolveWeek(s,{tickId:'week:'+week,expectedWeek:week});assert.equal(closed.ok,true,closed.error);s=closed.state;assert.doesNotThrow(()=>serializeV4(s));}assert.equal(s.shipments[0].status,'arrived');assert.equal(accountBalance(s,'packaging-inventory'),s.inventory.filter(l=>l.kind==='packaging').reduce((n,l)=>n+l.costCents,0));
});
test('a certified line cannot create wrapped goods without physical packs, and packing transfers landed asset cost once',async()=>{
 const {preparedHouse,action}=await import('./helpers/v4-house.mjs');const {scheduleProduction}=await import('../game/v4/production.ts');let s=preparedHouse();const plan={factoryId:'sf-workshop',items:[{recipeRevisionId:'embar62:r1',cases:20}]};
 const noPacks=structuredClone(s);noPacks.inventory=noPacks.inventory.filter(l=>l.kind!=='packaging');const missing=scheduleProduction({state:noPacks,factoryId:plan.factoryId},plan);assert.equal(missing.rows[0].goodCases,0);assert.ok(missing.constraints.some(c=>c.includes('packaging')));
 if(!s.inventory.some(l=>l.kind==='packaging'))s=action(s,{id:'packs',type:'purchase-packaging',request});const before=accountBalance(s,'packaging-inventory');s=action(s,{id:'plan',type:'production-plan',plan});s=action(s,{id:'high',type:'set-price',recipeRevisionId:'embar62:r1',priceCents:1000000});const closed=resolveWeek(s,{tickId:'pack-week',expectedWeek:1});assert.equal(closed.ok,true,closed.error);s=closed.state;const row=s.lastProduction[0].rows[0];assert.equal(row.packagingConsumed.reduce((n,l)=>n+l.quantity,0),row.inputCases*20);assert.equal(before-accountBalance(s,'packaging-inventory'),row.packagingCents);assert.equal(row.conversionCents,row.inputCases*44);assert.equal(accountBalance(s,'finished-inventory'),row.materialCents+row.packagingCents+row.conversionCents);assert.doesNotThrow(()=>serializeV4(s));
});
test('imports bind packaging quantity, identity, edition and value to paid procurement and historical use',()=>{
 let s=act(fresh(),{id:'paid',type:'purchase-packaging',request});for(const change of [l=>l.quantity*=10,l=>l.packagingId='presentation-box',l=>l.brandVersion=2]){const bad=structuredClone(s);change(bad.inventory[0]);assert.equal(deserializeV4(JSON.stringify(bad)).ok,false);}
 s=resolveWeek(s,{tickId:'closed',expectedWeek:1}).state;const bad=structuredClone(s);bad.snapshots[0].inventory.lots[0].quantity*=10;bad.events.find(e=>e.id==='closed').details.operatingActuals=JSON.stringify({production:bad.snapshots[0].production,inventory:bad.snapshots[0].inventory,obligations:bad.snapshots[0].obligations});assert.equal(deserializeV4(JSON.stringify(bad)).ok,false);
});
test('changing future packaging preserves the physical identity and sale appeal of already wrapped batches',async()=>{
 const {preparedHouse,action}=await import('./helpers/v4-house.mjs');let s=preparedHouse();s=action(s,{id:'plan',type:'production-plan',plan:{factoryId:'sf-workshop',items:[{recipeRevisionId:'embar62:r1',cases:20}]}});s=action(s,{id:'price',type:'set-price',recipeRevisionId:'embar62:r1',priceCents:1000000});s=resolveWeek(s,{tickId:'old-wrap-week',expectedWeek:1}).state;s.campaign.stage=2;
 s=action(s,{id:'select-box',type:'select-packaging',recipeRevisionId:'embar62:r1',packagingId:'presentation-box'});assert.equal(s.inventory.find(l=>l.kind==='finished').packagingId,'ordinary-wrap');assert.doesNotThrow(()=>serializeV4(s));s.factories[0].plan=[];s=resolveWeek(s,{tickId:'new-wrap-week',expectedWeek:2}).state;assert.equal(s.lastSales.retail.find(r=>r.offerId==='embar62:r1').packagingId,'ordinary-wrap');assert.doesNotThrow(()=>serializeV4(s));
});
test('an imported finished lot cannot acquire premium packaging appeal without paid batch consumption',async()=>{
 const {preparedHouse,action}=await import('./helpers/v4-house.mjs');let s=preparedHouse();s=action(s,{id:'plan',type:'production-plan',plan:{factoryId:'sf-workshop',items:[{recipeRevisionId:'embar62:r1',cases:20}]}});s=action(s,{id:'price',type:'set-price',recipeRevisionId:'embar62:r1',priceCents:1000000});s=resolveWeek(s,{tickId:'wrap-week',expectedWeek:1}).state;for(const change of [l=>l.packagingId='presentation-box',l=>l.brandVersion=999]){const forged=structuredClone(s);change(forged.inventory.find(l=>l.kind==='finished'));assert.equal(deserializeV4(JSON.stringify(forged)).ok,false);}
});
test('presentation packaging consumes more real packing time and finished space without improving intrinsic batch quality',async()=>{
 const {preparedHouse,action}=await import('./helpers/v4-house.mjs');const {scheduleProduction}=await import('../game/v4/production.ts');let s=preparedHouse();const {post,debit,credit}=await import('../game/v4/finance.ts');const funding={id:'packing-fixture-equity',origin:'action',week:s.week,type:'equity',signature:'packing-fixture',entityIds:['house'],details:{}};s.events.push(funding);post(s,funding,'Fund holding costs to isolate packaging tradeoffs',[debit('cash',200000),credit('equity',200000)]);s.campaign.stage=2;s=action(s,{id:'bulk-contact',type:'discover-supplier',supplierId:'bay-bulk'});s=action(s,{id:'boxes',type:'purchase-packaging',request:{supplierId:'bay-bulk',packagingId:'presentation-box',quantityUnits:1000,warehouseId:'sf-storage'}});for(let week=1;week<=3;week++){const r=resolveWeek(s,{tickId:'box-arrival-'+week,expectedWeek:week});assert.equal(r.ok,true,r.error);s=r.state;}
 const plan={factoryId:'sf-workshop',items:[{recipeRevisionId:'embar62:r1',cases:20}]},ordinary=scheduleProduction({state:s,factoryId:plan.factoryId},plan);s=action(s,{id:'boxes-selected',type:'select-packaging',recipeRevisionId:'embar62:r1',packagingId:'presentation-box'});const boxed=scheduleProduction({state:s,factoryId:plan.factoryId},plan);assert.equal(boxed.rows[0].quality,ordinary.rows[0].quality);assert.equal(boxed.rows[0].inputCases,ordinary.rows[0].inputCases);assert.ok(boxed.rows[0].stationMinutes.packing>ordinary.rows[0].stationMinutes.packing);assert.ok(boxed.rows[0].packagingCents>ordinary.rows[0].packagingCents);
});
