import test from 'node:test';
import assert from 'node:assert/strict';
import {preparedHouse,action} from './helpers/v4-house.mjs';
import {applyCommand} from '../game/v4/commands.ts';
import {post,debit,credit} from '../game/v4/finance.ts';
import {managedProduction} from '../game/v4/production-management.ts';
import {resolveWeek,previewWeek} from '../game/v4/tick.ts';
import {deserializeV4,serializeV4} from '../game/v4/saves.ts';
function house(){let s=preparedHouse();s.campaign.stage=3;const e={id:'manager-test-capital',origin:'action',week:1,type:'fixture',signature:'{}',entityIds:[],details:{}};s.events.push(e);post(s,e,'Declared focused management fixture',[debit('cash',2000000),credit('equity',2000000)]);s=action(s,{id:'hire-manager',type:'hire',employeeId:'rosa',factoryId:'sf-workshop'});return s;}
const production={priority:'commitments-first',minimumQuality:60,assortment:[{recipeRevisionId:'embar62:r1',maximumCases:80,stockTargetCases:12},{recipeRevisionId:'velvet-milk:r1',maximumCases:30,stockTargetCases:10}]};
const policy={type:'delegation-policy',factoryId:'sf-workshop',managerId:'rosa',enabled:true,budgetCents:20000000,items:[],packaging:[],production};
test('approved manager schedules due promises before discretionary goods using real physical capacity and round-trip evidence',()=>{let s=action(house(),{id:'buyer-promise',type:'accept-order',orderId:'ferry'});s=action(s,{id:'authority',...policy});const before=serializeV4(s),plan=managedProduction(s,s.delegationPolicies[0]);assert.equal(plan.items[0].contractId,s.contracts[0].id);assert.ok(plan.items[0].cases<=80);const preview=previewWeek(s,{tickId:'manager-forecast',expectedWeek:s.week});assert.equal(serializeV4(s),before);assert.equal(preview.blocked,false);const r=resolveWeek(s,{tickId:'manager-close',expectedWeek:s.week});assert.equal(r.ok,true,r.error);assert.ok(r.state.events.some(e=>e.id==='schedule:manager-close:sf-workshop'));assert.ok(r.state.snapshots[0].production[0].rows[0].goodCases>0);assert.equal(deserializeV4(serializeV4(r.state)).ok,true);const forged=structuredClone(r.state);forged.delegationPolicies[0].production.assortment[0].maximumCases=1;const e=forged.events.find(e=>e.id==='authority'),c=JSON.parse(e.signature);c.production=forged.delegationPolicies[0].production;e.signature=JSON.stringify(c);e.details.policy=JSON.stringify(forged.delegationPolicies[0]);assert.equal(deserializeV4(JSON.stringify(forged)).ok,false);});
test('stock held for another buyer cannot satisfy a manager commitment or a discretionary target',()=>{let s=action(house(),{id:'reservation-order',type:'accept-order',orderId:'ferry'});const c=s.contracts[0];s.inventory.push({id:'reserved-fixture',kind:'finished',recipeRevisionId:'embar62:r1',locationId:'sf-storage',quantity:100,costCents:10000,quality:90,condition:100,bornWeek:1,arrivalWeek:1,expiryWeek:5,storageClass:'ambient',packagingId:c.packagingId,reservations:[{contractId:'another-promise',quantity:100}]});const p={...policy,production:{...production,assortment:[production.assortment[0]]}},plan=managedProduction(s,p);assert.ok(plan.items.some(i=>i.contractId===c.id),'another commitment’s stock must not suppress this production');assert.ok(plan.items.some(i=>!i.contractId),'reserved stock must not count as free sale stock');});
test('quality and certification exceptions hold output; released assortments and weekly limits are explicit authority',()=>{let s=house();const p={...policy,production:{...production,minimumQuality:100}};assert.equal(managedProduction(s,p).items.length,0);assert.match(managedProduction(s,p).exceptions.join(' '),/Quality floor/);s.processProfiles=[];assert.match(managedProduction(s,policy).exceptions.join(' '),/Recommission/);assert.equal(action(house(),{id:'large-finite-budget',...policy}).delegationPolicies[0].budgetCents,20000000);for(const assortment of [[{...production.assortment[0],maximumCases:0}],[{...production.assortment[0],recipeRevisionId:'unknown'}],[production.assortment[0],production.assortment[0]]]){assert.equal(applyCommand(house(),{id:'invalid-authority',...policy,production:{...production,assortment}}).ok,false);}
});

test('ending a manager contract preserves the dated paused policy and a recoverable native save',()=>{let s=action(house(),{id:'departure-authority',...policy});s=action(s,{id:'departure-manager',type:'release-employee',employeeId:'rosa'});assert.equal(s.delegationPolicies[0].enabled,false);assert.equal(deserializeV4(serializeV4(s)).ok,true);});
