import test from 'node:test';import assert from 'node:assert/strict';
import {preparedHouse,action} from './helpers/v4-house.mjs';
import {resolveWeek} from '../game/v4/tick.ts';import {post,debit,credit} from '../game/v4/finance.ts';
import {deserializeV4,serializeV4} from '../game/v4/saves.ts';import {workforceRows} from '../game/v4/workforce.ts';
function capital(s,id,cents){const e={id,origin:'action',week:s.week,type:'fixture',signature:'{}',entityIds:[],details:{}};s.events.push(e);post(s,e,'Declared focused retention fixture capital',[debit('cash',cents),credit('equity',cents)]);return s;}
function close(s,id){const r=resolveWeek(s,{tickId:id,expectedWeek:s.week});assert.equal(r.ok,true,r.error);return r.state;}
function emptyCash(s){const e={id:'declared-unpaid-payroll-fixture',origin:'action',week:s.week,type:'fixture',signature:'{}',entityIds:[],details:{}};s.events.push(e);post(s,e,'Declared focused cash crisis fixture',[debit('fees',s.cashCents),credit('cash',s.cashCents)]);return s;}
test('two visible unpaid-payroll warnings precede departures; recovery and paid rehiring preserve history and obligations',()=>{let s=emptyCash(preparedHouse());for(let i=0;i<3;i++){s=close(s,'unpaid-retention:'+i);assert.equal(deserializeV4(serializeV4(s)).ok,true);const row=workforceRows(s.events.at(-1)).find(r=>r.id==='sam');assert.equal(row.unpaidWeeks,i+1);assert.equal(row.departure,i===2);if(i<2)assert.equal(s.employees[0].departedWeek,undefined);}assert.equal(s.employees[0].departedWeek,3);assert.ok(s.unpaidObligations.length);s=capital(s,'declared-rehire-fixture',2000000);const before=s.cashCents;s=action(s,{id:'returning-sam',type:'rehire-employee',employeeId:'sam',factoryId:'sf-workshop'});assert.equal(before-s.cashCents,18000);s=close(s,'returning-paid-close');assert.equal(s.employees.find(p=>p.id==='sam').departedWeek,undefined);assert.equal(workforceRows(s.events.at(-1)).find(r=>r.id==='sam').unpaidWeeks,0);assert.equal(deserializeV4(serializeV4(s)).ok,true);const forged=structuredClone(s);forged.employees.find(p=>p.id==='mira').departedWeek=undefined;assert.equal(deserializeV4(JSON.stringify(forged)).ok,false);});
test('cohort unpaid payroll changes morale and real headcount after three closes; paid staffing can recover',()=>{let s=preparedHouse();s.campaign.stage=3;s=capital(s,'declared-team-retention-fixture',2000000);s=action(s,{id:'team-retention-leader',type:'hire',employeeId:'rosa',factoryId:'sf-workshop'});s=action(s,{id:'team-retention-contract',type:'configure-team',workplaceId:'sf-workshop',leaderId:'rosa',role:'production',grade:'apprentice',headcount:10,minutes:1200});s=emptyCash(s);for(let i=0;i<3;i++){s=close(s,'team-retention:'+i);assert.equal(deserializeV4(serializeV4(s)).ok,true);assert.equal(s.cohortTeams[0].headcount,i<2?10:9);}assert.equal(s.cohortTeams[0].morale,49);const forged=structuredClone(s);forged.cohortTeams[0].headcount=10;assert.equal(deserializeV4(JSON.stringify(forged)).ok,false);});
test('worked overtime causes recoverable performance pressure then actual departure only after repeated high-fatigue warnings',()=>{let s=preparedHouse();s.campaign.stage=3;s=capital(s,'declared-overwork-fixture',6000000);s=action(s,{id:'overwork-travel',type:'travel',cityId:'oakland'});s=action(s,{id:'overwork-site',type:'open-factory',cityId:'oakland',package:'flexible'});s=action(s,{id:'overwork-hire',type:'hire',employeeId:'theo',factoryId:'oakland-works'});s=action(s,{id:'overwork-hours',type:'employment-terms',employeeId:'theo',factoryId:'oakland-works',minutes:600});s=close(s,'overwork-install1');s=close(s,'overwork-install2');s=action(s,{id:'overwork-process',type:'commission',factoryId:'oakland-works',recipeRevisionId:'embar62:r1',mode:'assisted',controls:[.7,.7,.7]});s=action(s,{id:'overwork-target',type:'production-plan',plan:{factoryId:'oakland-works',items:[{recipeRevisionId:'embar62:r1',cases:120}]}});let warningCount=0;for(let i=0;i<14;i++){for(const[varietyId,target]of [['cocoa-ecuador',95000],['sugar-refined',60000]]){const held=s.inventory.filter(l=>l.varietyId===varietyId&&l.locationId==='oakland-receiving'&&l.expiryWeek>=s.week).reduce((n,l)=>n+l.quantity,0);if(held<target)s=action(s,{id:'overwork-stock:'+i+':'+varietyId,type:'purchase',request:{supplierId:'rafi',varietyId,quantityGrams:target-held,grade:'standard',warehouseId:'oakland-receiving'}});}const held=s.inventory.filter(l=>l.kind==='packaging'&&l.locationId==='oakland-receiving').reduce((n,l)=>n+l.quantity,0);if(held<3000)s=action(s,{id:'overwork-packs:'+i,type:'purchase-packaging',request:{supplierId:'rafi',packagingId:'ordinary-wrap',quantityUnits:Math.ceil((3000-held)/1000)*1000,warehouseId:'oakland-receiving'}});s=action(s,{id:'overwork-book:'+i,type:'book-overtime',employeeId:'theo',minutes:150});s=close(s,'overwork-close:'+i);const row=workforceRows(s.events.at(-1)).find(r=>r.id==='theo');if(row.overworkWeeks&& !row.departure)warningCount++;assert.equal(deserializeV4(serializeV4(s)).ok,true);if(row.departure){assert.equal(row.overworkWeeks,3);break;}if(i===0)assert.equal(s.employees.find(e=>e.id==='theo').departedWeek,undefined);}assert.equal(warningCount,2);assert.ok(s.employees.find(e=>e.id==='theo').departedWeek);});
