import {useEffect,useRef,useState} from 'react';
import {Anchor,ArrowLeft,ArrowUpRight,BookOpen,ChevronRight,Coins,HelpCircle,Compass,Factory,FlaskConical,Globe2,Mail,MapPin,Minus,Plus,RotateCcw,ScrollText,Settings,Ship,Star,X} from 'lucide-react';
import type {State} from '../../game/engine';
import * as E from '../../game/engine';
import {createWorld,PLACES,type Place,type WorldController} from './scene';
const icons={factory:Factory,supply:Ship,orders:ScrollText,markets:Globe2,lab:FlaskConical,finance:BookOpen};
export default function WorldView({s,onOpen,onLetter,onMenu,onHelp,onCloseWeek,panelOpen,busy}:{s:State;onOpen:(tab:string)=>void;onLetter:()=>void;onMenu:()=>void;onHelp:()=>void;onCloseWeek:()=>void;panelOpen:boolean;busy:boolean}){
 const host=useRef<HTMLDivElement>(null),controller=useRef<WorldController|null>(null),labels=useRef<Record<string,HTMLButtonElement|null>>({});
 const [place,setPlace]=useState<Place|null>(null),[interior,setInterior]=useState(false),[failed,setFailed]=useState(false),[ready,setReady]=useState(false),[goals,setGoals]=useState(false);
 const visit=(id:Place)=>{setPlace(null);if(id==='factory'&&!interior)setInterior(true);else onOpen(PLACES[id].tab)};
 const pickRef=useRef(visit);pickRef.current=visit;
 useEffect(()=>{if(!host.current)return;try{controller.current=createWorld(host.current,id=>pickRef.current(id),points=>{for(const [id,el] of Object.entries(labels.current)){if(el){const p=points[id];el.style.transform=p?`translate(${p.x}px,${p.y}px) translate(-50%,-100%)`:'';el.style.visibility=p?.visible?'visible':'hidden';}}});controller.current.setState(s);setReady(true);}catch(e){setFailed(true);console.error('3D world unavailable',e)}return()=>controller.current?.dispose()},[]);
 useEffect(()=>controller.current?.setState(s),[s]);useEffect(()=>{controller.current?.setInterior(interior)},[interior]);
 const f=E.forecast(s),location=place?PLACES[place]:null,active=s.contracts.filter(c=>c.status==='active'),pending=E.pendingLetters(s),latest=s.reports[0];
 const concern=place==='factory'?(f.risk[0]||`${E.hours(s)} of ${E.capacity(s)} hours scheduled. ${Object.values(s.plan).reduce((a,n)=>a+n,0)} cases planned.`):place==='supply'?(s.orders[0]?`${s.orders[0].qty} kg ${s.orders[0].ingredient} arrives in week ${s.orders[0].arrival}.`:`${Math.round(s.stock.cocoa.qty)} kg of cocoa in your storeroom. Plan ahead for sea freight.`):place==='orders'?(active[0]?`${active[0].client}: ${active[0].qty} cases by week ${active[0].due}.`:`${E.offers(s).length} orders available. Deposits can finance production.`):place==='markets'?`${s.markets.length} of 3 markets open. Different districts want different chocolate.`:place==='lab'?(s.project?`Your ${s.project.id} programme completes at the start of week ${s.project.ready}.`:`${s.research.length} signature recipes discovered. ${s.upgrades.length} workshop investments installed.`):`${E.money(s.debt)} on the workshop note. ${E.money(s.receivables.reduce((a,r)=>a+r.amount,0))} in unpaid balances.`;
 return <section className={`world-view ${panelOpen?'has-panel':''}`} aria-label="San Francisco game world">
  <div className="world-canvas" ref={host}/><div className="world-vignette"/>
  {!ready&&!failed&&<div className="world-loading"><Anchor/><span>Opening the harbour…</span></div>}
  {failed&&<div className="world-fallback"><h2>Welcome to San Francisco</h2><p>This browser could not start the 3D view. You can still visit every location below and play the complete strategy game.</p></div>}
  <header className="world-header"><div className="world-brand"><span className="house-crest">C<span>H</span></span><div><strong>CACAO HOUSE</strong><small>BEYOND THE FIRST BAR</small></div></div><div className="world-resources"><button aria-label="Cash details" onClick={()=>onOpen('finance')}><Coins/><b>{E.money(s.cash)}</b><small>Cash · details ↗</small></button><button aria-label="Reputation details" onClick={()=>onOpen('markets')}><Star/><b>{s.reputation}/100</b><small>Reputation</small></button><button aria-label="Factory capacity details" onClick={()=>onOpen('workshop')}><Factory/><b>{E.hours(s)}/{E.capacity(s)}h</b><small>Factory capacity</small></button><button aria-label="Workshop note details" onClick={()=>onOpen('finance')}><BookOpen/><b>{E.money(s.debt)}</b><small>Workshop note · {s.mode==='campaign'?'W16':'balance'}</small></button></div><div className="world-tools"><button aria-label="Messages" onClick={onLetter}><Mail/>{pending.length>0&&<b>{pending.length}</b>}</button><button aria-label="Tutorial and help" onClick={onHelp}><HelpCircle/></button><button aria-label="Settings" onClick={onMenu}><Settings/></button></div></header>
  <div className="world-chapter"><p>{s.growth.chapter==='growth'?'THE NEXT ADDRESS':s.mode==='sandbox'?'FREE TRADE':s.week<8?'CHAPTER I':'CHAPTER II'} <span>·</span> AUTUMN 2026</p><h1>{interior?'San Francisco Workshop':s.mode==='sandbox'?'Your name on the quay.':s.week<8?'A house worth saving.':'The cost of independence.'}</h1><span>{interior?'From bean to bar. Your name on every case.':'SAN FRANCISCO · CALIFORNIA · BAY AREA'}</span></div>
  <div className="world-view-switch"><button className={!interior?'active':''} onClick={()=>{setPlace(null);setInterior(false)}}><Globe2 size={16}/>City</button><button className={interior?'active':''} onClick={()=>{setPlace(null);setInterior(true)}}><Factory size={16}/>Workshop</button>{s.week>=3&&<button onClick={()=>onOpen('travel')}><Globe2 size={16}/>Travel</button>}</div>
  <div className="world-labels">{(Object.keys(PLACES) as Place[]).map(id=>{const Icon=icons[id];return <button key={id} ref={el=>{labels.current[id]=el}} className={`world-label ${place===id?'selected':''} ${id==='factory'?'home':''}`} onClick={()=>visit(id)} aria-label={`Visit ${PLACES[id].name}`}><Icon size={14}/><span>{interior?({factory:'Production',supply:'Storeroom',orders:'Dispatch',lab:'Research'} as Record<string,string>)[id]:PLACES[id].name}</span>{id==='orders'&&active.length>0&&<i>{active.length}</i>}</button>})}</div>
  {!location&&!(s.tutorial.enabled&&s.week<=3&&!s.tutorial.completed.includes('result2'))&&<aside className="world-objective"><button onClick={()=>setGoals(!goals)}><span className="objective-seal"><Anchor size={19}/></span><div><small>{s.mode==='campaign'?'CAMPAIGN OBJECTIVES':'YOUR INDEPENDENT HOUSE'}</small><strong>{s.growth.chapter==='growth'?`Network review in week ${s.growth.reviewWeek}`:s.mode==='campaign'?`${Math.max(0,17-s.week)} weeks to make your name`:'Build your international business'}</strong></div><ChevronRight size={18}/></button>{goals&&<div className="world-goals">{(s.growth.chapter==='growth'?[['Operating factories',`${E.growthGoals(s).factories} / 2`],['Reliable buyers',`${E.growthGoals(s).buyers} / 2`],['Last 4 weeks profit',E.money(E.growthGoals(s).profit)]]:[['Repay the note',E.money(s.debt)+' left'],['Complete orders',`${s.fulfilled} / 4`],['Signature order',`${s.signature} / 1`],['Open markets',`${s.markets.length} / 2`],['Earn trust',`${s.reputation} / 65`]]).map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>}
   {!goals&&<p>{f.risk.length?'Your production plan needs attention. Visit the workshop before closing the week.':active.length?`${active[0].client} is waiting for ${active[0].qty} cases. Due week ${active[0].due}.`:s.week===1?'Nadia has the workshop ready. Visit her, meet the dock merchant, and find your first buyer.':'Visit a location to plan your next move. Time advances only when you close the week.'}</p>}{!goals&&<button className="objective-visit" onClick={()=>visit(active.length?'orders':f.risk.length?'factory':s.week===1?'factory':'finance')}>{active.length?'Visit the Buyer Office':f.risk.length?'Visit the workshop':s.week===1?'Meet Nadia':'Review the house'}<ChevronRight size={14}/></button>}
  </aside>}
  {location&&place&&<aside className="location-card"><button className="location-dismiss" aria-label="Close location" onClick={()=>setPlace(null)}><X size={17}/></button><div className={`character-portrait portrait-${location.person==='Rafi Osman'?'rafi':location.person==='Mara Sen'?'mara':location.person==='Nadia Vale'?'nadia':'ellis'}`}/><div className="location-copy"><p>{location.role}</p><h2>{location.name}</h2><small>{location.person}</small><div>{location.description}</div><p className="location-concern">{concern}</p><div className="location-actions">{place==='factory'&&!interior?<button className="primary" onClick={()=>{setPlace(null);setInterior(true)}}>Enter the workshop<ArrowUpRight size={17}/></button>:<button className="primary" onClick={()=>onOpen(location.tab)}>{location.action}<ArrowUpRight size={17}/></button>}{place==='factory'&&!interior&&<button className="text-button" onClick={()=>onOpen('workshop')}>Production plan</button>}</div></div></aside>}
  <div className="world-camera"><button aria-label="Zoom in" onClick={()=>controller.current?.zoom(.2)}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>controller.current?.zoom(-.2)}><Minus size={18}/></button><button aria-label="Reset camera" onClick={()=>controller.current?.reset()}><Compass size={19}/></button></div>
  {latest&&<div className="world-news"><span>W{latest.week} · HOUSE NEWS</span><p>{latest.notes.find(n=>n.includes('Delivered')||n.includes('Arrived')||n.includes('Research'))||`${latest.produced} cases made · ${E.money(latest.retail)} retail · ${E.money(latest.profit)} trading profit`}</p></div>}
  <footer className="world-footer"><nav aria-label="Visit San Francisco">{(Object.keys(PLACES) as Place[]).map(id=>{const Icon=icons[id];return <button className={place===id?'selected':''} key={id} onClick={()=>visit(id)} aria-label={`Go to ${PLACES[id].name}`}><Icon size={22}/><span>{{factory:'Workshop',supply:'Harbour',orders:'Buyers',markets:'Markets',lab:'Research',finance:'Overview'}[id]}</span></button>})}</nav><div className="world-week"><div><small>WEEK {s.week}</small><strong>{f.risk.length?'Plan needs attention':`${E.money(f.closing)} expected cash`}</strong></div><button disabled={busy||s.status!=='playing'} className="primary" onClick={()=>f.risk.length?onOpen('workshop'):onCloseWeek()}>{busy?'Closing…':f.risk.length?'Review plan':'Close the week'}<ChevronRight size={18}/></button></div></footer>
  <div className="world-controls-hint">DRAG TO EXPLORE <span>·</span> TAP A LOCATION</div>
 </section>
}
