const chapter=(number:number,title:string,lead:string,cityId:string,locationId:string,brief:string,objective:string,scene:string)=>({id:'chapter:'+number,title,lead,cityId,locationId,brief,objective,scene});
export const regionalChapters=[
chapter(29,'Write the operating standard','Nadia','sf','office','Partners operate their own businesses. Choose a real assortment, quality floor, royalty, training and supply model. Opening payments remain deferred obligations while support earns them.','Fund and write a viable operating standard with a paid capable leader.','Nadia lays the manual beside the accounts. The royalty is earned on partner sales; the stores and their turnover remain the operators’ businesses.'),
chapter(30,'Accra’s supply partnership','Amina','accra','partner-office','Kofi’s dependable cocoa route supports a steady core; Ama’s specialty route asks for premium quality and narrower collections. Visit both sources, reserve priced capacity and choose the commitment that fits your portfolio.','Sign actual Accra supplier capacity and choose the core or specialty partnership.','The chosen supplier records the locked volume, price and minimum-use obligation. Amina keeps the supply commitment connected to the operating standard.'),
chapter(31,'Choose the first partners','Imani','accra','partner-office','Private capital, local buying, demand and operating skill differ between operators. Choose two bounded cohorts whose economics can support the standard instead of selling opening promises alone.','Select two real operators and commit their paid opening cohorts.','Imani introduces the operators by name. Their private cash and stock remain visible alongside the group’s support promises.'),
chapter(32,'Fund field support','Amina','accra','training-campus','A large intake consumes skilled hours before royalties arrive. Distinct regional leaders and paid field teams must support the stores already promised.','Install two support hubs and fund a routine field team under named leadership.','The field roster has contracted hours, payroll and training dates. Amina can now compare support capacity with the proposed intake.'),
chapter(33,'Support the opening cohort','Imani','mumbai','fulfillment','Training and launch supplies do not create consumer sales automatically. Follow an actual cohort through its first viable operating weeks and inspect its shortages.','Support a cohort through four actual compliant, viable operating weeks.','Priya brings the store records. The customers bought real available stock; the operator paid costs before the house earned royalties.'),
chapter(34,'Protect the name','Amina','accra','partner-office','Fast openings can damage several regions when quality or support fails. Pause intake, fund training or repair supply before asking the brand to carry another promise.','Maintain four consecutive weeks with at least two cohorts and no compliance failure.','Amina reads the individual store exceptions with you. The response protects the house’s name through actual support and quality outcomes.'),
chapter(35,'The regional review','Nadia','sf','office','Three profitable regions and two compliant cohorts must survive a12-week operating review. Customer advances are excluded from recurring cash flow; a30%downside must still cover debt.','Pass the regional readiness review before accepting Singapore’s route.','Nadia forwards Mei’s invitation. The regional operating system has earned the next scale of responsibility, while every existing promise remains due.')];
export const globalChapters=[
chapter(36,'Singapore opens the next route','Mei','singapore','regional-hub','Annual distribution buyers offer finite, different product allocations. Their customer advances can finance an industrial campus, but remain liabilities until actual eligible deliveries. Read the staffing, source and receivable exposure.','Meet a global buyer and accept a priced physical distribution framework.','Mei opens the route book. Large numbers now represent inventory, paid teams and refundable promises rather than a valuation shortcut.'),
chapter(37,'Allocate the next year','Malik','singapore','executive-floor','Finance, operations and brand executives need paid hours without conflicting local leadership. Compare regional retention, innovation and resilience budgets over a13-week review.','Appoint two named executives and approve a funded regional portfolio allocation.','The directors retain their assumptions and cash envelope. The founder chooses priorities while ordinary sites continue to operate.'),
chapter(38,'The seasonal portfolio','Sophie','singapore','flagship','A long-lived drinking line and a fresh collaboration serve different windows. Fund innovation while qualifying every product line; changes in source, keeping quality and process still need evidence.','Release twenty recipes across all eight lines including a stage-six recipe, and fund an innovation allocation.','Sophie walks the display with its released products. The portfolio contains distinct operating routes rather than many labels for the same bar.'),
chapter(39,'The brand under pressure','Amina','accra','supply-yard','The economics desk announces a dated supply or freight squeeze before it becomes effective. Locked sources, regional manufacture, funded transport and restrained intake offer different responses.','Operate through an announced shock with positive recurring cash flow and inspect its actual reports.','Amina compares the forecast with the closed accounts. The house has paid for its resilience; the shock did not disappear because a story button was pressed.'),
chapter(40,'A promise across regions','Malik','singapore','executive-floor','Industrial capacity is expensive and needs paid specialists, methods and real sources. Oversight compares the group’s delivered promises with weekly distribution allocations and ordinary customers.','Deliver an actual global framework from a paid industrial site while keeping95%service.','Malik traces the delivered goods back to paid production. Partner turnover stays outside the group’s recognized revenue.'),
chapter(41,'The global launch','Sophie','singapore','flagship','A regional flagship and an Istanbul collaboration test new recipes, presentation, local receiving and delayed settlement together. The launch is a walkable event supported by real deliveries.','Fulfill the Singapore launch and Istanbul global collaboration.','The flagship opens around your house identity. Mei and Deniz bring the actual collection responses; the ongoing business retains its customers, staff and obligations.'),
chapter(42,'A house that outlasts its founder','Nadia','sf','office','The fictional enterprise estimate uses52closed weeks of group-recognized revenue with bounded margin, growth and reliability factors. Four successive quarterly reviews must exceed$2billion while cash, debt, service and quality remain sound.','Pass all global gates and meet Nadia at the headquarters anniversary.','Nadia draws back the doors for the anniversary. Your brand, qualified collection and regional collaborators belong to an operating house that can continue beyond its founder’s final chapter.')];
