/** Authored recovery leads; these explain operating choices without granting progress. */
export const chapterRecovery = [
 'Inspect the workshop from the waterfront. Your name and colors can be edited in Settings without restarting the house.',
 'Use Cash & commitments to compare installments, then preview an ordinary week before spending the founding cash.',
 'Inspect the bottleneck before buying a larger station. Hire paid operators, purchase the needed inputs and packaging, and certify each recipe locally; a smaller feasible plan can be saved first.',
 'Inspect each buyer’s delivery window, stock reservations and settlement. Renegotiate Leda’s missed first promise if necessary; accept replacement offers only when their paid stock route is feasible.',
 'Read actual sales beside unsold stock and direct costs. Reduce an excessive asking price or batch, or improve the actual formulation and grade before relying on premium demand.',
 'Repair arrears and preserve two weeks of unrestricted operating cover. A smaller profitable assortment can establish contribution before financing the collection.',
 'Meet Claire inside the showroom. Compare both disclosed orders before choosing; the uncommitted collection brief can be revised there.',
 'Visit Luca’s workshop for the actual brief, then choose compatible hazelnut inputs in the paid development lab. Keep the existing products running while research uses cash and hours.',
 'Discover the Guayaquil source and choose a real receiving warehouse. Compare grade, freight and lead time; the chapter needs a paid cocoa purchase rather than a visit alone.',
 'Meet Ximena at the Oaxaca market and inspect the inclusion brief. Start a separate amber-peel formulation rather than renaming an existing product.',
 'Inspect the supplier’s dated bulk bands and receiving capacity. Pick a quantity that earns an actual discount while preserving payroll cash and expiry headroom.',
 'Reserve compatible physical pilot ingredients and paid research hours. A poor finding can be revised or abandoned; its consumed materials and fees remain costs.',
 'Release enough distinct lines, deliver the signed Paris order and inspect the four closed statements. Reduce discretionary spending and settle overdue bills before committing the second-site deposit.',
 'Compare the Oakland premises terms and installation date. Preserve the home workshop’s stock and wages while the paid second site is being commissioned.',
 'Assign a local manager and operators, receive inputs locally and certify two methods against Oakland’s equipment. Start with a feasible small operating batch.',
 'Meet Aoi’s tea brief and run its actual paid pilot. Keeping quality and tea formulation must be established before treating the collection as saleable stock.',
 'Follow Salvador’s nut-free collection brief. Choose compatible plant and inclusion inputs and fund its own pilot; existing cocoa-bar findings do not substitute.',
 'Approve Oakland’s actual arrival policy and receiving space, then route a paid shipment there. A warehouse label alone does not move inventory.',
 'Select the same released revision in both process studios. Pay for the second factory’s independent method, or delegate to an eligible engineer after inspecting its terms.',
 'Appoint a paid available manager, approve discovered suppliers and a cash envelope, and enable procurement. Review replenishment targets and lead times before starting the saved four-week management turn.',
 'Inspect the failed network gate and its eight-week source records. Repair service, physical shortages or operating losses before adding consumer commitments; preserve six weeks of fixed cover.',
 'Install the Paris flagship and its receiving route, then approve a released assortment. Transfer actual eligible stock before paying for a large launch.',
 'Compare store revenue with goods, rent, people and media in the dated channel report. Adjust asking prices and supply to local customers rather than opening another loss-making shop.',
 'Visit Deniz’s gift showroom and fund the cardamom pilot with compatible ingredients. A seasonal audience cannot rescue an unqualified formulation.',
 'Meet Priya at the launch studio and run the spiced-coffee pilot. Inspect keeping quality against warm fulfillment routes before committing customers.',
 'Stock the actual ecommerce warehouse, physical packaging and fulfillment capacity. Inspect due parcels and returns; customer advances become revenue only after delivery.',
 'Approve a bounded creative and media brief with at least three paid operating weeks. Read the completed campaign’s sales and spending; avoid paying for reach while stock is unavailable.',
 'Read each failed twelve-week consumer gate. Improve actual market contribution, repeat customers and parcel service; reduce media or expensive formats when their recognized results do not cover costs.',
 'Appoint the paid capable standard leader and choose viable assortment, quality and royalty terms. Compare the operator’s private economics before selling opening promises.',
 'Inspect both Accra sources, sign priced capacity with its minimum-use bill and choose the matching partnership. Paid agreements still need receiving capacity and working cash.',
 'Compare each named operator’s cash, skill and local demand. Choose bounded cohorts whose supply and support can be funded before committing more stores.',
 'Install two regional hubs, assign distinct available leaders and hire paid field capacity. Inspect support hours against the stores already promised.',
 'Trace each partner exception to source stock, supplier spot capacity, lead time or funded field support. Pause intake and repair the route before expecting four viable operating weeks.',
 'Pause expansion when quality or support fails. Fund training and repair paid supplies for both cohorts; inspect the consecutive compliance record rather than aggregate opening fees.',
 'Use regional statements and individual twelve-week cohort records to locate the failed gate. Restore recurring cash and downside debt cover while maintaining funded support; advances do not establish profit.',
 'Read the annual framework’s finite allocations, keeping terms and refundable advance. Accept a route only with a credible paid industrial, staffing and source plan.',
 'Choose executives who are paid, available and free of conflicting factory or field leadership. Compare actual regional results and approve only a funded thirteen-week allocation.',
 'Inspect missing product lines and stage-six briefs, fund distinct development and qualify their keeping/process methods. Innovation allocations consume cash independently of pilot costs.',
 'Read the announced effective and end dates in News. Compare locked sources, stock, transport and resilience budgets; operate through the actual squeeze and inspect closed cash afterward.',
 'Fund the industrial site’s real teams, calibrated recipes and inputs. Compare actual weekly framework deliveries with their scheduled allocations; repair missed service before accepting more volume.',
 'Inspect the Singapore and Istanbul contracts separately. Produce eligible local or transferred stock, physical presentation packaging and paid transport before their signed deadlines.',
 'Inspect all four dated quarterly reviews and the recognized trailing year. Repair recurring cash, debt cover, service or quality before a new review; partner turnover and advances cannot inflate the fictional estimate.',
] as const;
