export const consumerChapters=[
{id:'chapter:22',title:'The first flagship',lead:'Claire',cityId:'paris',locationId:'flagship',brief:'A display is not an owned shop. A flagship commits a real receiving route, refundable premises deposit, paid fitout and staff before the first sale. Its assortment competes with the original buyers for actual cases.',objective:'Open and install a paid flagship with an approved released assortment and local receiving stock.',scene:'Claire opens your flagship door. The installation and deposit are recorded; the local store still has to earn its rent, pay its people and keep the display supplied.'},
{id:'chapter:23',title:'A store is a business',lead:'Claire',cityId:'paris',locationId:'flagship',brief:'Footfall, no-purchase choices and nearby rivals limit the display. Compare the store’s actual sales and costs before promising another location. Borrowing and premises deposits do not count as contribution.',objective:'Earn positive store contribution in three actual closed weeks and read its dated channel report.',scene:'Claire places the shop’s three operating statements beside the window display. The house now knows what the local store earned after goods, media, rent and staffing, rather than treating its till receipts as profit.'},
{id:'chapter:24',title:'Istanbul’s gift season',lead:'Deniz',cityId:'istanbul',locationId:'gift-showroom',brief:'Deniz wants cardamom caramel for a gifting audience. Seasonal consideration can justify presentation stock, but the physical pilot still determines flavor and keeping quality. A short opportunity is different from a permanent sales bonus.',objective:'Meet Deniz’s gift-showroom brief and complete a paid cardamom-caramel pilot finding.',scene:'Deniz reads the spice pilot beside the seasonal retail calendar. Your formulation and paid finding remain after the season; the gifting audience and presentation costs change with the opportunity.'},
{id:'chapter:25',title:'Mumbai’s launch brief',lead:'Priya',cityId:'mumbai',locationId:'launch-studio',brief:'Coffee, spice and warm parcel routes make a different launch. A keeping-quality promise must cover transport; protective packaging is physical stock, not a checkbox that improves old batches.',objective:'Meet Priya’s launch brief and complete the paid spiced-coffee pilot finding.',scene:'Priya examines the coffee pilot and the fulfillment route. The house can now distinguish an attractive asking price from a launch that survives actual storage, parcel costs and returns.'},
{id:'chapter:26',title:'The online launch',lead:'Priya',cityId:'mumbai',locationId:'fulfillment',brief:'Online advances stay customer obligations until delivery. Delivery fees offset actual parcel costs; observed damage generates later refunds. A website cannot ship the same cases already promised to a buyer.',objective:'Deliver actual paid online parcels in three closed operating weeks and inspect the channel’s sales report.',scene:'Priya follows the parcels from physical stock to customer advances, delivered revenue and the return ledger. The online business is now an operating relationship rather than a free demand button.'},
{id:'chapter:27',title:'A campaign with consequences',lead:'Priya',cityId:'mumbai',locationId:'launch-studio',brief:'Choose an audience, paid creative production, objective and measurement plan. Media saturates and fatigues; launches without available stock lose consideration. Retention works from customers the house has actually served.',objective:'Finish a bounded campaign with three actual paid media weeks and read its dated sales and spending results.',scene:'Priya compares the measured launch window with its paid creative and media costs. Associated sales also reflect stock, price and existing customers; the campaign’s result is evidence for your next decision, not guaranteed attribution.'},
{id:'chapter:28',title:'Own the customer relationship',lead:'Nadia',cityId:'sf',locationId:'office',brief:'The operating brand needs viable markets, growing repeat relationships and profitable channels. Three unprofitable openings do not become success by adding together their deposits and loans.',objective:'Pass the 12-week consumer review with fourteen recipes, five lines, three viable markets, positive store/online contribution, repeat growth and current obligations.',scene:'Nadia signs the consumer review from its actual channel history. The house has earned the responsibility to support independent partners while protecting the quality and name customers already trust.'}
]as const;
