import type {Stage} from '../model.ts';

export interface FranchisePartner {
 id:string;name:string;lead:string;cityId:string;stage:Stage;maximumStores:number;
 capitalPerStoreCents:number;fitoutPerStoreCents:number;fixedPerStoreCents:number;
 operatingSkill:number;casesPerStore:number;giftingPeak:number;peakWeeks:[number,number];
 brief:string;districts:string[];
}
/** Separate operators and catchments, with disclosed capital and constraints.
 * Their kitchens, tills and assets belong to them, never to the house ledger. */
export const franchisePartners:FranchisePartner[]=[
 {id:'bay-neighborhood',name:'Bay Neighborhood Kitchens',lead:'Marisol Vega',cityId:'sf',stage:5,maximumStores:8,capitalPerStoreCents:3000000,fitoutPerStoreCents:1400000,fixedPerStoreCents:30000,operatingSkill:72,casesPerStore:72,giftingPeak:1.35,peakWeeks:[41,52],brief:'An experienced neighborhood operator with patient capital. Everyday prices suit its regulars; too many closely spaced openings divide the same district demand.',districts:['Sunset corner','Richmond market','Mission courtyard','Noe village','Bernal steps','Inner Sunset','North Beach lane','Cole Valley']},
 {id:'oakland-cafe-group',name:'East Bay Café Cooperative',lead:'Reuben Ellis',cityId:'oakland',stage:5,maximumStores:10,capitalPerStoreCents:2600000,fitoutPerStoreCents:1000000,fixedPerStoreCents:28000,operatingSkill:63,casesPerStore:95,giftingPeak:1.15,peakWeeks:[41,52],brief:'Lower fitout costs and larger everyday volumes. The team needs additional paid quality training before it can meet a demanding premium standard.',districts:['Temescal pantry','Lake Merritt walk','Rockridge café','Fruitvale courtyard','Uptown counter','Grand Lake','Piedmont avenue','West Oakland','Dimond district','Montclair village']},
 {id:'paris-curators',name:'Atelier des Quartiers',lead:'Camille Moreau',cityId:'paris',stage:5,maximumStores:6,capitalPerStoreCents:5500000,fitoutPerStoreCents:2800000,fixedPerStoreCents:75000,operatingSkill:82,casesPerStore:62,giftingPeak:1.85,peakWeeks:[41,52],brief:'A skilled presentation-led operator with expensive premises. Gift season supports a premium collection; year-round volume alone may not cover the leases.',districts:['Canal atelier','Marais passage','Left-bank cabinet','Batignolles table','Belleville salon','Montparnasse arcade']},
 {id:'turin-patisserie',name:'Torino Pastry Network',lead:'Giulia Ferrero',cityId:'turin',stage:5,maximumStores:4,capitalPerStoreCents:4500000,fitoutPerStoreCents:2300000,fixedPerStoreCents:42000,operatingSkill:76,casesPerStore:85,giftingPeak:1.5,peakWeeks:[45,52],brief:'Experienced pastry kitchens can handle short-lived products locally. Central supply ties cash to transport and keeping dates rather than avoiding that constraint.',districts:['Porta Palazzo','San Salvario','Crocetta counter','Vanchiglia workshop']},
 {id:'accra-community',name:'Accra Community Retail',lead:'Esi Adjei',cityId:'accra',stage:5,maximumStores:12,capitalPerStoreCents:3000000,fitoutPerStoreCents:1200000,fixedPerStoreCents:26000,operatingSkill:72,casesPerStore:100,giftingPeak:1.3,peakWeeks:[47,52],brief:'Strong regular demand and practical local cocoa knowledge. A dependable core range and supported training matter more than a luxury origin label.',districts:['Osu courtyard','Labone market','Adabraka corner','Madina pantry','East Legon','Dansoman table','Achimota walk','Kaneshie counter','Tema community','Spintex kitchen','Airport avenue','Cantonments']},
 {id:'istanbul-gift-houses',name:'Bosphorus Gift Houses',lead:'Selin Demir',cityId:'istanbul',stage:5,maximumStores:8,capitalPerStoreCents:3600000,fitoutPerStoreCents:1600000,fixedPerStoreCents:32000,operatingSkill:69,casesPerStore:100,giftingPeak:1.7,peakWeeks:[41,52],brief:'Gift-led demand rewards a distinctive assortment. Opening at the seasonal high leaves rent and support obligations after consideration returns to normal.',districts:['Kadıköy passage','Karaköy counter','Beşiktaş courtyard','Balat cabinet','Nişantaşı salon','Üsküdar market','Moda corner','Beyoğlu arcade']},
 {id:'mumbai-market-kitchens',name:'Mumbai Market Kitchens',lead:'Neel Desai',cityId:'mumbai',stage:5,maximumStores:20,capitalPerStoreCents:2400000,fitoutPerStoreCents:900000,fixedPerStoreCents:21000,operatingSkill:62,casesPerStore:120,giftingPeak:1.8,peakWeeks:[43,48],brief:'Affordable sites and broad reach come with a real training gap. Warm handling makes local controlled production and a reliable core assortment especially valuable.',districts:['Bandra market','Dadar pantry','Fort arcade','Powai counter','Chembur courtyard','Andheri kitchen','Juhu lane','Colaba table','Matunga cabinet','Worli corner','Goregaon walk','Malad market','Vile Parle','Ghatkopar','Kurla pantry','Parel passage','Santacruz','Mulund counter','Sion courtyard','Versova kitchen']},
 {id:'singapore-gallery',name:'Straits Gallery Retail',lead:'Mei Lin Ong',cityId:'singapore',stage:6,maximumStores:12,capitalPerStoreCents:7500000,fitoutPerStoreCents:4000000,fixedPerStoreCents:98000,operatingSkill:86,casesPerStore:140,giftingPeak:1.4,peakWeeks:[1,8],brief:'Professional teams and ample partner capital accompany demanding leases and competitive price comparisons. This is a regional portfolio decision, not free premium demand.',districts:['Tiong Bahru gallery','Joo Chiat table','Orchard arcade','Bugis cabinet','Katong counter','River Valley','Chinatown kitchen','Tanjong Pagar','Novena market','Holland village','Bishan corner','Tampines gallery']},
];
