/** Negotiated demand is external business, not a tutorial grant. */
export const repeatBuyerTerms={steady:{cases:20,priceCents:2100,minimumQuality:60,depositRatio:.10,window:2,delay:1,penaltyCents:3500},flexible:{cases:15,priceCents:1950,minimumQuality:58,depositRatio:0,window:3,delay:0,penaltyCents:2000}} as const;
export interface OrderOffer {id:string;stage:number;cityId:string;locationId:string;buyer:string;recipeId:string;cases:number;priceCents:number;minimumQuality:number;packagingId?:string;minimumShelfWeeks:number;depositBps:number;windowWeeks:number;settlementDelay:number;penaltyCents:number;brief:string;tradeoff:string;kind:'commission'|'launch'|'framework';startDelay?:number;}
export const orderOffers:OrderOffer[]=[
 {id:'sf-morning',stage:1,cityId:'sf',locationId:'ferry-cafe',buyer:'Leda · morning replenishment',recipeId:'embar62',cases:18,priceCents:2150,minimumQuality:60,minimumShelfWeeks:1,depositBps:0,windowWeeks:1,settlementDelay:0,penaltyCents:3500,brief:'A small early delivery competes with the week’s local retail experiment.',tradeoff:'Immediate cash; tight deadline and no advance deposit.',kind:'commission'},
 {id:'sf-gifts',stage:1,cityId:'sf',locationId:'office',buyer:'June · local gift desk',recipeId:'velvet-milk',cases:20,priceCents:2450,minimumQuality:66,minimumShelfWeeks:2,depositBps:1000,windowWeeks:2,settlementDelay:2,penaltyCents:4500,brief:'The gift desk pays for consistent milk bars rather than sheer throughput.',tradeoff:'Higher input grade and delayed balance; compare the cost of quality.',kind:'commission'},
 {id:'sf-rush',stage:1,cityId:'sf',locationId:'ferry-cafe',buyer:'Leda · conference catering',recipeId:'embar62',cases:35,priceCents:2300,minimumQuality:62,minimumShelfWeeks:1,depositBps:0,windowWeeks:1,settlementDelay:1,penaltyCents:8000,brief:'A conference needs a larger short run while ordinary customers still expect stock.',tradeoff:'Priority capacity versus retail margin; a missed deadline costs more.',kind:'commission'},
 {id:'paris-preview',stage:2,cityId:'paris',locationId:'gift-buyer',buyer:'Claire · collection preview',recipeId:'origin-collection',cases:24,priceCents:4300,minimumQuality:70,packagingId:'presentation-box',minimumShelfWeeks:4,depositBps:1000,windowWeeks:3,settlementDelay:1,penaltyCents:12000,brief:'A selective origin collection earns a premium for finish, presentation and proven keeping quality.',tradeoff:'Smaller paid launch with demanding quality and box capacity.',kind:'launch'},
 {id:'paris-broad-launch',stage:2,cityId:'paris',locationId:'gift-buyer',buyer:'Claire · broader collection launch',recipeId:'origin-collection',cases:60,priceCents:3600,minimumQuality:68,packagingId:'presentation-box',minimumShelfWeeks:3,depositBps:0,windowWeeks:4,settlementDelay:2,penaltyCents:18000,brief:'A broader launch reaches more buyers but ties up more working capital.',tradeoff:'Lower unit price, larger batch and later settlement; no advance financing.',kind:'launch'},
 {id:'turin-technique',stage:2,cityId:'turin',locationId:'trade-desk',buyer:'Luca · makers’ tasting',recipeId:'gianduja',cases:24,priceCents:4200,minimumQuality:70,minimumShelfWeeks:3,depositBps:0,windowWeeks:3,settlementDelay:0,penaltyCents:7000,brief:'A nut-led tasting tests whether roast quality earns its extra landed cost.',tradeoff:'Immediate settlement after imported specialist inputs and changeovers.',kind:'commission'},
 {id:'oaxaca-citrus',stage:2,cityId:'oaxaca',locationId:'local-buyer',buyer:'Ximena · market collection',recipeId:'amber-peel',cases:18,priceCents:3900,minimumQuality:68,minimumShelfWeeks:2,depositBps:1000,windowWeeks:2,settlementDelay:1,penaltyCents:6000,brief:'A compact citrus collection needs the right harvest route and compatible storage.',tradeoff:'Short seasonal lead time; preserving critical fruit quality matters.',kind:'commission'},
 {id:'paris-praline',stage:2,cityId:'paris',locationId:'gift-buyer',buyer:'Claire · praline comparison',recipeId:'copper-praline',cases:30,priceCents:4500,minimumQuality:72,packagingId:'presentation-box',minimumShelfWeeks:3,depositBps:0,windowWeeks:3,settlementDelay:2,penaltyCents:11000,brief:'Compare praline margin with origin bars under the same gift presentation.',tradeoff:'Nut cleaning, packing time and receivables compete with collection growth.',kind:'commission'},
 {id:'kyoto-fresh',stage:3,cityId:'kyoto',locationId:'confectioner',buyer:'Aoi · fresh tea counter',recipeId:'kyoto-tea-cream',cases:24,priceCents:5400,minimumQuality:74,minimumShelfWeeks:1,depositBps:0,windowWeeks:2,settlementDelay:0,penaltyCents:10000,brief:'A fresh tea product must survive the receiving route with its character intact.',tradeoff:'Cold space and short shelf life; produce near delivery rather than stockpiling.',kind:'commission'},
 {id:'salvador-fruit',stage:3,cityId:'salvador',locationId:'coastal-buyer',buyer:'Marisa · coastal assortment',recipeId:'cashew-coconut',cases:40,priceCents:4700,minimumQuality:71,minimumShelfWeeks:2,depositBps:1000,windowWeeks:3,settlementDelay:1,penaltyCents:10000,brief:'Regional cashew and coconut inputs offer a different cost and flavor mix.',tradeoff:'Reserve a route buffer without losing freshness or crowding the warehouse.',kind:'commission'},
 {id:'oakland-network',stage:3,cityId:'oakland',locationId:'bulk-desk',buyer:'Mateo · campus catering',recipeId:'embar62',cases:120,priceCents:2050,minimumQuality:64,minimumShelfWeeks:2,depositBps:0,windowWeeks:3,settlementDelay:2,penaltyCents:18000,brief:'Everyday volume belongs on a reliable line, not the premium workshop’s scarce changeover hours.',tradeoff:'Lower margin rewards specialization and actual network supply.',kind:'commission'},
 {id:'istanbul-gifts',stage:4,cityId:'istanbul',locationId:'retailer-office',buyer:'Deniz · gift-season retailers',recipeId:'cardamom-caramel',cases:80,priceCents:6100,minimumQuality:74,packagingId:'presentation-box',minimumShelfWeeks:2,depositBps:1500,windowWeeks:3,settlementDelay:2,penaltyCents:24000,brief:'Seasonal gifting pays for distinctive spice and presentation, then subsides.',tradeoff:'Volume before the season turns versus box storage and delayed cash.',kind:'commission'},
 {id:'mumbai-online',stage:4,cityId:'mumbai',locationId:'retail-buyer',buyer:'Priya · online launch samples',recipeId:'spiced-coffee',cases:70,priceCents:5200,minimumQuality:72,packagingId:'protective-pack',minimumShelfWeeks:3,depositBps:0,windowWeeks:3,settlementDelay:1,penaltyCents:20000,brief:'The launch travels through a fulfillment route rather than a gift display.',tradeoff:'Protection and handling cost can consume the headline online margin.',kind:'commission'},
 {id:'salvador-fresh-counter',stage:4,cityId:'salvador',locationId:'coastal-buyer',buyer:'Marisa · fruit counter',recipeId:'passion-ganache',cases:45,priceCents:6800,minimumQuality:76,minimumShelfWeeks:1,depositBps:0,windowWeeks:2,settlementDelay:0,penaltyCents:18000,brief:'A fresh fruit counter rewards small frequent production over remote bulk inventory.',tradeoff:'Fragile keeping quality and a narrow arrival window, with immediate settlement.',kind:'commission'},
 {id:'accra-cocoa',stage:5,cityId:'accra',locationId:'partner-office',buyer:'Kofi · cocoa partnership event',recipeId:'pecan-bites',cases:100,priceCents:4200,minimumQuality:76,minimumShelfWeeks:3,depositBps:1000,windowWeeks:4,settlementDelay:1,penaltyCents:23000,brief:'A supply partnership values stable origin quality and a product suited to storage.',tradeoff:'Bulk sourcing earns a discount only if receiving space and quality hold.',kind:'commission'},
 {id:'mumbai-partner-support',stage:5,cityId:'mumbai',locationId:'fulfillment',buyer:'Priya · partner training cohort',recipeId:'biscuit-bites',cases:160,priceCents:3700,minimumQuality:70,packagingId:'protective-pack',minimumShelfWeeks:3,depositBps:0,windowWeeks:4,settlementDelay:2,penaltyCents:30000,brief:'Training samples are a genuine supplied order; partner store turnover is separate from group sales.',tradeoff:'Support commitments must not starve ordinary customer stock.',kind:'commission'},
 {id:'kyoto-repeat-retention',stage:5,cityId:'kyoto',locationId:'confectioner',buyer:'Aoi · repeat-customer assortment',recipeId:'oat-milk',cases:90,priceCents:4900,minimumQuality:74,minimumShelfWeeks:3,depositBps:0,windowWeeks:3,settlementDelay:1,penaltyCents:23000,brief:'A repeat-customer assortment contrasts stable everyday demand with expensive new acquisition.',tradeoff:'A fair recurring price versus the temptation to oversell premium novelty.',kind:'commission'},
 {id:'singapore-launch',stage:6,cityId:'singapore',locationId:'flagship',buyer:'Mei · regional flagship launch',recipeId:'mocha',cases:120,priceCents:6300,minimumQuality:78,packagingId:'presentation-box',minimumShelfWeeks:3,depositBps:0,windowWeeks:4,settlementDelay:1,penaltyCents:45000,brief:'The new regional platform must carry its own tested stage-six recipe.',tradeoff:'A new process and route under global commitments, not borrowed cash as success.',kind:'commission'},
 {id:'istanbul-global-collaboration',stage:6,cityId:'istanbul',locationId:'gift-showroom',buyer:'Deniz · global collaboration',recipeId:'almond-berry',cases:180,priceCents:6700,minimumQuality:78,packagingId:'presentation-box',minimumShelfWeeks:1,depositBps:1000,windowWeeks:4,settlementDelay:2,penaltyCents:50000,brief:'A global collaboration demands consistency while the portfolio remains broad.',tradeoff:'Fresh regional production, long receivables and the same accountable quality promise.',kind:'commission'},
 {id:'accra-resilience',stage:6,cityId:'accra',locationId:'supply-yard',buyer:'Kofi · supply resilience review',recipeId:'classic-drinking',cases:220,priceCents:4300,minimumQuality:76,minimumShelfWeeks:8,depositBps:0,windowWeeks:5,settlementDelay:1,penaltyCents:48000,brief:'A durable product tests the supply network’s buffer during the economic shock.',tradeoff:'Long-life inventory is useful only if capital, receiving space and source quality are funded.',kind:'commission'},
 {id:'global-everyday',stage:6,cityId:'singapore',locationId:'regional-hub',buyer:'Mei · regional everyday distribution',recipeId:'velvet-milk',cases:6000000,priceCents:2400,minimumQuality:78,minimumShelfWeeks:4,depositBps:2500,windowWeeks:60,startDelay:8,settlementDelay:2,penaltyCents:144000000,brief:'A finite annual distribution framework for six million everyday cases. Regional depots handle onward trade after receipt; your house must produce and deliver physical stock to Singapore.',tradeoff:'A25%customer advance funds capacity but remains refundable unearned liability. Eight weeks to commission; delayed balances, real quality, shelf life and a1%miss penalty. An industrial team and reserved ingredient capacity are necessary.',kind:'framework'},
 {id:'global-drinking',stage:6,cityId:'singapore',locationId:'origin-importer',buyer:'Aria · hospitality drinking collection',recipeId:'classic-drinking',cases:4500000,priceCents:4300,minimumQuality:80,minimumShelfWeeks:8,depositBps:2500,windowWeeks:60,startDelay:8,settlementDelay:1,penaltyCents:193500000,brief:'Hotels request four-and-a-half million long-life drinking cases over a trading year. A new product line, cocoa provenance and a higher quality floor change the factory mix.',tradeoff:'Stable long-life demand versus premium cocoa concentration. The refundable advance is no profit; each physical delivery earns only its own share.',kind:'framework'},
 {id:'global-plant',stage:6,cityId:'singapore',locationId:'flagship',buyer:'Sera · plant-based retail partnership',recipeId:'oat-milk',cases:3500000,priceCents:4900,minimumQuality:82,minimumShelfWeeks:4,depositBps:2000,windowWeeks:60,startDelay:8,settlementDelay:3,penaltyCents:171500000,brief:'A separate plant-based retail partner requests3.5million cases. Ingredient segregation, a high quality floor and longer receivables compete with everyday throughput.',tradeoff:'A higher headline price carries a smaller advance, stricter quality and three-week settlement. Choose the portfolio your paid staff and real inventory can serve.',kind:'framework'},

];
