import{packagingFamilies}from'./content/packaging.ts';
import type {V4State,DomainEvent,ConsumerChannel,ConsumerChannelProposal}from'./model.ts';
import{catalog}from'./catalog.ts';import{protectedCash}from'./sourcing.ts';import{post,debit,credit}from'./finance.ts';import{regionForCity}from'./content/regions.ts';
/** Tunable paid channel contracts, separate from factory capacity. */
export const consumerTerms={neighborhood:{depositCents:120000,setupCents:180000,rentCents:12000,staffCents:14000,capacityCases:90,installationWeeks:2,headcount:2},flagship:{depositCents:240000,setupCents:450000,rentCents:24000,staffCents:32000,capacityCases:240,installationWeeks:3,headcount:4},online:{depositCents:0,setupCents:180000,rentCents:5000,staffCents:8000,capacityCases:150,installationWeeks:1,headcount:2}};
export function openConsumerChannel(s:V4State,p:ConsumerChannelProposal,event:DomainEvent){const city=catalog.cities.find(c=>c.id===p.cityId&&c.stage<=s.campaign.stage),warehouse=s.warehouses.find(w=>w.id===p.warehouseId),terms=consumerTerms[p.format];if(s.campaign.stage<4||!city||!s.visitedCities.includes(city.id)||!warehouse||!terms||!['owned-retail','ecommerce'].includes(p.kind)||p.kind==='owned-retail'&&(p.format==='online'||warehouse.cityId!==p.cityId||s.currentCityId!==p.cityId)||p.kind==='ecommerce'&&p.format!=='online'||(s.consumerChannels??[]).some(c=>c.kind===p.kind&&c.cityId===p.cityId&&c.active))throw Error('Visit the market and choose an owned physical receiving route, a distinct channel and its disclosed format.');const total=terms.depositCents+terms.setupCents;if(total+protectedCash(s)>s.cashCents)throw Error('This channel investment would spend protected operating obligations.');const id='channel:'+event.id,scope={regionId:regionForCity(city.id),channelId:p.kind};if(terms.depositCents)post(s,event,'Refundable consumer premises deposit',[debit('premises-deposit',terms.depositCents,id),credit('cash',terms.depositCents)],'deposit',scope);post(s,event,p.kind==='ecommerce'?'Paid storefront, fulfillment and checkout launch':'Paid retail fitout and opening recruitment',[debit('commissioning',terms.setupCents,id),credit('cash',terms.setupCents)],'setup',scope);const channel:ConsumerChannel={id,kind:p.kind,cityId:p.cityId,warehouseId:p.warehouseId,format:p.format,active:true,readyWeek:s.week+terms.installationWeeks,assortment:[],prices:{},weeklyMediaCents:0,shippingSubsidyCents:300,fulfillmentCases:terms.capacityCases,retainedCustomers:0,trust:.5,staffHeadcount:terms.headcount,staffSkill:65,deliveryWeeks:1,audience:p.kind==='ecommerce'?'online':'gifting'};s.consumerChannels??=[];s.consumerChannels.push(channel);event.entityIds=[id,p.cityId,p.warehouseId];event.details={channel:JSON.stringify(channel),depositCents:terms.depositCents,setupCents:terms.setupCents,weeklyRentCents:terms.rentCents,weeklyStaffCents:terms.staffCents};}
export function consumerFixed(s:V4State){return(s.consumerChannels??[]).filter(c=>c.active).map(c=>({channel:c,...consumerTerms[c.format]}));}
export function consumerPolicy(s:V4State,c:{channelId:string;assortment:string[];prices?:Record<string,number>;weeklyMediaCents:number;shippingSubsidyCents:number;fulfillmentCases:number;deliveryWeeks:1|2;audience:import('./model.ts').SegmentId},event:DomainEvent){const channel=s.consumerChannels?.find(x=>x.id===c.channelId&&x.active);if(!channel||!validChannelPrices(s,c.prices)||!Array.isArray(c.assortment)||new Set(c.assortment).size!==c.assortment.length||c.assortment.some(id=>!s.recipeRevisions.some(r=>r.id===id&&r.released))||!Number.isSafeInteger(c.weeklyMediaCents)||c.weeklyMediaCents<0||c.weeklyMediaCents>250000||!Number.isSafeInteger(c.shippingSubsidyCents)||c.shippingSubsidyCents<0||c.shippingSubsidyCents>1000||!Number.isSafeInteger(c.fulfillmentCases)||c.fulfillmentCases<1||c.fulfillmentCases>consumerTerms[channel.format].capacityCases||![1,2].includes(c.deliveryWeeks)||!['value','gifting','enthusiast','online'].includes(c.audience))throw Error('Approve released products, an actual fulfillment limit, disclosed shipping support and a bounded weekly media plan.');for(const key of ['assortment','weeklyMediaCents','shippingSubsidyCents','fulfillmentCases','deliveryWeeks','audience']as const){Object.assign(channel,{[key]:c[key]});}if(c.prices!==undefined)channel.prices=structuredClone(c.prices);event.entityIds=[channel.id];event.details={policy:JSON.stringify(c)};}

export function validChannelPrices(s:V4State,prices:unknown){return prices===undefined||!!prices&&typeof prices==='object'&&!Array.isArray(prices)&&Object.entries(prices).every(([id,value])=>s.recipeRevisions.some(r=>r.id===id&&r.released)&&typeof value==='number'&&Number.isSafeInteger(value)&&value>=100&&value<=100000);}
export function consumerPrice(s:V4State,c:ConsumerChannel,id:string){const r=s.recipeRevisions.find(r=>r.id===id);return c.prices?.[id]??s.prices[id]??catalog.recipes.find(p=>p.id===r?.recipeId)!.referencePriceCents;}
export function consumerParcelCost(s:V4State,c:ConsumerChannel){const origin=s.warehouses.find(w=>w.id===c.warehouseId)!,same=origin.cityId===c.cityId,near=['sf','oakland'].includes(origin.cityId)&&['sf','oakland'].includes(c.cityId);return(same?200:near?300:regionForCity(origin.cityId)===regionForCity(c.cityId)?500:800)+(['mumbai','salvador'].includes(c.cityId)?150:0);}
export function channelPriceCredibility(s:V4State,c:ConsumerChannel){let credibility=1;for(const id of c.assortment){const own=consumerPrice(s,c,id),other=(s.consumerChannels??[]).filter(o=>o.id!==c.id&&o.active&&o.cityId===c.cityId&&o.readyWeek<=s.week&&o.assortment.includes(id)).map(o=>consumerPrice(s,o,id)+(o.kind==='ecommerce'?Math.max(0,consumerParcelCost(s,o)-o.shippingSubsidyCents):0)),lowest=Math.min(own,...other);if(own>lowest*1.15)credibility=Math.min(credibility,Math.max(.35,lowest*1.15/own));}return credibility;}

/** Resolve exact registered entities and retail transaction identities, never ID prefixes. */
export function consumerEntryChannel(s:V4State,j:import('./model.ts').LedgerEntry){for(const p of j.postings){if(!p.entityId)continue;const direct=s.consumerChannels?.find(c=>c.id===p.entityId);if(direct)return direct.id;const order=s.consumerOrders?.find(o=>o.id===p.entityId);if(order)return order.channelId;const campaign=s.consumerCampaigns?.find(c=>c.id===p.entityId);if(campaign)return campaign.channelId;if(p.entityId.startsWith(j.eventId+':'))for(const r of s.recipeRevisions)for(const pack of packagingFamilies){const tail=':'+r.id+':'+pack.id;if(p.entityId.endsWith(tail)){const candidate=p.entityId.slice(j.eventId.length+1,-tail.length);if(s.consumerChannels?.some(c=>c.id===candidate))return candidate;}}}return undefined;}
