import{portfolioFixed}from './global.ts';
import{ supplyMinimumFixed }from'./supply-agreements.ts';
import{teamsBefore,teamFixed}from'./teams.ts';import{maintenanceFixed}from'./maintenance.ts';import{machineLeaseFixed}from'./machine-orders.ts';import{retainedSiteFixed}from'./site-recovery.ts';import{stationCapacity}from'./equipment.ts';
import type {V4State,DomainEvent,Loan} from './model.ts';
import{accountBalance,starterLoan,serviceLoan,installment}from'./finance.ts';
import{facilities,type FacilityId}from'./commercial-finance.ts';
import{staffBefore}from'./staff-history.ts';
import{consumerTerms}from'./channels.ts';
import{franchiseTerms}from'./franchise.ts';
/** Reconstruct the actual support boundary before this close pays fixed bills.
 * Loan principal arrears are outside the accrued-obligation journal, so their
 * contracted replay is needed in addition to the dated balance sheet. */
export function franchiseFundingAt(s:V4State,event:DomainEvent,datedLoans?:Loan[],cashPrefixes?:number[]){
 const index=s.events.indexOf(event),prior=s.events.slice(0,index),loans:Loan[]=datedLoans??[starterLoan()],loanIds=new Set(s.loans.map(l=>l.id));
 if(!datedLoans)for(const e of prior){
  if(e.type==='select-funding'&&JSON.parse(e.signature).package==='leveraged')loans[0]=starterLoan(true);
  if(e.type==='take-loan'){const facility=e.details.facility as FacilityId,t=facilities[facility],principal=Number(e.details.principalCents);if(!t)throw Error('Unknown dated loan');loans.push({product:facility,id:'facility:'+facility,principalCents:principal,weeklyRateBps:t.rate,installmentCents:installment(principal,t.rate,t.term),remainingWeeks:t.term,nextDueWeek:e.week,arrearsCents:0,arrearsPrincipalCents:0,arrearsInterestCents:0,feesCents:0,arrearsSinceWeek:null,status:'active',bridge:false});}
  if(e.type==='finance-recovery'){if(e.details.option==='restructure')for(const l of loans)Object.assign(l,{principalCents:0,remainingWeeks:0,arrearsCents:0,arrearsPrincipalCents:0,arrearsInterestCents:0,feesCents:0,arrearsSinceWeek:null,status:'settled'});const principal=Number(e.details.principalCents),rate=Number(e.details.weeklyRateBps),term=Number(e.details.termWeeks);loans.push({id:String(e.details.loanId),principalCents:principal,weeklyRateBps:rate,installmentCents:installment(principal,rate,term),remainingWeeks:term,nextDueWeek:e.week,arrearsCents:0,arrearsPrincipalCents:0,arrearsInterestCents:0,feesCents:0,arrearsSinceWeek:null,status:'active',bridge:e.details.option==='bridge'});}
  if(e.origin==='tick')for(const l of loans.filter(l=>l.status!=='settled')){const position=s.ledger.findIndex(j=>j.eventId===e.id&&j.id.startsWith(e.id+':'+l.id+'-'));if(position<0)throw Error('Missing prior contracted service');serviceLoan({...s,week:e.week,cashCents:accountBalance(s,'cash',s.ledger.slice(0,position)),ledger:[],campaign:{...s.campaign}},l,e);}
 }
 const liveIds=new Set((s.franchiseCohorts??[]).map(c=>c.id));
 const position=s.ledger.findIndex(j=>j.eventId===event.id&&(j.id.startsWith(event.id+':payroll:')||j.id.startsWith(event.id+':rent:')||j.description==='Earlier operating obligation settled'||[...loanIds].some(id=>j.id.startsWith(event.id+':'+id+'-'))||j.kind==='inventory-expiry'||j.postings.some(p=>p.account==='royalty-revenue'||p.entityId&&liveIds.has(p.entityId))));
 if(position<0)throw Error('Missing close boundary');const ledger=s.ledger.slice(0,position),cashCents=cashPrefixes?.[position]??accountBalance(s,'cash',ledger),marker={...event,id:event.id+':funding-marker'},dated={...s,events:[...prior,event,marker]};
 const payroll=s.employees.reduce((n,e)=>{const past=staffBefore(dated,e.id,marker)?.employee;return n+(past&&past.departedWeek===undefined?past.wageCents:0)},0),exists=(id:string)=>prior.some(e=>e.entityIds.includes(id));
 const factories=s.factories.filter(f=>exists(f.id)).map(f=>{const result={...f,active:true,stations:Object.fromEntries(Object.keys(f.stations).map(id=>[id,{tier:1,minutes:stationCapacity(f.packageId,id as keyof typeof f.stations,1,f.capacityScale??1)}])) as typeof f.stations};for(const e of prior){let p:any={};try{p=JSON.parse(e.signature)}catch{}if(e.type==='close-factory'&&p.factoryId===f.id)result.active=false;if(e.type==='reopen-factory'&&p.factoryId===f.id)result.active=true;if(e.entityIds.includes(f.id)&&['upgrade-module','install-module','return-leased-module'].includes(e.type)){const j=s.machineOrders?.find(j=>j.id===p.orderId);const station=p.station??j?.station,tier=e.type==='upgrade-module'?result.stations[station as keyof typeof f.stations].tier+1:e.type==='install-module'?p.tier:j?.previousTier;if(station&&tier)result.stations[station as keyof typeof f.stations]={tier,minutes:stationCapacity(f.packageId,station,tier,f.capacityScale??1)};}}return result;});
 const rent=factories.filter(f=>f.active).reduce((n,f)=>n+f.rentCents,0)+s.warehouses.filter(w=>w.id==='sf-storage'||exists(w.id)).reduce((n,w)=>n+(w.rentCents??0),0)+(s.franchiseSupportHubs??[]).filter(h=>exists(h.id)).length*franchiseTerms.hubRentCents;
 const consumer=(s.consumerChannels??[]).filter(c=>exists(c.id)).reduce((n,c)=>n+consumerTerms[c.format].rentCents+consumerTerms[c.format].staffCents,0),installments=loans.filter(l=>l.status!=='settled').reduce((n,l)=>n+l.installmentCents+l.arrearsPrincipalCents,0),accrued=Math.max(0,-accountBalance(s,'arrears',ledger)),reserve=prior.filter(e=>e.type==='set-reserve').at(-1);
 const factoryOperations=factories.map(f=>({factoryId:f.id,startedWeek:1,policy:(()=>{const p=prior.filter(e=>e.type==='maintenance-policy'&&e.entityIds.includes(f.id)).at(-1);return p?JSON.parse(p.signature).policy:'reactive'})(),stations:{}})),machineOrders=(s.machineOrders??[]).filter(j=>prior.some(e=>e.id===j.id)).map(j=>({...j,status:prior.some(e=>e.type==='return-leased-module'&&JSON.parse(e.signature).orderId===j.id)?'returned':prior.some(e=>e.id===j.id+':installed')?'installed':'installing'})),operating={...s,week:event.week,events:prior,supplyAgreements:(s.supplyAgreements??[]).filter(a=>prior.some(e=>e.id===a.id)),factories,factoryOperations,machineOrders,cohortTeams:teamsBefore(dated,marker),siteClosures:(s.siteClosures??[]).filter(c=>prior.some(e=>e.id===c.id))} as V4State,additional=[...portfolioFixed({...operating,events:prior}),...supplyMinimumFixed(operating),...teamFixed(operating),...maintenanceFixed(operating),...machineLeaseFixed(operating),...retainedSiteFixed(operating)].reduce((n,c)=>n+c.amount,0);
 return {cashCents,protectedCents:Math.max(reserve?JSON.parse(reserve.signature).cents:0,payroll+rent+consumer+installments+accrued+additional)};
}
