import type {V4State,DomainEvent,FranchiseSupplyOrder,FranchiseSupplyDelivery,FranchiseCohort,InventoryLot} from './model.ts';
import {catalog} from './catalog.ts';import {franchisePartners} from './content/franchise-partners.ts';import {regionForCity} from './content/regions.ts';import {consumerReservedQuantity} from './channel-stock.ts';import {post,debit,credit} from './finance.ts';
export function franchiseSupplyQuote(s:V4State,p:{cohortId:string;recipeRevisionId:string;quantity:number}){
 const c=s.franchiseCohorts?.find(c=>c.id===p.cohortId),standard=s.franchiseStandards?.find(q=>q.id===c?.standardId),partner=franchisePartners.find(p=>p.id===c?.partnerId),warehouse=s.warehouses.find(w=>w.id===c?.warehouseId),revision=s.recipeRevisions.find(r=>r.id===p.recipeRevisionId),recipe=catalog.recipes.find(r=>r.id===revision?.recipeId);
 if(!c||c.paused||!partner||!warehouse||standard?.supply!=='central'||!standard.assortment.includes(p.recipeRevisionId)||!revision||!recipe||!Number.isSafeInteger(p.quantity)||p.quantity<1||p.quantity>50000)throw Error('Choose an active central cohort, its licensed product and a whole physical case quantity.');
 const nearby=warehouse.cityId===partner.cityId||['sf','oakland'].includes(warehouse.cityId)&&['sf','oakland'].includes(partner.cityId),sameRegion=regionForCity(warehouse.cityId)===regionForCity(partner.cityId),dueWeek=s.week+(nearby?1:2),unitPriceCents=Math.round(recipe.referencePriceCents*.65),shippingCents=p.quantity*(nearby?75:sameRegion?150:300)+(recipe.storageClass==='cold'?p.quantity*150:0),allocations:FranchiseSupplyOrder['allocations']=[];
 let remaining=p.quantity;for(const l of s.inventory.filter(l=>l.kind==='finished'&&l.recipeRevisionId===p.recipeRevisionId&&l.locationId===warehouse.id&&l.arrivalWeek<=s.week&&l.expiryWeek>=dueWeek+1&&l.quality*l.condition/100>=standard.minimumQuality).sort((a,b)=>a.expiryWeek-b.expiryWeek||a.id.localeCompare(b.id))){const quantity=Math.min(remaining,Math.max(0,l.quantity-l.reservations.reduce((n,r)=>n+r.quantity,0)-consumerReservedQuantity(s,l.id)));if(quantity){allocations.push({lotId:l.id,quantity});remaining-=quantity;}if(!remaining)break;}
 if(remaining)throw Error('The shipping warehouse lacks uncommitted licensed stock meeting quality and route keeping dates.');
 const committed=(s.franchiseSupplyOrders??[]).filter(o=>o.cohortId===c.id&&o.status==='pending').reduce((n,o)=>n+o.quantity*o.unitPriceCents+o.shippingCents,0);
 if(p.quantity*unitPriceCents+shippingCents+committed+partner.fixedPerStoreCents*c.stores*2+c.partnerArrearsCents>c.partnerCashCents)throw Error('The partner cannot cover this supply promise and two weeks of its own fixed commitments.');
 return {cohortId:c.id,recipeRevisionId:p.recipeRevisionId,warehouseId:warehouse.id,bookedWeek:s.week,dueWeek,quantity:p.quantity,unitPriceCents,shippingCents,status:'pending' as const,allocations};
}
/** Signed queued dispatch: cases stay owned in the source warehouse until
 * the dated delivery close. No deposit, income or private stock is invented. */
export function bookFranchiseSupply(s:V4State,p:{cohortId:string;recipeRevisionId:string;quantity:number},e:DomainEvent){const order:FranchiseSupplyOrder={id:'supply:'+e.id,...franchiseSupplyQuote(s,p)};s.franchiseSupplyOrders??=[];s.franchiseSupplyOrders.push(order);e.entityIds=[order.id,order.cohortId,order.warehouseId];e.details={order:JSON.stringify(order)};}
export function deliverFranchiseSupply(c:FranchiseCohort,o:FranchiseSupplyOrder,inventory:InventoryLot[],week:number,minimumQuality:number):FranchiseSupplyDelivery|undefined{
 const price=o.quantity*o.unitPriceCents+o.shippingCents;
 if(c.paused||c.partnerCashCents<price||o.allocations.some(a=>!inventory.some(l=>l.id===a.lotId&&l.kind==='finished'&&l.recipeRevisionId===o.recipeRevisionId&&l.locationId===o.warehouseId&&l.quantity>=a.quantity&&l.expiryWeek>=week+1&&l.quality*l.condition/100>=minimumQuality))){o.status='cancelled';o.exception='Delivery stopped: operating pause, actual working capital, quality or keeping dates no longer cover this order.';return;}
 const d:FranchiseSupplyDelivery={orderId:o.id,cohortId:c.id,revenueCents:o.quantity*o.unitPriceCents,shippingCents:o.shippingCents,consumed:[],stocks:[]};
 for(const [i,a]of o.allocations.entries()){const l=inventory.find(l=>l.id===a.lotId)!,cost=a.quantity===l.quantity?l.costCents:Math.floor(l.costCents*a.quantity/l.quantity);d.consumed.push({lotId:l.id,quantity:a.quantity,costCents:cost});l.quantity-=a.quantity;l.costCents-=cost;d.stocks.push({id:o.id+':finished:'+i,kind:'finished',recipeRevisionId:o.recipeRevisionId,quantity:a.quantity,costCents:a.quantity*o.unitPriceCents+Math.floor(o.shippingCents*(o.allocations.slice(0,i+1).reduce((n,a)=>n+a.quantity,0))/o.quantity)-Math.floor(o.shippingCents*(o.allocations.slice(0,i).reduce((n,a)=>n+a.quantity,0))/o.quantity),quality:l.quality*l.condition/100,arrivalWeek:week,expiryWeek:l.expiryWeek,supplierId:'house'});}
 c.partnerCashCents-=price;c.stock.push(...structuredClone(d.stocks));o.status='delivered';o.deliveredWeek=week;return d;
}
export function resolveFranchiseSupply(s:V4State,e:DomainEvent){const deliveries:FranchiseSupplyDelivery[]=[];
 for(const o of(s.franchiseSupplyOrders??[]).filter(o=>o.status==='pending'&&o.dueWeek<=s.week)){const c=s.franchiseCohorts?.find(c=>c.id===o.cohortId)!,standard=s.franchiseStandards!.find(p=>p.id===c.standardId)!,partner=franchisePartners.find(p=>p.id===c.partnerId)!,d=deliverFranchiseSupply(c,o,s.inventory,s.week,standard.minimumQuality);if(!d)continue;const scope={regionId:regionForCity(partner.cityId),channelId:'partner-supply'},cost=d.consumed.reduce((n,a)=>n+a.costCents,0);post(s,e,'Delivered licensed goods sold to an independent franchise operator',[debit('cash',d.revenueCents+d.shippingCents),credit('supply-revenue',d.revenueCents,o.id),credit('shipping',d.shippingCents,o.id)],o.id+':supply-sale',scope);post(s,e,'Actual central route carrier cost',[debit('shipping',d.shippingCents,o.id),credit('cash',d.shippingCents)],o.id+':carrier',scope);if(cost)post(s,e,'External licensed supply acquisition cost',[debit('cogs',cost,o.id),credit('finished-inventory',cost)],o.id+':supply-cogs',scope,'franchise-supply-cogs');deliveries.push(d);}
 s.inventory=s.inventory.filter(l=>l.quantity>0);if(s.franchiseSupplyOrders?.length){e.details.franchiseSupplyDeliveries=JSON.stringify(deliveries);e.details.franchiseSupplyOrders=JSON.stringify(s.franchiseSupplyOrders);}return deliveries;
}
