import {executiveAssignments} from './global.ts';
import {fieldTeamMinutes} from './teams.ts';
import {activeEmployee} from './site-recovery.ts';
import {staffBefore} from './staff-history.ts';
import type {V4State,DomainEvent,FranchiseStandardProposal,FranchiseSupportProposal,FranchiseStandard,FranchiseSupportHub} from './model.ts';
import {catalog} from './catalog.ts';
import {protectedCash} from './sourcing.ts';
import {post,debit,credit} from './finance.ts';
import {regionForCity} from './content/regions.ts';
export const franchiseTerms={standardCents:180000,hubSetupCents:220000,hubRentCents:15000,hubInstallationWeeks:2,supportMinutesPerStore:60};
const uint=(n:unknown):n is number=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=0;
export function validStandardTerms(s:V4State,p:FranchiseStandardProposal){return !!p&&Array.isArray(p.assortment)&&p.assortment.length>=2&&new Set(p.assortment).size===p.assortment.length&&p.assortment.every(id=>s.recipeRevisions.some(r=>r.id===id&&r.released))&&uint(p.minimumQuality)&&p.minimumQuality>=55&&p.minimumQuality<=95&&uint(p.royaltyBps)&&p.royaltyBps>=300&&p.royaltyBps<=1200&&['local','central'].includes(p.supply)&&uint(p.weeklySupportCents)&&p.weeklySupportCents>=2000&&p.weeklySupportCents<=20000&&uint(p.openingFeeCents)&&p.openingFeeCents>=100000&&p.openingFeeCents<=500000&&uint(p.feeEarningWeeks)&&p.feeEarningWeeks>=26&&p.feeEarningWeeks<=52&&uint(p.trainingWeeks)&&p.trainingWeeks>=2&&p.trainingWeeks<=4&&typeof p.brief==='string'&&p.brief.trim().length>=30&&p.brief.length<=1200;}
function leader(s:V4State,id:string){return s.employees.find(e=>activeEmployee(e)&&e.id===id&&['commercial','manager'].includes(e.role)&&e.skills.management>=75&&e.contractedMinutes>=1200&&!s.training.some(t=>t.employeeId===e.id));}
export function franchiseStandard(s:V4State,p:FranchiseStandardProposal,e:DomainEvent){
 if(s.campaign.stage<5||!leader(s,p.leaderId)||!validStandardTerms(s,p))throw Error('Approve released products, a capable contracted lead, quality, royalty, paid support and deferred opening-fee obligations.');
 if(franchiseTerms.standardCents+protectedCash(s)>s.cashCents)throw Error('Operating-standard work would spend protected commitments.');
 const standard:FranchiseStandard={id:'standard:'+e.id,version:(s.franchiseStandards?.length??0)+1,createdWeek:s.week,leaderId:p.leaderId,assortment:[...p.assortment],minimumQuality:p.minimumQuality,royaltyBps:p.royaltyBps,supply:p.supply,weeklySupportCents:p.weeklySupportCents,openingFeeCents:p.openingFeeCents,feeEarningWeeks:p.feeEarningWeeks,trainingWeeks:p.trainingWeeks,brief:p.brief.trim()};
 post(s,e,'Paid franchise operating manuals, training design and legal terms',[debit('commissioning',franchiseTerms.standardCents,standard.id),credit('cash',franchiseTerms.standardCents)],'standard',{channelId:'franchise-royalties'});s.franchiseStandards??=[];s.franchiseStandards.push(standard);e.entityIds=[standard.id,p.leaderId];e.details={standard:JSON.stringify(standard)};
}
export function configureFranchiseSupport(s:V4State,p:FranchiseSupportProposal,e:DomainEvent){
 if(executiveAssignments(s).some(a=>a.employeeId===p.leaderId)||s.campaign.stage<5||!s.franchiseStandards?.length||!s.visitedCities.includes(p.cityId)||s.currentCityId!==p.cityId||!catalog.cities.some(c=>c.id===p.cityId&&c.stage<=s.campaign.stage)||!leader(s,p.leaderId)||!uint(p.weeklyBudgetCents)||p.weeklyBudgetCents<20000||p.weeklyBudgetCents>500000||(s.delegationPolicies??[]).some(d=>d.enabled&&d.managerId===p.leaderId)||(s.franchiseSupportHubs??[]).some(h=>h.cityId===p.cityId||h.leaderId===p.leaderId))throw Error('Visit the region, fund a distinct support office and assign a capable lead whose hours are not allocated to another hub.');
 if(franchiseTerms.hubSetupCents+protectedCash(s)>s.cashCents)throw Error('Regional support setup would spend protected operating commitments.');
 const hub:FranchiseSupportHub={id:'support:'+e.id,cityId:p.cityId,leaderId:p.leaderId,weeklyBudgetCents:p.weeklyBudgetCents,readyWeek:s.week+franchiseTerms.hubInstallationWeeks};post(s,e,'Paid regional field-support office and training equipment',[debit('commissioning',franchiseTerms.hubSetupCents,hub.id),credit('cash',franchiseTerms.hubSetupCents)],'support-hub',{regionId:regionForCity(p.cityId),channelId:'franchise-royalties'});s.franchiseSupportHubs??=[];s.franchiseSupportHubs.push(hub);e.entityIds=[hub.id,p.cityId,p.leaderId];e.details={hub:JSON.stringify(hub)};
}
export function franchiseHubCapacity(s:V4State,h:FranchiseSupportHub){if(h.readyWeek>s.week)return 0;const e=s.employees.find(e=>activeEmployee(e)&&e.id===h.leaderId&&['commercial','manager'].includes(e.role)&&e.skills.management>=75),busy=e&&s.training.some(t=>t.employeeId===e.id);return e?Math.floor((e.contractedMinutes*(busy?.5:1)*(1-e.fatigue/200)+fieldTeamMinutes(s,h.id))/franchiseTerms.supportMinutesPerStore):0;}
export function franchiseSupportCapacity(s:V4State,cityId:string){return(s.franchiseSupportHubs??[]).filter(h=>regionForCity(h.cityId)===regionForCity(cityId)).reduce((n,h)=>n+franchiseHubCapacity(s,h),0);}
export function franchiseFixed(s:V4State){return(s.franchiseSupportHubs??[]).map(h=>({hub:h,rentCents:franchiseTerms.hubRentCents}));}
/** Immutable agreements replay exact signed choices and their one-time paid work. */
export function franchiseEvidenceErrors(s:V4State){const errors:string[]=[],standards=s.franchiseStandards??[],hubs=s.franchiseSupportHubs??[];if(!Array.isArray(standards)||!Array.isArray(hubs))return['Invalid franchise collections'];const events=s.events.filter(e=>['write-franchise-standard','franchise-support'].includes(e.type));if(events.length!==standards.length+hubs.length)errors.push('Missing franchise authority');
 for(const [index,p]of standards.entries()){const e=s.events.find(e=>e.id===p?.id?.slice('standard:'.length)&&e.type==='write-franchise-standard');let c:(FranchiseStandardProposal&{id:string;type:string})|undefined;try{c=JSON.parse(e?.signature??'')}catch{}const past=e&&c&&staffBefore(s,c.leaderId,e),capable=past&&['commercial','manager'].includes(past.employee.role)&&past.employee.skills.management>=75&&past.employee.contractedMinutes>=1200&&!past.training;const expected=c&&validStandardTerms(s,c)&&{id:'standard:'+e!.id,version:index+1,createdWeek:e!.week,leaderId:c.leaderId,assortment:c.assortment,minimumQuality:c.minimumQuality,royaltyBps:c.royaltyBps,supply:c.supply,weeklySupportCents:c.weeklySupportCents,openingFeeCents:c.openingFeeCents,feeEarningWeeks:c.feeEarningWeeks,trainingWeeks:c.trainingWeeks,brief:c.brief?.trim()};if(!e||!c||c.id!==e.id||c.type!==e.type||JSON.stringify(e.entityIds)!==JSON.stringify([p.id,p.leaderId])||!expected||!capable||JSON.stringify(p)!==JSON.stringify(expected)||e.details.standard!==JSON.stringify(p)||!exactPayment(s,e,'standard',franchiseTerms.standardCents,p.id,{channelId:'franchise-royalties'}))errors.push('Franchise standard differs from its dated paid terms');}
 for(const h of hubs){const e=s.events.find(e=>e.id===h?.id?.slice('support:'.length)&&e.type==='franchise-support');let c:(FranchiseSupportProposal&{id:string;type:string})|undefined;try{c=JSON.parse(e?.signature??'')}catch{}const past=e&&c&&staffBefore(s,c.leaderId,e),capable=past&&['commercial','manager'].includes(past.employee.role)&&past.employee.skills.management>=75&&past.employee.contractedMinutes>=1200&&!past.training;const before=e?s.events.slice(0,s.events.indexOf(e)):[],cityBefore=before.filter(ev=>ev.type==='travel'&&Number(ev.details.elapsedWeeks)===0||ev.origin==='tick'&&ev.details.arrivedCityId).at(-1),local=cityBefore?(cityBefore.details.arrivedCityId??cityBefore.entityIds[0]):'sf';if(!e||!c||c.id!==e.id||c.type!==e.type||JSON.stringify(e.entityIds)!==JSON.stringify([h.id,h.cityId,h.leaderId])||!standards.some(p=>before.some(ev=>ev.id===p.id.slice('standard:'.length)))||local!==h.cityId||!capable||!uint(c.weeklyBudgetCents)||c.weeklyBudgetCents<20000||c.weeklyBudgetCents>500000||!catalog.cities.some(p=>p.id===c.cityId)||JSON.stringify(h)!==JSON.stringify({id:'support:'+e.id,cityId:c.cityId,leaderId:c.leaderId,weeklyBudgetCents:c.weeklyBudgetCents,readyWeek:e.week+franchiseTerms.hubInstallationWeeks})||e.details.hub!==JSON.stringify(h)||!exactPayment(s,e,'support-hub',franchiseTerms.hubSetupCents,h.id,{regionId:regionForCity(h.cityId),channelId:'franchise-royalties'}))errors.push('Support office differs from its dated paid contract');}
 if((s.delegationPolicies??[]).some(p=>p.enabled&&hubs.some(h=>h.leaderId===p.managerId)))errors.push('Manager hours are allocated to both factory delegation and regional support');
 if(new Set(hubs.map(h=>h.cityId)).size!==hubs.length||new Set(hubs.map(h=>h.leaderId)).size!==hubs.length)errors.push('Support resources are allocated twice');return errors;
}
function exactPayment(s:V4State,e:DomainEvent,suffix:string,amount:number,id:string,scope:import('./model.ts').LedgerScope){const entries=s.ledger.filter(j=>j.eventId===e.id);return entries.length===1&&entries[0].id===e.id+':'+suffix&&entries[0].week===e.week&&JSON.stringify(entries[0].scope)===JSON.stringify(scope)&&JSON.stringify(entries[0].postings)===JSON.stringify([debit('commissioning',amount,id),credit('cash',amount)]);}
