import {loansAt} from './dated-finance.ts';import {staffBefore} from './staff-history.ts';
import type{V4State,DomainEvent}from './model.ts';import{financialSummary,post,debit,credit}from './finance.ts';import{regionForCity,regionCities}from './content/regions.ts';import{protectedCash}from './sourcing.ts';import{activeEmployee}from './site-recovery.ts';import{orderOffers}from './content/orders.ts';
function command(e:DomainEvent){try{return JSON.parse(e.signature)}catch{return {}}}
export function recurringOperatingFlow(s:V4State,from:number,to:number){const entries=s.ledger.filter(j=>j.week>=from&&j.week<=to),cash=entries.filter(j=>!j.postings.some(p=>p.account==='loan-principal'||p.account==='equity'||p.account==='equipment'||p.account==='premises-deposit')).reduce((n,j)=>n+j.postings.filter(p=>p.account==='cash').reduce((m,p)=>m+p.debitCents-p.creditCents,0),0),advances=entries.filter(j=>j.postings.some(p=>p.account==='customer-deposits'&&p.creditCents>0)).reduce((n,j)=>n+j.postings.filter(p=>p.account==='cash').reduce((m,p)=>m+p.debitCents-p.creditCents,0),0);return cash-advances;}
export function enterpriseValue(s:V4State,asOf=s.week-1){const from=Math.max(1,asOf-51),rows=s.snapshots.filter(w=>w.week>=from&&w.week<=asOf),entries=s.ledger.filter(j=>j.week>=from&&j.week<=asOf),p=financialSummary(s,entries),margin=p.revenueCents?Math.max(-1,Math.min(.6,p.profitCents/p.revenueCents)):0,previous=financialSummary(s,s.ledger.filter(j=>j.week>=from-52&&j.week<from)).revenueCents,growth=previous?Math.max(-.5,Math.min(.5,p.revenueCents/previous-1)):0,production=rows.flatMap(w=>w.production.flatMap(f=>f.rows)),quantity=production.reduce((n,r)=>n+r.goodCases,0),quality=quantity?production.reduce((n,r)=>n+r.quality*r.goodCases,0)/quantity:0,due=s.contracts.filter(c=>c.dueEnd>=from&&c.dueEnd<=asOf),promised=due.reduce((n,c)=>n+c.cases,0),delivered=due.reduce((n,c)=>n+s.salesHistory.filter(w=>w.week<=Math.min(c.dueEnd,asOf)).flatMap(w=>w.contracts).filter(r=>r.contractId===c.id).reduce((m,r)=>m+r.deliveredCases,0),0),frameworks=s.contracts.filter(c=>orderOffers.find(o=>o.id===c.offerId)?.kind==='framework'&&c.dueStart<=asOf&&c.dueEnd>=from),scheduled=frameworks.reduce((n,c)=>n+Math.floor(c.cases/52)*Math.max(0,Math.min(asOf,c.dueEnd)-Math.max(from,c.dueStart)+1),0),served=frameworks.reduce((n,c)=>n+s.salesHistory.filter(w=>w.week>=from&&w.week<=asOf).flatMap(w=>w.contracts).filter(r=>r.contractId===c.id).reduce((m,r)=>m+r.deliveredCases,0),0),service=Math.min(1,(promised+scheduled)?(delivered+served)/(promised+scheduled):s.serviceTrust),factor=Math.max(2,Math.min(14,4+margin*12+growth*3+service*2)),valueCents=rows.length===52?Math.round(p.revenueCents*factor):0,operatingFlowCents=recurringOperatingFlow(s,from,asOf),installments=s.loans.filter(l=>l.status!=='settled').reduce((n,l)=>n+l.installmentCents,0),downsideCoverage=installments?operatingFlowCents/Math.max(1,rows.length)*.7/installments:operatingFlowCents>0?Infinity:0;return{asOf,windowWeeks:rows.length,revenueCents:p.revenueCents,profitCents:p.profitCents,margin,growth,service,quality,factor,valueCents,operatingFlowCents,downsideCoverage,eligible:rows.length===52&&valueCents>200000000000&&operatingFlowCents>0&&downsideCoverage>=1&&service>=.95&&quality>=78&&!s.unpaidObligations.length&&s.loans.every(l=>!l.arrearsCents)};}
export function globalStart(s:V4State){return s.events.find(e=>e.type==='review-chapter'&&command(e).chapterId==='chapter:35')?.week;}
export function economicOutlook(s:V4State){const start=globalStart(s);if(start===undefined)return undefined;const cycle=Math.floor(Math.max(0,s.week-start)/26),announcement=start+cycle*26+5,effective=announcement+3,end=effective+7,kind=cycle%2===0?'cocoa':'freight';return{kind,announcement,effective,end,announced:s.week>=announcement,active:s.week>=effective&&s.week<=end,title:kind==='cocoa'?'Cocoa carryover squeeze':'Transport capacity squeeze',body:kind==='cocoa'?'A fictional forecast warns of35%higher spot cocoa prices and15%fewer discretionary market opportunities. Locked capacity prices remain fixed. Diversified origins, cash buffers and a long-life portfolio provide different responses.':'A fictional forecast warns of25%higher freight costs and15%fewer discretionary market opportunities. Local production, funded transport and slower intake provide different responses.'};}
export function economicPriceFactor(s:V4State,familyId:string){const n=economicOutlook(s);return n?.active&&n.kind==='cocoa'&&familyId==='cocoa'?1.35:1;}
export function economicFreightFactor(s:V4State){const n=economicOutlook(s);return n?.active&&n.kind==='freight'?1.25:1;}
export function economicDemandFactor(s:V4State,cityId=s.currentCityId){return economicOutlook(s)?.active ? (fundedPortfolio(s,'resilience',cityId) ? .92 : .85) : 1;}
export function executiveAssignments(s:V4State){return s.events.filter(e=>e.type==='appoint-executive').filter((e,i,all)=>all.findLastIndex(x=>command(x).role===command(e).role)===i).map(e=>({...command(e),sourceId:e.id}));}
export function executives(s:V4State){return executiveAssignments(s).filter(a=>{const p=s.employees.find(p=>p.id===a.employeeId&&activeEmployee(p)&&p.contractedMinutes>=1200&&p.skills.management>=80);return !!p&&!s.training.some(t=>t.employeeId===p.id)&&!s.ledger.some(j=>j.week===s.week-1&&j.postings.some(x=>x.account==='payroll'&&x.entityId===p.id&&x.debitCents>0)&&j.postings.some(x=>x.account==='arrears'&&x.creditCents>0));});}
export function appointExecutive(s:V4State,p:{employeeId:string;role:'finance'|'operations'|'brand'},e:DomainEvent){const person=s.employees.find(x=>x.id===p.employeeId&&activeEmployee(x)&&['manager','commercial'].includes(x.role)&&x.skills.management>=80&&x.contractedMinutes>=1200);if(s.campaign.stage<6||!['finance','operations','brand'].includes(p.role)||!person||(s.franchiseSupportHubs??[]).some(h=>h.leaderId===person.id)||(s.delegationPolicies??[]).some(d=>d.enabled&&d.managerId===person.id)||(s.cohortTeams??[]).some(t=>t.headcount&&t.leaderId===person.id)||executiveAssignments(s).some(x=>x.employeeId===person.id&&x.role!==p.role))throw Error('Appoint a paid senior colleague with20+hours and no conflicting local leadership responsibility.');const cost=500000;if(cost+protectedCash(s)>s.cashCents)throw Error('Preserve payroll and debt service before executive onboarding.');post(s,e,'Executive onboarding and region-review mandate',[debit('commissioning',cost,person.id),credit('cash',cost)],'appointment');e.entityIds=[person.id,p.role];e.details={name:person.name,role:p.role};}
export function portfolioPlans(s:V4State){return s.events.filter(e=>e.type==='allocate-portfolio'&&e.week<=s.week&&e.week+13>s.week).map(e=>({...command(e),startWeek:e.week,endWeek:e.week+12,id:e.id}));}
export function allocatePortfolio(s:V4State,p:{regionId:string;priority:'retention'|'innovation'|'resilience';weeklyBudgetCents:number},e:DomainEvent){if(s.campaign.stage<6||!Object.hasOwn(regionCities,p.regionId)||!['retention','innovation','resilience'].includes(p.priority)||!Number.isSafeInteger(p.weeklyBudgetCents)||p.weeklyBudgetCents<20000||p.weeklyBudgetCents>100000000||executives(s).length<2||portfolioPlans(s).some(a=>a.regionId===p.regionId)||protectedCash(s)+p.weeklyBudgetCents*2>s.cashCents)throw Error('Two paid executives must review a distinct13-week regional allocation and its funded cash envelope.');e.entityIds=[p.regionId,p.priority];e.details={priority:p.priority,weeklyBudgetCents:p.weeklyBudgetCents,endWeek:s.week+12};}
export function portfolioFixed(s:V4State){return portfolioPlans(s).map(p=>({label:'Approved regional '+p.priority+' allocation',account:(p.priority==='retention'?'marketing':p.priority==='innovation'?'research':'support') as 'marketing'|'research'|'support',amount:p.weeklyBudgetCents,entityId:p.id,scope:{regionId:p.regionId}}));}
export function portfolioDemand(s:V4State,cityId:string){const id=regionForCity(cityId),plans=portfolioPlans(s).filter(p=>p.regionId===id&&p.priority==='retention'),paid=plans.reduce((n,p)=>n+s.ledger.filter(j=>j.week<s.week&&j.week>=p.startWeek&&j.postings.some(x=>x.entityId===p.id&&x.account==='marketing'&&x.debitCents>0)).length,0);return Math.min(.12,paid*.01);}
export function globalWeeklyReview(s:V4State,e:DomainEvent){const start=globalStart(s);if(start===undefined)return;const n=economicOutlook(s);if(n&&s.week===n.announcement){e.details.globalNews=JSON.stringify(n);}if(s.week>start&&(s.week-start)%13===0){e.details.globalQuarterTerms=2;e.details.globalQuarter=JSON.stringify(enterpriseValue(s,s.week));}}
export function sustainedQuarters(s:V4State){return s.events.filter(e=>e.details.globalQuarter).slice(-4).map(e=>({sourceId:e.id,...JSON.parse(String(e.details.globalQuarter))}));}
/** Immutable quarterly proof uses only the completed event prefix. Future loans,
 * recipe output and customer contracts cannot change an earlier review. */
export function datedEnterpriseValue(s:V4State,e:DomainEvent){const events=s.events.slice(0,s.events.indexOf(e)+1),ids=new Set(events.map(e=>e.id)),loans=loansAt(s,e),arrears=Math.max(0,-financialArrears(s,ids));return enterpriseValue({...s,week:e.week+1,events,ledger:s.ledger.filter(j=>ids.has(j.eventId)),snapshots:s.snapshots.filter(w=>ids.has(w.tickId)),salesHistory:s.salesHistory.filter(w=>ids.has(w.tickId)),contracts:s.contracts.filter(c=>events.some(e=>['accept-order','accept-offer','repeat-order','repeat-regional-order'].includes(e.type)&&e.entityIds.includes(c.id))),loans,unpaidObligations:arrears?[{id:'dated-arrears',account:'payroll',cents:arrears,sinceWeek:e.week}]:[]},e.week);}
function financialArrears(s:V4State,ids:Set<string>){return s.ledger.filter(j=>ids.has(j.eventId)).reduce((n,j)=>n+j.postings.filter(p=>p.account==='arrears').reduce((m,p)=>m+p.debitCents-p.creditCents,0),0);}
export function globalEvidenceErrors(s:V4State){const errors:string[]=[],start=globalStart(s);for(const e of s.events){if(e.type==='appoint-executive'){const p=command(e),past=staffBefore(s,p.employeeId,e),person=past?.employee,j=s.ledger.filter(j=>j.eventId===e.id);if(p.id!==e.id||p.type!==e.type||!['finance','operations','brand'].includes(p.role)||!person||person.departedWeek!==undefined||past?.training||!['manager','commercial'].includes(person.role)||person.skills.management<80||person.contractedMinutes<1200||j.length!==1||j[0].id!==e.id+':appointment'||JSON.stringify(j[0].postings)!==JSON.stringify([debit('commissioning',500000,person.id),credit('cash',500000)]))errors.push('Executive appointment lacks its available paid senior colleague.');}
 if(e.details.globalQuarter!==undefined){try{const q=JSON.parse(String(e.details.globalQuarter));if(start===undefined||e.week<=start||(e.week-start)%13!==0||e.origin!=='tick'||!s.snapshots.some(w=>w.tickId===e.id)||e.details.globalQuarterTerms!==undefined&&e.details.globalQuarterTerms!==2||JSON.stringify(q)!==JSON.stringify(datedEnterpriseValue(s,e)))errors.push('Global review differs from dated recognized operations, quality, service, cash or debt.');}catch{errors.push('Unreadable global quarterly evidence.');}}
 if(start!==undefined&&e.origin==='tick'&&e.week>start&&(e.week-start)%13===0&&e.details.globalQuarter===undefined)errors.push('Missing scheduled global quarterly review.');}return errors;}

export function fundedPortfolio(s:V4State,priority:string,cityId:string){return portfolioPlans(s).filter(p=>p.priority===priority&&p.regionId===regionForCity(cityId)).some(p=>s.ledger.some(j=>j.week===s.week-1&&j.postings.some(x=>x.entityId===p.id&&x.account===(priority==='innovation'?'research':priority==='resilience'?'support':'marketing')&&x.debitCents>=20000)));}
