import {activeEmployee} from './site-recovery.ts';
import type {V4State,Factory,StationId,DomainEvent,FactoryOperations,MaintenancePolicy} from './model.ts';
import {post,debit,credit} from './finance.ts';import {protectedCash} from './sourcing.ts';import{regionForCity}from'./content/regions.ts';
export const factoryStations:StationId[]=['preparation','processing','tempering','cooling','packing'];
export function initialOperations(f:Factory,week:number):FactoryOperations{return{factoryId:f.id,startedWeek:week,policy:'reactive',stations:Object.fromEntries(factoryStations.map(id=>[id,{condition:100,availableMinutes:f.stations[id].minutes,downMinutes:0}])) as FactoryOperations['stations']};}
export function equipmentOperatingCosts(f:Factory,policy:MaintenancePolicy){const tiers=factoryStations.reduce((n,id)=>n+f.stations[id].tier-1,0),scale=f.capacityScale??1;return{maintenanceCents:Math.round((policy==='reactive'?0:policy==='preventive'?600+tiers*100:1600+tiers*200)*scale),standingCents:Math.round(factoryStations.reduce((n,id)=>n+[0,500,1500,4500][f.stations[id].tier-1],0)*scale),energyPerCase:Math.max(24,(f.packageId==='flexible'?50:f.packageId==='balanced'?44:36)-Math.floor(tiers/2))};}
function operating(s:V4State,f:Factory){s.factoryOperations??=[];let o=s.factoryOperations.find(o=>o.factoryId===f.id);if(!o){o=initialOperations(f,s.week);s.factoryOperations.push(o);}return o;}
export function maintenancePolicy(s:V4State,p:{factoryId:string;policy:MaintenancePolicy},event:DomainEvent){const f=s.factories.find(f=>f.id===p.factoryId&&f.active&&Math.max(f.readyWeek??1,f.reactivationReadyWeek??1)<=s.week);if(!f||!['reactive','preventive','reliability'].includes(p.policy))throw Error('Choose an installed owned line and a disclosed maintenance policy.');const o=operating(s,f);o.policy=p.policy;event.entityIds=[f.id];event.details={factoryId:f.id,policy:p.policy};}
export function repairStation(s:V4State,p:{factoryId:string;station:StationId},event:DomainEvent){const f=s.factories.find(f=>f.id===p.factoryId&&f.active&&Math.max(f.readyWeek??1,f.reactivationReadyWeek??1)<=s.week),o=s.factoryOperations?.find(o=>o.factoryId===f?.id);if(!f||!o||!factoryStations.includes(p.station)||o.stations[p.station].condition>=100)throw Error('Choose an installed station with recorded wear.');const cost=Math.round(3000*f.stations[p.station].tier*(f.capacityScale??1));if(cost+protectedCash(s)>s.cashCents)throw Error('Station repair must preserve operating commitments.');post(s,event,'Paid station overhaul; owned station capacity is unchanged',[debit('maintenance',cost,f.id),credit('cash',cost)],'repair',{factoryId:f.id,regionId:regionForCity(f.cityId)});o.stations[p.station].condition=100;event.entityIds=[f.id,p.station];event.details={factoryId:f.id,station:p.station,costCents:cost};}
function chance(seed:number,week:number,factory:string,station:string,sample:number){let h=2166136261;for(const c of `${seed}:${week}:${factory}:${station}:${sample}`)h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;return h/4294967296;}
export function maintenanceCompetence(s:V4State,f:Factory){return Math.max(0,...s.employees.filter(e=>activeEmployee(e)&&e.factoryId===f.id&&e.contractedMinutes>=600).map(e=>e.skills.maintenance*(1-e.fatigue/500)*(s.training.some(t=>t.employeeId===e.id&&t.readyWeek>s.week)?.5:1)));}
export function prepareEquipmentOperations(s:V4State,event:DomainEvent,sample=0){const rows=[];for(const f of s.factories.filter(f=>f.active&&Math.max(f.readyWeek??1,f.reactivationReadyWeek??1)<=s.week)){const o=operating(s,f),competence=maintenanceCompetence(s,f),cost=equipmentOperatingCosts(f,o.policy),opening=structuredClone(o.stations);for(const id of factoryStations){const station=o.stations[id],risk=(o.policy==='reactive'?.01:.004)+Math.max(0,80-station.condition)/100*(1-competence/200),failed=chance(s.random.seed,s.week,f.id,id,sample)<risk,service=o.policy==='preventive'?.08:o.policy==='reliability'?.05:0,loss=service+(failed?Math.min(.65,.2+Math.max(0,70-station.condition)/100):0);station.availableMinutes=Math.max(0,Math.floor(f.stations[id].minutes*(1-loss)));station.downMinutes=f.stations[id].minutes-station.availableMinutes;}rows.push({factoryId:f.id,policy:o.policy,competence,...cost,opening,available:structuredClone(o.stations)});}event.details.equipmentOperationsOpening=JSON.stringify(rows);return rows;}
export function effectiveStationMinutes(s:V4State,f:Factory,station:StationId){return s.factoryOperations?.find(o=>o.factoryId===f.id)?.stations[station].availableMinutes??f.stations[station].minutes;}
export function closeEquipmentOperations(s:V4State,event:DomainEvent){for(const f of s.factories.filter(f=>f.active&&Math.max(f.readyWeek??1,f.reactivationReadyWeek??1)<=s.week)){const o=operating(s,f),competence=maintenanceCompetence(s,f),actual=s.lastProduction.find(p=>p.factoryId===f.id);for(const id of factoryStations){const used=actual?.stationUsedMinutes[id]??0,wear=used?Math.max(1,Math.ceil((.5+used/Math.max(1,f.stations[id].minutes)*5)*(1-competence/250))):0,restore=o.policy==='reactive'?0:o.policy==='preventive'?6:10;o.stations[id].condition=Math.min(100,Math.max(0,o.stations[id].condition-wear+restore));}}event.details.equipmentOperationsClosing=JSON.stringify(s.factoryOperations??[]);}
export function maintenanceFixed(s:V4State){return s.factories.filter(f=>f.active&&Math.max(f.readyWeek??1,f.reactivationReadyWeek??1)<=s.week).flatMap(f=>{const costs=equipmentOperatingCosts(f,s.factoryOperations?.find(o=>o.factoryId===f.id)?.policy??'reactive'),scope={factoryId:f.id,regionId:regionForCity(f.cityId)};return[{label:'Scheduled equipment maintenance',account:'maintenance' as const,amount:costs.maintenanceCents,entityId:f.id,scope},{label:'Installed station standing operation',account:'energy' as const,amount:costs.standingCents,entityId:'station-operation:'+f.id,scope}]});}
/** Bounded operating state and paid repair/policy sources; deeper campaign replay is a post-publication check. */
export function maintenanceStateErrors(s:V4State){const rows=s.factoryOperations??[];if(new Set(rows.map(o=>o.factoryId)).size!==rows.length)return['Duplicate factory operations'];for(const o of rows){const f=s.factories.find(f=>f.id===o.factoryId);if(!f||!Number.isSafeInteger(o.startedWeek)||o.startedWeek<1||o.startedWeek>s.week||!['reactive','preventive','reliability'].includes(o.policy)||factoryStations.some(id=>{const a=o.stations?.[id];return!a||![a.condition,a.availableMinutes,a.downMinutes].every(Number.isSafeInteger)||a.condition<0||a.condition>100||a.availableMinutes<0||a.availableMinutes>f.stations[id].minutes||a.downMinutes<0||a.downMinutes>f.stations[id].minutes;}))return['Invalid factory care or station availability'];}return[];}
