import {freightDestination} from './freight-destinations.ts';
import type {V4State,InventoryLot,DomainEvent} from './model.ts';import {catalog} from './catalog.ts';
const command=(e:DomainEvent)=>{try{return JSON.parse(e.signature)}catch{return {}}};
/** Procurement and movement actions authorize geography; snapshots report it. */
export function acquisitionLot(s:V4State,lotId:string):InventoryLot|undefined{const known=s.inventory.find(l=>l.id===lotId)??s.snapshots.flatMap(w=>w.inventory.lots).find(l=>l.id===lotId);if(known)return known;const source=s.events.find(e=>e.id+':lot'===lotId||e.id+':packaging'===lotId);if(!source)return;const c=command(source),variety=catalog.ingredients.find(i=>i.id===c.request?.varietyId);if(c.type==='purchase'&&variety)return {id:lotId,kind:'ingredient',varietyId:variety.id,locationId:c.request.warehouseId,quantity:c.request.quantityGrams,costCents:Number(source.details.totalCents),quality:65,condition:100,bornWeek:source.week,arrivalWeek:source.week,expiryWeek:source.week+variety.shelfWeeks-1,storageClass:variety.storageClass,reservations:[]};if(c.type==='purchase-packaging')return {id:lotId,kind:'packaging',packagingId:c.request.packagingId,locationId:c.request.warehouseId,quantity:c.request.quantityUnits,costCents:Number(source.details.goodsCents)+Number(source.details.freightCents),quality:65,condition:100,bornWeek:source.week,arrivalWeek:source.week,expiryWeek:source.week+207,storageClass:'dry',reservations:[]};}
export function physicalLocationEvidenceErrors(s:V4State){const errors:string[]=[],locations=new Map<string,{location:string;pending?:{id:string;warehouseId:string;due:number}}>(),snapshots=new Map(s.snapshots.map(w=>[w.tickId,w]));const cityAt=(id:string)=>s.warehouses.find(w=>w.id===id||'overflow:'+w.id===id)?.cityId??s.factories.find(f=>f.id===id)?.cityId??freightDestination(s,id)?.cityId;
 for(const e of s.events){const c=command(e);
  if(['purchase','purchase-packaging'].includes(e.type)){const supplier=catalog.suppliers.find(p=>p.id===c.request?.supplierId),warehouse=s.warehouses.find(w=>w.id===c.request?.warehouseId);if(!supplier||!warehouse){errors.push('Acquisition requires a documented physical receiving source');continue;}const packaging=e.type==='purchase-packaging',lead=Number(e.details.routeWeeks??supplier.leadWeeks),lotId=e.id+(packaging?':packaging':':lot'),shipmentId=e.id+(packaging?':freight':':shipment');locations.set(lotId,{location:lead?'transit:'+shipmentId:warehouse.id,...(lead?{pending:{id:shipmentId,warehouseId:warehouse.id,due:e.week+lead}}:{})});}
  if(e.type==='transfer-lot'){const source=locations.get(c.lotId),to=s.warehouses.find(w=>w.id===c.toLocationId)??s.factories.find(f=>f.id===c.toLocationId);if(!source||source.pending||!to||cityAt(source.location)!==to.cityId)errors.push('Local handling differs from actual stock geography');else source.location=c.toLocationId;}
  if(e.type==='ship-lot'){const source=locations.get(c.lotId),to=freightDestination(s,c.warehouseId);if(!source||source.pending||!to||cityAt(source.location)!==e.details.originCityId){errors.push('Transport lacks its actual physical departure source');continue;}const nearby=!!c.express||['sf','oakland'].includes(cityAt(source.location)!)&&['sf','oakland'].includes(to.cityId);source.location=nearby?to.id:'transit:'+e.id+':shipment';source.pending=nearby?undefined:{id:e.id+':shipment',warehouseId:to.id,due:e.week+1};}
  if(e.origin==='tick'){const snap=snapshots.get(e.id);if(!snap)continue;
   for(const [id,source]of locations){if(!source.pending)continue;const shipment=snap.inventory.shipments.find(sh=>sh.id===source.pending!.id),actual=snap.inventory.lots.find(l=>l.id===id);if(shipment?.status==='arrived'){if(snap.week<source.pending.due||shipment.warehouseId!==source.pending.warehouseId)errors.push('Receiving precedes the documented transport route');const overflow=actual?.locationId==='overflow:'+source.pending.warehouseId;if(overflow&&!s.ledger.some(l=>l.eventId===e.id&&l.id===e.id+':'+source.pending!.id+'-overflow'&&l.postings.some(p=>p.account==='rent'&&p.debitCents===10000)))errors.push('Overflow stock requires its dated handling payment');source.location=overflow?'overflow:'+source.pending.warehouseId:source.pending.warehouseId;delete source.pending;}}
   for(const production of snap.production){const factory=s.factories.find(f=>f.id===production.factoryId),warehouse=s.warehouses.find(w=>w.cityId===factory?.cityId);if(!warehouse){errors.push('Produced goods require their documented local receiving site');continue;}production.rows.forEach((row,i)=>{if(row.goodCases>0)locations.set(e.id+':'+production.factoryId+':'+i,{location:warehouse.id});});}
   for(const lot of snap.inventory.lots){if(locations.get(lot.id)?.location!==lot.locationId)errors.push('Historical stock location differs from procurement, transport and receiving');}
   const live=new Set(snap.inventory.lots.map(l=>l.id));for(const id of locations.keys())if(!live.has(id))locations.delete(id);
  }
 }
 for(const lot of s.inventory)if(locations.get(lot.id)?.location!==lot.locationId)errors.push('Current stock location differs from dated physical movements');return [...new Set(errors)];}
