import type {FranchiseCohort,FranchiseStandard,FranchiseActual,RecipeRevision,PartnerStock} from './model.ts';
import type {FranchisePartner} from './content/franchise-partners.ts';
import {catalog} from './catalog.ts';
import {packagingFamilies} from './content/packaging.ts';
import {partnerPurchase,type PartnerProcurementContext} from './partner-procurement.ts';

export interface PartnerWeekContext extends PartnerProcurementContext {seed:number;tickId:string;revisions:RecipeRevision[];supportedStores:number;supportCents:number;sample?:number;brandFactor?:number;serviceModel?:2|3|4|5;centralProcurementCents?:number}
function noise(seed:number,week:number,id:string,sample?:number){let n=(seed^week)>>>0;for(const c of id+':'+(sample===undefined?'actual':sample))n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;return .8+(n%401)/1000;}
function stockItem(l:PartnerStock){return l.kind==='ingredient'?l.varietyId:l.kind==='finished'?l.recipeRevisionId:l.packagingId;}
function eligible(c:FranchiseCohort,kind:PartnerStock['kind'],id:string,week:number){return c.stock.filter(l=>l.kind===kind&&stockItem(l)===id&&l.arrivalWeek<=week&&l.expiryWeek>=week&&l.quantity>0).sort((a,b)=>a.expiryWeek-b.expiryWeek||a.id.localeCompare(b.id));}
function take(c:FranchiseCohort,kind:PartnerStock['kind'],id:string,quantity:number,week:number,minimumQuality=0){const consumed:{stockId:string;quantity:number;costCents:number;quality:number}[]=[];for(const l of eligible(c,kind,id,week).filter(l=>l.quality>=minimumQuality)){const q=Math.min(quantity,l.quantity);if(!q)continue;const costCents=q===l.quantity?l.costCents:Math.floor(l.costCents*q/l.quantity);l.quantity-=q;l.costCents-=costCents;quantity-=q;consumed.push({stockId:l.id,quantity:q,costCents,quality:l.quality});if(!quantity)break;}if(quantity)throw Error('Partner production cannot consume unavailable physical stock.');return consumed;}

/** Separate third-party working capital and physical FEFO production. Only
 * the caller's paid support, earned license service and collected royalty
 * are eligible for the group journal. Local cash/turnover never becomes it. */
export function operatePartner(input:FranchiseCohort,standard:FranchiseStandard,partner:FranchisePartner,context:PartnerWeekContext){
 const c=structuredClone(input),row:FranchiseActual={cohortId:c.id,partnerId:partner.id,cityId:partner.cityId,supportedStores:context.supportedStores,supportCents:context.supportCents,openingCashCents:c.partnerCashCents+(context.centralProcurementCents??0),closingCashCents:0,trainingCompletedWeeks:c.trainingCompletedWeeks,partnerRevenueCents:0,partnerCogsCents:0,partnerFixedCents:partner.fixedPerStoreCents*c.stores,partnerFixedPaidCents:0,closingPartnerArrearsCents:0,partnerProcurementCents:context.centralProcurementCents??0,partnerExpiryCents:0,royaltyCents:0,feeEarnedCents:0,feeRemainingCents:c.feeRemainingCents,serviceWeeks:c.serviceWeeks,compliant:false,exception:'',purchases:[],recipes:[],closingStock:[],stores:[]};
 const fullSupport=context.supportedStores===c.stores&&!c.paused,requiredTraining=standard.trainingWeeks+c.extraTrainingWeeks,training=c.trainingCompletedWeeks<requiredTraining;
 if(c.paused)row.exception='Trading and training are paused; partner premises obligations continue.';
 else if(!fullSupport)row.exception='Opening/trading stopped: this cohort lacks complete paid regional support coverage.';
 else if(training){c.trainingCompletedWeeks++;row.trainingCompletedWeeks=c.trainingCompletedWeeks;row.exception='Actual paid operating-standard training is in progress.';}
 const revisions=standard.assortment.map(id=>context.revisions.find(r=>r.id===id)!).filter(Boolean),yearWeek=(context.week-1)%52+1,season=yearWeek>=partner.peakWeeks[0]&&yearWeek<=partner.peakWeeks[1]?partner.giftingPeak:1,catchment=1-.35*Math.max(0,c.stores/partner.maximumStores-.5),priceAppeal=Math.max(.08,Math.min(1.3,Math.exp(-(c.priceFactorBps/10000-1)*1.5))),planned=Math.floor(partner.casesPerStore*c.stores*catchment*season*priceAppeal*(context.brandFactor??1)),requirements=new Map<string,{kind:PartnerStock['kind'];id:string;quantity:number;minimumQuality:number}>();
 const trainedSkill=(weeks:number)=>Math.min(96,partner.operatingSkill+weeks*1.5*Math.min(2,standard.weeklySupportCents/4500)),qualityFloor=(weeks:number)=>Math.max(0,Math.ceil((standard.minimumQuality-trainedSkill(weeks)*.45)/.55));
 // Replenishment includes lead-time pipeline, so a partner cannot buy the
 // same future lot every close. Training weeks prepare physical supply.
 if(fullSupport&&standard.supply==='local'){
  for(const revision of revisions){const recipe=catalog.recipes.find(r=>r.id===revision.recipeId)!,targetCases=Math.ceil(planned/Math.max(1,revisions.length))*4;for(const role of recipe.roles){const id=revision.formula[role.role],key='ingredient:'+id,p= requirements.get(key)??{kind:'ingredient' as const,id,quantity:0,minimumQuality:0};p.minimumQuality=Math.max(p.minimumQuality,role.minimumQuality,qualityFloor(Math.max(c.trainingCompletedWeeks,requiredTraining)));p.quantity+=targetCases*role.gramsPerCase;requirements.set(key,p);}const key='packaging:'+revision.packagingId,p=requirements.get(key)??{kind:'packaging' as const,id:revision.packagingId,quantity:0,minimumQuality:0};p.quantity+=targetCases*20;requirements.set(key,p);}
  for(const original of requirements.values()){const item={...original},weekly=original.quantity/4;let reorder=item.quantity*.5;if(context.serviceModel===4||context.serviceModel===5){const cash=Math.max(0,c.partnerCashCents-row.partnerFixedCents*2-c.partnerArrearsCents),quotes=context.allowedSupplierIds.map(supplierId=>partnerPurchase({...context,allowedSupplierIds:[supplierId],grade:c.grade,minimumQuality:item.minimumQuality},item.kind,item.id,item.quantity,cash,context.tickId+':lead-preview')).filter(Boolean),lead=Math.max(0,...quotes.map(q=>q!.stock.arrivalWeek-context.week));item.quantity=Math.ceil(weekly*(Math.ceil(lead*1.2)+4));reorder=Math.ceil(weekly*(Math.ceil(lead*1.2)+2));}let held=c.stock.filter(l=>l.kind===item.kind&&stockItem(l)===item.id&&l.expiryWeek>=context.week&&l.quality>=item.minimumQuality).reduce((n,l)=>n+l.quantity,0);if(held>=reorder)continue;
   // New closes can split a large replenishment across actual discovered
   // offers. Version2 retains its original one-offer procurement history.
   const attempts=(context.serviceModel===3||context.serviceModel===4||context.serviceModel===5)?context.allowedSupplierIds.length:1;
   for(let attempt=0;attempt<attempts&&held<item.quantity;attempt++){const cash=Math.max(0,c.partnerCashCents-row.partnerFixedCents*2-c.partnerArrearsCents),q=partnerPurchase({...context,grade:c.grade,minimumQuality:item.minimumQuality},item.kind,item.id,item.quantity-held,cash,context.tickId+':'+c.id+((context.serviceModel===3||context.serviceModel===4||context.serviceModel===5)?':split:'+attempt:''));if(!q)break;c.stock.push(q.stock);c.partnerCashCents-=q.goodsCents+q.freightCents;row.partnerProcurementCents+=q.goodsCents+q.freightCents;row.purchases.push(structuredClone(q));held+=q.stock.quantity;const key=q.stock.kind+':'+q.stock.supplierId+':'+(q.stock.kind==='packaging'&&context.sharedPackagingCapacity?'*':stockItem(q.stock));context.used.set(key,(context.used.get(key)??0)+q.stock.quantity);}
  }
 }
 const actualDemand=Math.floor(planned*noise(context.seed,context.week,c.id,context.sample));
 if((context.serviceModel===2||context.serviceModel===3||context.serviceModel===4||context.serviceModel===5)){row.demandCases=training||c.paused?0:Math.floor(actualDemand/Math.max(1,revisions.length))*revisions.length;row.soldCases=0;row.unservedCases=row.demandCases;row.viable=false;}
 if(fullSupport&&!training&&standard.supply==='local'){
  let laborRemaining=c.stores*2400;const skill=trainedSkill(c.trainingCompletedWeeks),demand=actualDemand;
  for(const revision of revisions){const recipe=catalog.recipes.find(r=>r.id===revision.recipeId)!,pack=packagingFamilies.find(p=>p.id===revision.packagingId)!;let cases=Math.floor(demand/Math.max(1,revisions.length));const mass=new Map<string,{grams:number;minimumQuality:number}>();for(const role of recipe.roles){const id=revision.formula[role.role],prior=mass.get(id)??{grams:0,minimumQuality:0};prior.grams+=role.gramsPerCase;prior.minimumQuality=Math.max(prior.minimumQuality,role.minimumQuality,qualityFloor(c.trainingCompletedWeeks));mass.set(id,prior);}for(const [id,required]of mass){const lots=eligible(c,'ingredient',id,context.week).filter(l=>l.quality>=required.minimumQuality);cases=Math.min(cases,Math.floor(lots.reduce((n,l)=>n+l.quantity,0)/required.grams));}cases=Math.min(cases,Math.floor(eligible(c,'packaging',pack.id,context.week).reduce((n,l)=>n+l.quantity,0)/20));const laborMinutes=recipe.operations.reduce((n,o)=>n+o.laborMinutesPerCase,0)+pack.packingExtraMinutesPerCase;cases=Math.min(cases,Math.floor(laborRemaining/Math.max(1,laborMinutes)));if(cases<1)continue;
   const trial=structuredClone(c),inputs=recipe.roles.map(role=>({role,used:take(trial,'ingredient',revision.formula[role.role],role.gramsPerCase*cases,context.week,mass.get(revision.formula[role.role])!.minimumQuality)})),weightedQuality=inputs.reduce((n,{role,used})=>n+used.reduce((m,l)=>m+l.quantity*l.quality,0)/(role.gramsPerCase*cases)*role.qualityWeight,0),totalWeight=recipe.roles.reduce((n,r)=>n+r.qualityWeight,0),quality=Math.min(100,weightedQuality/Math.max(1,totalWeight)*.55+skill*.45);
   if(quality<standard.minimumQuality){row.exception='Quality hold: local ingredients and trained kitchen skill do not meet the signed standard.';continue;}
   const consumed=inputs.flatMap(i=>i.used),packing=take(trial,'packaging',pack.id,cases*20,context.week),good=Math.floor(cases*Math.min(.98,.90+skill/1000)),priceCents=Math.round(recipe.referencePriceCents*c.priceFactorBps/10000),materialCents=consumed.reduce((n,r)=>n+r.costCents,0),packagingCents=packing.reduce((n,r)=>n+r.costCents,0),sale={recipeRevisionId:revision.id,inputCases:cases,soldCases:good,quality,priceCents,materialCents,packagingCents,consumed:consumed.map(r=>({stockId:r.stockId,quantityGrams:r.quantity,costCents:r.costCents})),packagingConsumed:packing.map(r=>({stockId:r.stockId,quantityUnits:r.quantity,costCents:r.costCents}))};c.stock=trial.stock;laborRemaining-=cases*laborMinutes;row.recipes.push(sale);row.partnerRevenueCents+=good*priceCents;row.partnerCogsCents+=materialCents+packagingCents;c.partnerCashCents+=good*priceCents;
  }
  }else if(fullSupport&&!training&&standard.supply==='central'){
  for(const revision of revisions){const recipe=catalog.recipes.find(r=>r.id===revision.recipeId)!,demand=Math.floor(actualDemand/Math.max(1,revisions.length)),stock=eligible(c,'finished',revision.id,context.week).filter(l=>l.quality>=standard.minimumQuality),cases=Math.min(demand,stock.reduce((n,l)=>n+l.quantity,0));if(!cases)continue;const inputs=take(c,'finished',revision.id,cases,context.week,standard.minimumQuality),quality=inputs.reduce((n,l)=>n+l.quantity*l.quality,0)/cases,priceCents=Math.round(recipe.referencePriceCents*c.priceFactorBps/10000),cost=inputs.reduce((n,l)=>n+l.costCents,0);row.recipes.push({recipeRevisionId:revision.id,inputCases:cases,soldCases:cases,quality,priceCents,materialCents:cost,packagingCents:0,consumed:[],finishedConsumed:inputs.map(l=>({stockId:l.stockId,quantityCases:l.quantity,costCents:l.costCents})),packagingConsumed:[]});row.partnerRevenueCents+=cases*priceCents;row.partnerCogsCents+=cost;c.partnerCashCents+=cases*priceCents;}
 }
 // Royalties are split from earned till receipts under the signed terms,
 // before the operator settles its own rent/team obligations.
 if(row.partnerRevenueCents){row.royaltyCents=Math.floor(row.partnerRevenueCents*standard.royaltyBps/10000);c.partnerCashCents-=row.royaltyCents;}
 const fixedDue=row.partnerFixedCents+c.partnerArrearsCents;row.partnerFixedPaidCents=Math.min(c.partnerCashCents,fixedDue);c.partnerCashCents-=row.partnerFixedPaidCents;c.partnerArrearsCents=fixedDue-row.partnerFixedPaidCents;
 if((context.serviceModel===2||context.serviceModel===3||context.serviceModel===4||context.serviceModel===5)){row.soldCases=row.recipes.reduce((n,r)=>n+r.soldCases,0);row.unservedCases=Math.max(0,row.demandCases!-row.soldCases);row.viable=row.partnerRevenueCents-row.partnerCogsCents-row.partnerExpiryCents-row.royaltyCents-row.partnerFixedCents>0;if(row.partnerRevenueCents)c.openedWeek??=context.week;if(fullSupport&&!training&&row.soldCases<row.demandCases!*.8&&!row.exception)row.exception='Service hold: actual supply cannot serve at least 80% of district demand.';}
 row.compliant=fullSupport&&!training&&!c.partnerArrearsCents&&row.partnerRevenueCents>0&&!row.exception&&row.royaltyCents===Math.floor(row.partnerRevenueCents*standard.royaltyBps/10000);
 if(row.compliant){c.openedWeek??=context.week;c.compliantWeeks++;if(c.serviceWeeks<standard.feeEarningWeeks){const total=standard.openingFeeCents*c.stores,next=c.serviceWeeks+1;row.feeEarnedCents=Math.floor(total*next/standard.feeEarningWeeks)-Math.floor(total*c.serviceWeeks/standard.feeEarningWeeks);c.serviceWeeks=next;c.feeRemainingCents-=row.feeEarnedCents;}}
 if(fullSupport&&!training&&!row.partnerRevenueCents&&!row.exception)row.exception='No eligible physical stock reached these kitchens; keep promises within actual supply.';
 if(c.partnerArrearsCents)row.exception='Partner working capital cannot pay its own premises/team obligations.';
 for(const l of c.stock.filter(l=>l.expiryWeek<=context.week)){row.partnerExpiryCents+=l.costCents;l.quantity=0;l.costCents=0;}
 c.stock=c.stock.filter(l=>l.quantity>0);c.exception=row.exception;row.closingCashCents=c.partnerCashCents;row.closingPartnerArrearsCents=c.partnerArrearsCents;row.feeRemainingCents=c.feeRemainingCents;row.serviceWeeks=c.serviceWeeks;row.closingStock=structuredClone(c.stock);row.stores=Array.from({length:c.stores},(_,i)=>({id:c.id+':store:'+i,name:partner.districts[i]??partner.name+' district '+(i+1),status:c.paused||!fullSupport?'paused' as const:training?'training' as const:row.partnerRevenueCents>0?'operating' as const:'paused' as const,exception:row.exception}));
 if((context.serviceModel===2||context.serviceModel===3||context.serviceModel===4||context.serviceModel===5)){row.viable=row.partnerRevenueCents-row.partnerCogsCents-row.partnerExpiryCents-row.royaltyCents-row.partnerFixedCents>0;row.stores=row.stores.map((store,i)=>{const demandCases=Math.floor(row.demandCases!/c.stores)+(i<row.demandCases!%c.stores?1:0),soldCases=Math.floor(row.soldCases!/c.stores)+(i<row.soldCases!%c.stores?1:0),compliant=fullSupport&&!training&&!c.partnerArrearsCents&&demandCases>0&&soldCases>=demandCases*.8;return {...store,demandCases,soldCases,compliant,status:training&&fullSupport?'training':compliant?'operating':'paused',exception:compliant?'':row.exception||'District service is below its actual demand.'};});}
 return {cohort:c,row};
}
