import type {V4State,DomainEvent,Employee,CohortTeam} from './model.ts';
export interface WorkforceOutcome {id:string;kind:'person'|'team';overworkWeeks:number;unpaidWeeks:number;departure:boolean;leavers:number;morale?:number;reason:string}
export function workforceRows(e:DomainEvent|undefined):WorkforceOutcome[]{try{return JSON.parse(String(e?.details.workforceActuals??'[]'));}catch{return [];}}
/** Visible, deterministic retention: two warnings precede a third consecutive
 * excessive close. Rest/paid payroll resets the streak. No random departures. */
export function workforceOutcomes(s:V4State,e:DomainEvent,people:Employee[],teams:CohortTeam[]):WorkforceOutcome[]{
 const prior=s.events.slice(0,s.events.indexOf(e)<0?s.events.length:s.events.indexOf(e)),last=prior.findLast(e=>e.origin==='tick'),previous=workforceRows(last),hours=JSON.parse(String(e.details.overtimeActuals??'[]')) as {employeeId:string;workedMinutes:number;closingFatigue:number}[];
 const unpaid=(id:string)=>s.ledger.some(j=>j.eventId===e.id&&j.postings.some(p=>p.account==='payroll'&&p.entityId===id&&p.debitCents>0)&&j.postings.some(p=>p.account==='arrears'&&p.creditCents>0));
 const previousFor=(id:string)=>{const reset=prior.slice(last?prior.indexOf(last)+1:0).some(p=>p.type==='rehire-employee'&&p.entityIds.includes(id)||p.type==='configure-team'&&p.entityIds.includes(id));return reset?undefined:previous.find(p=>p.id===id);};
 const rows:WorkforceOutcome[]=people.filter(p=>p.departedWeek===undefined).map(p=>{const old=previousFor(p.id),worked=hours.find(h=>h.employeeId===p.id),overworkWeeks=worked&&worked.workedMinutes>0&&worked.closingFatigue>=60?(old?.overworkWeeks??0)+1:0,unpaidWeeks=unpaid(p.id)?(old?.unpaidWeeks??0)+1:0,departure=overworkWeeks>=3||unpaidWeeks>=3;return{id:p.id,kind:'person',overworkWeeks,unpaidWeeks,departure,leavers:departure?1:0,reason:overworkWeeks?'Sustained overtime at fatigue60+':unpaidWeeks?'Repeated unpaid payroll':''};});
 for(const t of teams.filter(t=>t.headcount>0)){const old=previousFor(t.id),unpaidWeeks=unpaid(t.id)?(old?.unpaidWeeks??0)+1:0,morale=unpaidWeeks?Math.max(0,t.morale-12):Math.min(85,t.morale+4),leavers=unpaidWeeks>=3&&morale<60?Math.max(1,Math.ceil(t.headcount*.1)):0;rows.push({id:t.id,kind:'team',overworkWeeks:0,unpaidWeeks,departure:leavers>0,leavers,morale,reason:unpaidWeeks?'Repeated unpaid team payroll':''});}
 return rows;
}
export function applyWorkforceRows(people:Employee[],teams:CohortTeam[],rows:WorkforceOutcome[],week:number){for(const r of rows){if(r.kind==='person'&&r.departure){const p=people.find(p=>p.id===r.id);if(p)p.departedWeek=week;}if(r.kind==='team'){const t=teams.find(t=>t.id===r.id);if(t){t.headcount=Math.max(0,t.headcount-r.leavers);t.morale=r.morale!;}}}}
export function resolveWorkforce(s:V4State,e:DomainEvent){const rows=workforceOutcomes(s,e,s.employees,s.cohortTeams??[]);applyWorkforceRows(s.employees,s.cohortTeams??[],rows,s.week);e.details.workforceTerms=1;e.details.workforceActuals=JSON.stringify(rows);return rows.filter(r=>r.reason||r.departure).map(r=>{const p=s.employees.find(p=>p.id===r.id),name=p?.name??r.id;return r.departure?`${name}: ${r.leavers} colleague${r.leavers===1?'':'s'} departed after three unresolved closes. Replace leadership or fund returning staff; payroll arrears remain owed.`:`${name}: retention warning (${Math.max(r.overworkWeeks,r.unpaidWeeks)}/3). ${r.reason}. Rest, staffing or paid payroll prevents departure.`;});}
/** Full row replay runs within overtimeEvidenceErrors' existing single staff
 * pass. This boundary check preserves old closes and requires continuity. */
export function workforceEvidenceErrors(s:V4State){const errors:string[]=[],first=s.events.findIndex(e=>e.details.workforceTerms!==undefined);for(const [i,e]of s.events.entries()){if(e.origin!=='tick')continue;if(e.details.workforceActuals!==undefined&&e.details.workforceTerms!==1||first>=0&&i>=first&&e.details.workforceTerms!==1)errors.push('Missing dated workforce retention terms');}return errors;}
