import {catalog} from './catalog.ts';
export type RegionalInterior='production'|'showroom'|'warehouse'|'lab'|'office'|'partner';
export interface DistrictPlan {surface:string;facade:string;glass:string;accent:string;character:'industrial'|'retail'|'craft'|'river'|'garden'|'market'|'coast'|'promenade'|'metropolis'|'campus'|'logistics';neighborhoods:[string,string];sites:[number,number,RegionalInterior][];}
/** Positions are authored for commercial routes, not geographical replicas. */
export const districtPlans:Record<string,DistrictPlan>={
 oakland:{surface:'#c9c4ad',facade:'#c8d0c6',glass:'#527a83',accent:'#b77245',character:'industrial',neighborhoods:['Production campus','Loading & training'],sites:[[-7,0,'production'],[7,-6,'warehouse'],[-8,-19,'warehouse'],[7,-22,'office']]},
 paris:{surface:'#dfd7bd',facade:'#e6dfcd',glass:'#456875',accent:'#a97755',character:'retail',neighborhoods:['Collection quarter','Import & flagship court'],sites:[[-6,-1,'showroom'],[6,-6,'showroom'],[-6,-21,'warehouse'],[6,-24,'showroom'],[-6,-36,'production']]},
 turin:{surface:'#cfc6b4',facade:'#ba9780',glass:'#426d74',accent:'#a5673f',character:'craft',neighborhoods:['Technical court','Makers & trade'],sites:[[-7,0,'production'],[7,-4,'lab'],[-7,-18,'warehouse'],[7,-19,'lab']]},
 guayaquil:{surface:'#d1c9ad',facade:'#d9e1cd',glass:'#41766e',accent:'#b9854c',character:'river',neighborhoods:['River export district','Grower logistics'],sites:[[-7,0,'warehouse'],[4,-8,'warehouse'],[-8,-19,'office'],[4,-25,'lab']]},
 kyoto:{surface:'#d5d2bb',facade:'#d7d8cd',glass:'#496c65',accent:'#997852',character:'garden',neighborhoods:['Contemporary confectioners','Tea & technique garden'],sites:[[-7,-1,'lab'],[7,-4,'warehouse'],[-7,-18,'showroom'],[7,-20,'lab']]},
 oaxaca:{surface:'#d4bca0',facade:'#c4a891',glass:'#436d68',accent:'#a75f46',character:'market',neighborhoods:['Craft-market court','Cocoa & harvest street'],sites:[[-8,0,'showroom'],[7,-3,'lab'],[-7,-18,'warehouse'],[7,-19,'showroom']]},
 salvador:{surface:'#d9cfaf',facade:'#e1d4b6',glass:'#3e7883',accent:'#c3964c',character:'coast',neighborhoods:['Coastal trade quay','Inland receiving court'],sites:[[-7,0,'warehouse'],[4,-8,'warehouse'],[-8,-19,'warehouse'],[4,-25,'showroom']]},
 istanbul:{surface:'#d6d3c6',facade:'#cccdc4',glass:'#344e57',accent:'#b38454',character:'promenade',neighborhoods:['Gift promenade','Trade & distribution court'],sites:[[-7,0,'showroom'],[4,-7,'warehouse'],[-8,-20,'office'],[4,-25,'warehouse']]},
 mumbai:{surface:'#cbc9b9',facade:'#d1d7d1',glass:'#436d7e',accent:'#bb8546',character:'metropolis',neighborhoods:['Commercial avenue','Fulfillment quarter'],sites:[[-8,0,'showroom'],[7,-2,'warehouse'],[-7,-18,'warehouse'],[7,-21,'showroom']]},
 accra:{surface:'#d0b69a',facade:'#bd9578',glass:'#4f7772',accent:'#a96a45',character:'campus',neighborhoods:['Trading campus','Partner & support court'],sites:[[-8,0,'warehouse'],[7,-4,'partner'],[-7,-18,'office'],[7,-19,'warehouse']]},
 singapore:{surface:'#ced4c7',facade:'#d8ded7',glass:'#437984',accent:'#b89c58',character:'logistics',neighborhoods:['Regional logistics','Flagship & executive court'],sites:[[-8,0,'warehouse'],[7,-3,'warehouse'],[-7,-19,'showroom'],[7,-21,'office']]},
};
export function regionalPlaces(cityId:string){const city=catalog.cities.find(c=>c.id===cityId),plan=districtPlans[cityId];if(!city||!plan)return [];return city.hotspots.map((id,i)=>({id,label:id.replaceAll('-',' ').replace(/^./,x=>x.toUpperCase()),contact:city.contact,kind:plan.sites[i][2],position:[plan.sites[i][0],3.6,plan.sites[i][1]] as [number,number,number],area:i<2?0:1}));}
export const regionalInteriorActions:Record<RegionalInterior,string[]>={production:['production','machines','staff','inventory','research','dispatch'],showroom:['collection','buyer','commercial','display'],warehouse:['supplier','stock','freight','market'],lab:['research','technique','brief','staff'],office:['reports','campaign','people','delegation'],partner:['partners','standards','support','reports']};
export function regionalDestination(cityId:string){const city=catalog.cities.find(c=>c.id===cityId)!,plan=districtPlans[cityId];return {name:city.name,region:city.geography,areas:plan.neighborhoods.map((name,i)=>({id:i?'operations':'street',name,description:i?city.interior+' · '+city.contact:'Explore the local commercial district and its contacts.',target:[0,2,i?-19:0] as [number,number,number]}))};}
