import {franchisePartners} from './content/franchise-partners.ts';
import type{V4State}from'./model.ts';import{catalog}from'./catalog.ts';import{regionalPlaces}from'./world-routes.ts';
/** Resolve report entity identity into a real local door, preserving paid travel. */
export function worldSourceRoute(s:V4State,id:string){const factory=s.factories.find(f=>f.id===id),warehouse=s.warehouses.find(w=>w.id===id),supplier=catalog.suppliers.find(p=>p.id===id),channel=s.consumerChannels?.find(c=>c.id===id),contract=s.contracts.find(c=>c.id===id),city=catalog.cities.find(c=>c.id===id),cohort=s.franchiseCohorts?.find(c=>c.id===id||c.id===s.franchiseSupplyOrders?.find(o=>o.id===id)?.cohortId),partner=franchisePartners.find(p=>p.id===(cohort?.partnerId??id)),hub=s.franchiseSupportHubs?.find(h=>h.id===id),cityId=partner?.cityId??hub?.cityId??factory?.cityId??warehouse?.cityId??supplier?.cityId??channel?.cityId??contract?.cityId??city?.id??(id==='office'||['sf-storage','sf-workshop','rafi-pantry','ferry-cafe','workshop'].includes(id)?'sf':s.currentCityId),content=catalog.cities.find(c=>c.id===cityId)!;let locationId=id;
 if(partner||hub)locationId=cityId==='sf'?'office':regionalPlaces(cityId).find(p=>p.kind==='partner')?.id??regionalPlaces(cityId).find(p=>p.kind==='office')?.id??content.hotspots[0];
 else if(factory)locationId=cityId==='sf'?'workshop':content.hotspots.includes('production-site')?'production-site':regionalPlaces(cityId).find(p=>p.kind==='production')?.id??regionalPlaces(cityId).find(p=>p.kind==='warehouse')?.id??content.hotspots[0];
 else if(channel)locationId=cityId==='sf'?(channel.kind==='owned-retail'?'flagship':'office'):channel.kind==='ecommerce'?content.hotspots.find(p=>p.includes('fulfillment'))??regionalPlaces(cityId).find(p=>p.kind==='warehouse')?.id??content.hotspots[0]:content.hotspots.find(p=>p==='flagship')??regionalPlaces(cityId).find(p=>p.kind==='showroom')?.id??content.hotspots[0];
 else if(warehouse||supplier)locationId=cityId==='sf'?(supplier?'rafi-pantry':'workshop'):regionalPlaces(cityId).find(p=>p.kind==='warehouse')?.id??content.hotspots[0];
 else if(contract||city)locationId=cityId==='sf'?'ferry-cafe':content.hotspots.find(p=>p.includes('buyer'))??content.hotspots[0];
 if(!content.hotspots.includes(locationId))locationId=cityId==='sf'?'office':content.hotspots[0];return{cityId,locationId,consumer:!!channel,...(partner||hub?{franchise:true}:{})};}
