import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,ChevronRight,Compass,Globe2,Mail,Menu,X,Play,BookOpen,Volume2,VolumeX,Factory,Package,Users,Landmark,Newspaper,FlaskConical,Check,Download,Upload,HelpCircle,Settings} from 'lucide-react';
import * as E from '../game/engine';
import type {State,Action,FactoryId,RecipeId} from '../game/engine';
import V3World from './world/V3World';
import FactoryPanel from './v3/FactoryPanel';
import {SupplyPanel,OrdersPanel,MarketsPanel,ResearchPanel,AccountsPanel,ManagersPanel,ReportPanel,NewsPanel,Metrics} from './v3/CommercePanels';
import {TravelMap,Discovery,AcquireFactory,CITY_NAMES} from './v3/WorldPanels';
import './v3/app.css';
import './v3/fonts.css';
const SAVE='cacao-house-save-v2',BACKUP=SAVE+'-backup';
function savedItem(key:string){try{return localStorage.getItem(key)}catch{return null}}
type Panel={id:string;detail?:string};
type Section='production'|'people'|'equipment'|'inventory'|'standards';
function boot(){try{const raw=localStorage.getItem(SAVE);if(raw){const s=E.deserialize(raw);if(JSON.parse(raw).version<6&&!localStorage.getItem('cacao-house-pre-v3'))localStorage.setItem('cacao-house-pre-v3',raw);return {s,loaded:true,error:''};}}catch{try{const raw=localStorage.getItem(BACKUP);if(raw)return {s:E.deserialize(raw),loaded:true,error:'Your last good backup has been restored.'};}catch{}return {s:E.newGame(),loaded:false,error:'The saved house could not be read. The original save has been preserved; use Settings to import a good copy.'};}return {s:E.newGame(),loaded:false,error:''};}
function Sheet({title,context,onClose,children,wide=false,navigation}:{title:string;context?:string;onClose:()=>void;children:ReactNode;wide?:boolean;navigation?:ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const prior=document.activeElement as HTMLElement|null;ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const els=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea,a[href],[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus?.();};},[]);return <div className="v3-sheet-layer"><button tabIndex={-1} className="v3-scrim" aria-label="Return to world" onClick={onClose}/><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`v3-sheet ${wide?'wide':''}`}><header className="v3-sheet-head"><div>{context&&<small>{context}</small>}<h2>{title}</h2></div><button className="v3-icon" onClick={onClose} aria-label="Close panel"><X size={20}/></button></header>{navigation}<div className="v3-sheet-body">{children}</div></section></div>}
const placeForFactory=(id:FactoryId)=>E.factoryPlace(id);
const factoryForPlace=(id:string):FactoryId|null=>id==='sf'?'quay':id==='oakland'?'riverside':id==='turin'?'northline':null;
export default function App(){
 const initial=useRef<ReturnType<typeof boot>|null>(null);if(!initial.current)initial.current=boot();
 const [s,setS]=useState(initial.current.s),ref=useRef(s);ref.current=s;
 const [legacyInfo,setLegacyInfo]=useState(initial.current.loaded&&!initial.current.s.v3.enabled&&!savedItem('cacao-house-v3-introduced'));
 function dismissLegacy(){setLegacyInfo(false);try{localStorage.setItem('cacao-house-v3-introduced','yes')}catch{}}
 const [sceneArea,setSceneArea]=useState<string|undefined>();
 const [panel,setPanel]=useState<Panel|null>(null),[interior,setInterior]=useState(false),[factory,setFactory]=useState<FactoryId>(factoryForPlace(s.travel.location)||'quay'),[section,setSection]=useState<Section>('production');
 const [welcome,setWelcome]=useState(!initial.current.loaded),[message,setMessage]=useState(initial.current.error),[saved,setSaved]=useState(true),[busy,setBusy]=useState(false),[sound,setSound]=useState(false),[highlight,setHighlight]=useState<string|undefined>(),[booking,setBooking]=useState<E.Destination|'sf'|null>(null),[result,setResult]=useState(false),[restart,setRestart]=useState(false),[founder,setFounder]=useState(s.v3.identity.founder),[business,setBusiness]=useState(s.v3.identity.business),[crest,setCrest]=useState(s.v3.identity.crest),[nameForm,setNameForm]=useState(false);
 const file=useRef<HTMLInputElement>(null),lock=useRef(false),audio=useRef<AudioContext|null>(null),timer=useRef<number|undefined>(undefined);
 function announce(text:string){setMessage(text);window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setMessage(''),5500);}
 function chime(){if(!sound)return;try{const Constructor=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;const a=audio.current||(audio.current=new Constructor());void a.resume();[392,493.88,587.33].forEach((freq,i)=>{const oscillator=a.createOscillator(),gain=a.createGain(),t=a.currentTime+i*.06;oscillator.type='sine';oscillator.frequency.value=freq;gain.gain.setValueAtTime(.018,t);gain.gain.exponentialRampToValueAtTime(.001,t+.22);oscillator.connect(gain).connect(a.destination);oscillator.start(t);oscillator.stop(t+.24);});}catch{}}
 function persist(next:State){try{const previous=localStorage.getItem(SAVE);if(previous){try{E.deserialize(previous);localStorage.setItem(BACKUP,previous);}catch{}}localStorage.setItem(SAVE,E.serialize(next));setSaved(true);}catch{setSaved(false);announce('Autosave unavailable. Export a save from Settings before leaving.');}}
 function apply(action:Action,quiet=false){const r=E.act(ref.current,action);if(r.ok){ref.current=r.state;setS(r.state);persist(r.state);if(!quiet)announce(r.message);if(['deliver','journey','pilot','factory','upgrade'].includes(action.type))chime();}else announce(r.message);return r;}
 function dispatch(action:Action){const r=apply(action);if(r.ok&&ref.current.tutorial.enabled){const step=action.type==='plan'?'plan':action.type==='accept'?'buyer':action.type==='buy'?'stock':null;if(step&&!ref.current.tutorial.completed.includes(step))apply({type:'tutorial',complete:step},true);}return r;}
 useEffect(()=>{if(!initial.current!.error)persist(ref.current);return()=>window.clearTimeout(timer.current);},[]);
 useEffect(()=>{setSceneArea(undefined);},[s.travel.location]);
 useEffect(()=>{if(s.travel.trip)setInterior(false);},[s.travel.trip?.to]);
 const caps=E.capabilities(s),journey=E.journeyView(s),localFactory=factoryForPlace(s.travel.location),owned=localFactory&&s.growth.factories.some(f=>f.id===localFactory),risk=E.blockers(s),trip=s.travel.trip,completed=s.tutorial.completed;
 const guide=s.tutorial.enabled&&!s.v3.completed&&(!s.v3.enabled||s.v3.chapter<2)&&!completed.includes('week')?( !completed.includes('messages')?{text:'Nadia left you a note. Tap the envelope to read it.',target:'messages'}:!completed.includes('navigate-factory')?{text:'Find the workshop on the waterfront. Tap its building to go inside.',target:'factory'}:s.v3.enabled&&s.v3.chapter===0?{text:'Meet Nadia beside the machinery. She has your first introduction.',target:'staff'}:!completed.includes('plan')?{text:'Tap a production machine. Inspect the cases and hours, then choose your batch.',target:'production'}:!completed.includes('buyer')?{text:'Go Outside and meet Captain Leda on the waterfront. Accept your first order.',target:'buyer'}:{text:'Your batch is ready. Advance one week to make, dispatch and sell it.',target:'week'}):null;
 function closePanel(){setPanel(null);setBooking(null);setResult(false);}
 function open(id:string,detail?:string){setPanel({id,detail});setBooking(null);setResult(false);setHighlight(undefined);}
 function factoryPanel(sec:Section='production',id=localFactory||'quay'){setFactory(id);setSection(sec);open('factory');}
 function reveal(target:string){closePanel();if(s.travel.location==='sf')setSceneArea(['buyer','market','office','research'].includes(target)&&!(target==='buyer'&&s.v3.chapter===1)?'hill':'quay');if(['factory','buyer','supplier','market','office','terminal','news'].includes(target))setInterior(false);if(['production','staff','inventory','research','machines'].includes(target))setInterior(true);setHighlight(target);}
 function navigate(where:string){if(where.startsWith('discovery:')){open('discovery',where.slice(10));return;}if(where.startsWith('remote:')){factoryPanel('production',where.split(':')[1] as FactoryId);return;}if(Object.keys(CITY_NAMES).includes(where)){if(s.travel.location!==where){setBooking(where as E.Destination|'sf');setPanel(null);}else reveal('factory');return;}if(where==='factory'){const id=localFactory&&owned?localFactory:'quay';if(!E.canManageFactory(s,id)){setBooking(placeForFactory(id));setPanel(null);}else if(placeForFactory(id)===s.travel.location){closePanel();setInterior(true);setHighlight('production');}else factoryPanel('production',id);return;}if(['suppliers','supply'].includes(where)){open('supply');return;}if(where==='market'){open('market');return;}if(where==='orders'){open('orders');return;}if(where==='research'){open('research');return;}reveal(where);}
 function meet(){open('story','meeting');}
 function interact(action:string){
  if(action==='exterior'){setInterior(false);closePanel();return;}
  if(action==='factory'){if(!localFactory)return;if(!owned){open('acquire',localFactory);return;}setFactory(localFactory);setInterior(true);closePanel();if(s.tutorial.enabled&&!completed.includes('navigate-factory'))apply({type:'tutorial',complete:'navigate-factory'},true);return;}
  if(action.startsWith('discovery:')){open('discovery',action.slice(10));return;}
  if(action==='staff'&&!interior&&s.v3.enabled&&s.v3.chapter===1&&!journey.ready){open('orders');return;}
  if(action==='staff'&&s.v3.enabled&&journey.ready&&journey.place===s.travel.location){meet();return;}
  if(action==='production'){if(owned)factoryPanel('production');else if(localFactory)open('acquire',localFactory);return;}
  if(action==='machines'){if(owned)factoryPanel('equipment');return;}
  if(action==='staff'){if(caps.people&&owned)factoryPanel('people');else meet();return;}
  if(action==='inventory'){if(owned)factoryPanel('inventory');else open('supply');return;}
  if(action==='research'){if(caps.research)open('research');else announce('Make your first introduction with Nadia.');return;}
  if(action==='terminal'){if(caps.travel)open('travel');else announce('Complete the waterfront introduction to begin your travels.');return;}
  if(action==='buyer'||action==='dispatch'){if(action==='buyer'&&s.v3.enabled&&journey.ready&&journey.place===s.travel.location)meet();else open('orders');return;}
  if(action==='supplier'){open('supply');return;}
  if(action==='market'){if(s.travel.location==='kyoto'){open('discovery','kyoto-tea');return;}open('market');return;}
  if(action==='news'){open('news');return;}
  if(action==='office'){open('office');return;}
 }
 function start(guided:boolean){apply({type:'identity',founder,business,crest},true);apply({type:'tutorial',enabled:guided,complete:'welcome'},true);setWelcome(false);setHighlight(guided?'messages':'factory');}
 function exportSave(raw=E.serialize(ref.current),label=`cacao-house-week-${ref.current.week}`){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=label+'.json';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1500);}
 async function importSave(input?:File){if(!input)return;try{if(input.size>3*1024*1024)throw Error('Choose a save smaller than 3 MB.');const next=E.deserialize(await input.text());ref.current=next;setS(next);persist(next);setWelcome(false);setInterior(false);closePanel();announce(`Restored ${next.v3.identity.business}, week ${next.week}.`);}catch(e){announce(e instanceof Error?e.message:'Could not read this save. Your house is unchanged.');}if(file.current)file.current.value='';}
 function reset(){exportSave();const next=E.newGame();ref.current=next;setS(next);persist(next);setWelcome(true);setRestart(false);setInterior(false);closePanel();}
 function closeWeek(){if(lock.current)return;lock.current=true;setBusy(true);const r=apply({type:'advance'},true);if(r.ok){if(ref.current.tutorial.enabled&&!ref.current.tutorial.completed.includes('week'))apply({type:'tutorial',complete:'week'},true);setPanel(null);setBooking(null);setResult(true);chime();}window.setTimeout(()=>{lock.current=false;setBusy(false);},400);}
 async function travel(to?:E.Destination|'sf'){
  if(lock.current)return;lock.current=true;setBusy(true);setBooking(null);setPanel(null);setInterior(false);
  if(to){const r=apply({type:'travel',to},true);if(!r.ok){lock.current=false;setBusy(false);return;}}
  let weeks=0;while(ref.current.travel.trip&&ref.current.status==='playing'&&weeks<4){const r=apply({type:'advance'},true);if(!r.ok){announce('Journey paused between trading weeks: '+r.message);setPanel({id:'transit'});break;}weeks++;await new Promise(resolve=>window.setTimeout(resolve,260));}
  if(!ref.current.travel.trip){announce(`Arrived in ${CITY_NAMES[ref.current.travel.location]}. ${weeks?`${weeks} trading week${weeks>1?'s':''} completed.`:'No trading week passed.'}`);setHighlight(ref.current.v3.enabled?E.journeyView(ref.current).ready?'buyer':undefined:undefined);chime();}else if(!panel)setPanel({id:'transit'});
  setBusy(false);lock.current=false;
 }
 const common={s,dispatch,onNavigate:navigate};
 function storyContent(meeting:boolean){if(!s.v3.enabled)return <><h3>Your existing house is preserved.</h3><p>Its original campaign and economic progress continue. The new guided story is available when starting a new house.</p><Metrics items={[["Contracts delivered",s.fulfilled],["Loan remaining",E.money(s.debt)],["Reputation",s.reputation],["Markets",s.markets.length]]}/>{s.growth.chapter==='growth'&&<p>Network review W{s.growth.reviewWeek}: two staffed factories, two reliable buyers and positive combined profit over four weeks.</p>}<button className="v3-button" onClick={()=>open('orders')}>Review commitments</button></>;
 if(s.v3.completed)return <><div className="v3-contact"><span>CH</span><div><small>THE COMPLETE COLLECTION</small><strong>{s.v3.identity.business}</strong></div></div><small className="v3-eyebrow">THE HOUSE TABLE</small><h2>A house with a place in the world.</h2><p>{s.ending||'The collection has launched. Your recipes, people and relationships are yours to grow.'}</p><button className="v3-button" onClick={()=>{closePanel();setInterior(false);}}>Visit the gathering</button></>;
 const onsite=s.travel.location===journey.place&&!trip,canMeet=onsite&&meeting;return <><div className="v3-contact"><span>{journey.person.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><small>{meeting?"IN PERSON":"YOUR CONTACT"} · {CITY_NAMES[journey.place]}</small><strong>{journey.person}</strong></div></div><small className="v3-eyebrow">CHAPTER {journey.chapter+1} · {CITY_NAMES[journey.place]}</small><h2>{journey.title}</h2><p className="v3-story-copy">{journey.text}</p><div className="v3-objective-card"><small>YOUR NEXT OBJECTIVE</small><strong>{journey.objective}</strong><p>{journey.progress}</p></div>{canMeet&&journey.ready?<div className="v3-stack">{journey.options.map(o=><button className="v3-choice" key={o.id} onClick={()=>{if(dispatch({type:'journey',choice:o.id}).ok){closePanel();if(ref.current.v3.chapter===1)setHighlight('production');}}}><strong>{o.label}<ArrowRight size={18}/></strong><span>{o.detail}</span></button>)}</div>:<button className="v3-button" onClick={()=>{if(!onsite){setBooking(journey.place);setPanel(null);}else{reveal(journey.chapter===0?!completed.includes('navigate-factory')?'factory':'staff':journey.chapter===6?'staff':journey.ready?'buyer':journey.chapter===1?'buyer':journey.chapter===5||journey.chapter===8?'research':'buyer');}}}>{onsite?journey.ready?`Find ${journey.person.split(' ')[0]}`:'Return to the next action':`Plan travel to ${CITY_NAMES[journey.place]}`}</button>}{canMeet&&!journey.ready&&<button className="v3-button secondary" onClick={()=>open(s.v3.chapter===5||s.v3.chapter===8?'research':'orders')}>Review the work still needed</button>}{s.v3.chapter>0&&<details className="v3-card"><summary>Your story so far</summary>{Object.entries(s.v3.decisions).filter(([k])=>/^\d+$/.test(k)).map(([k,v])=><p key={k}>Chapter {Number(k)+1} · {v.replaceAll('-',' ')}</p>)}</details>}</>;
 }
 function content(){switch(panel?.id){
 case 'explore':return <><p>Choose a neighbourhood or go straight to a local contact.</p><div className="sf-district-list">{[{area:'quay',name:'The waterfront',description:'Workshop, ingredients & ferry',places:[['factory','Your workshop','Plan a batch and inspect the line'],['supplier','Rafi · ingredients','Restock the ingredients for your next batch'],['staff',s.v3.chapter===0?'Nadia':s.v3.chapter===1?'Captain Leda':'Your crew',s.v3.chapter===1?'Your first customer order':'Meet your local contact'],...(caps.travel?[['terminal','Ferry Building','Plan your next journey']]:[])]},{area:'hill',name:'City steps',description:'Buyers, shops & the house office',places:[['buyer','Mara · buyers','Meet the city’s buyers'],['market','Union Square','Retail prices and distribution'],['office','House accounts','Your finances and commitments'],...(caps.research?[['research','Nadia’s studio','Develop your recipes']]:[])]}].map(d=><section key={d.area}><button className="sf-district-jump" onClick={()=>{setInterior(false);setSceneArea(d.area);setHighlight(undefined);closePanel();}}><span><strong>{d.name}</strong><small>{d.description}</small></span><ArrowRight size={18}/></button><div>{d.places.map(([id,name,description])=><button className="sf-place-row" key={id} onClick={()=>{setInterior(false);setSceneArea(d.area);closePanel();interact(id);}}><span><strong>{name}</strong><small>{description}</small></span><ChevronRight size={17}/></button>)}</div></section>)}</div><button className="v3-button secondary" onClick={()=>open('story')}>Your story & current objective</button><button className="v3-button secondary" onClick={()=>open(s.reports.length?'reports':'news')}>{s.reports.length?'Trading results':'The newspaper'}</button></>;
 case 'factory':return <>{guide?.target==='production'&&<div className="v3-tutorial-inline"><p>Each batch consumes hours and ingredients. The starter plan fits your line.</p><button className="v3-button secondary" onClick={()=>apply({type:'tutorial',complete:'plan'},true)}>Keep this production plan</button></div>}<FactoryPanel s={s} factory={factory} section={section} onSection={setSection} dispatch={dispatch} onNavigate={navigate}/></>;
 case 'supply':return <SupplyPanel {...common}/>;case 'orders':return <OrdersPanel {...common}/>;case 'market':return <MarketsPanel {...common}/>;case 'research':return <ResearchPanel {...common} initialRecipe={s.v3.chapter===5?'gianduja':s.v3.chapter>=8?'tea':'orange'}/>;case 'finance':return <AccountsPanel {...common}/>;case 'managers':return <ManagersPanel {...common}/>;case 'reports':return <ReportPanel {...common}/>;case 'news':return <NewsPanel {...common}/>;
 case 'travel':return <TravelMap s={s} onBook={to=>{setPanel(null);setBooking(to);}}/>;
 case 'discovery':return <Discovery s={s} id={panel.detail!} dispatch={dispatch} onMeet={meet}/>;
 case 'acquire':return <AcquireFactory s={s} id={panel.detail as FactoryId} dispatch={dispatch} onEnter={()=>{setFactory(panel.detail as FactoryId);setInterior(true);closePanel();}}/>;
 case 'story':return storyContent(panel.detail==='meeting');
 case 'office':return <><div className="v3-office-head"><span className="v3-house-mark">{s.v3.identity.crest==='star'?'✦':s.v3.identity.crest==='leaf'?'❧':'◒'}</span><div><small>{s.v3.identity.founder||'Your independent house'}</small><h2>{s.v3.identity.business}</h2></div></div><div className="v3-action-grid"><button onClick={()=>open('story','meeting')}><BookOpen/><strong>The current introduction</strong><span>{s.v3.enabled?journey.title:'Campaign objectives'}</span></button><button onClick={()=>open('finance')}><Landmark/><strong>Cash & loan</strong><span>{E.money(s.cash)} available</span></button>{s.reports.length>0&&<button onClick={()=>open('reports')}><Newspaper/><strong>Trading results</strong><span>Week {s.reports[0].week}</span></button>}{(caps.people||s.v3.operations)&&<button onClick={()=>open('managers')}><Users/><strong>Your management team</strong><span>Information & delegation</span></button>}</div></>;
 case 'messages':return <>{s.v3.enabled?<><div className="v3-card"><small>{journey.person} · {CITY_NAMES[journey.place]}</small><h3>{journey.title}</h3><p>{journey.objective}</p><button className="v3-button" onClick={()=>{if(s.tutorial.enabled&&!completed.includes('messages'))apply({type:'tutorial',complete:'messages'},true);open('story');}}>Read the introduction</button></div></>:E.LETTERS.filter(l=>l.week<=s.week).slice().reverse().map(l=><details className="v3-card" key={l.id}><summary>{l.title}</summary><p>{l.text}</p>{l.choices&&!s.choices[l.id]&&l.choices.map(c=><button className="v3-choice" key={c.id} onClick={()=>dispatch({type:'choice',id:l.id,choice:c.id})}><strong>{c.label}</strong><span>{c.detail}</span></button>)}</details>)}<button className="v3-button secondary" onClick={()=>open('news')}>Read the trade newspaper</button></>;
 case 'transit':return <><div className="v3-transit-art"><Globe2 size={50}/><span>IN TRANSIT</span><h2>{CITY_NAMES[trip?.to||s.travel.location]}</h2></div><p>{trip?`Arrival at the start of week ${trip.arrival}. Production uses available stock and ready factory capacity while you travel; limits reduce output.`:'Your journey is complete.'}</p>{risk.map(x=><p className="v3-warning" key={x}>{x}</p>)}<button className="v3-button" disabled={busy||!!risk.length} onClick={()=>void travel()}>Continue journey</button><button className="v3-button secondary" onClick={()=>open('supply')}>Review ingredients and deliveries</button>{s.v3.operations&&<button className="v3-button secondary" onClick={()=>open('managers')}>Ask your operations manager</button>}</>;
 case 'advance':{const f=E.forecast(s),actual=E.actualProduction(s),possible=Object.values(actual.plan).reduce((n,q)=>n+q,0),planned=Object.values(s.plan).reduce((n,q)=>n+q,0);return <><small className="v3-eyebrow">WEEK {s.week}</small><h2>Put your plan to work.</h2><p>Production uses available ingredients and factory capacity, ready orders ship, customers buy, and payments arrive. Limits reduce output; your saved plan stays in place. Retail turnout is uncertain.</p><Metrics items={[["Cases planned",Object.values(s.plan).reduce((n,q)=>n+q,0)],["Production costs",E.money(f.labor)],["Fixed weekly costs",E.money(f.overhead)],["Cash available",E.money(s.cash)]]}/>{possible<planned&&<p className="v3-warning">Available ingredients and factory capacity can make {possible} of {planned} planned cases. The week will continue with this smaller batch; the saved plan stays unchanged.</p>}{actual.warnings.map((warning,i)=><p className="v3-warning" key={`production-${i}`}>{warning}</p>)}{s.contracts.filter(c=>c.status==='active'&&c.due<=s.week).map(c=><p className="v3-warning" key={c.id}>{c.client}: due this week. Unfilled orders return the deposit and incur a fee.</p>)}{risk.map(x=><p className="v3-warning" key={x}>{x}</p>)}{s.cash<f.labor+f.overhead&&<p className="v3-warning">Cash before sales does not cover all known costs. Sales may not close the gap.</p>}<button className="v3-button" disabled={busy||!!risk.length} onClick={closeWeek}>Produce, dispatch & sell</button>{risk.length>0&&<div className="v3-row"><button className="v3-button secondary" onClick={()=>navigate('factory')}>Review the factory</button><button className="v3-button secondary" onClick={()=>open('supply')}>Buy missing stock</button></div>}</>;}
 case 'help':return <><h3>A business you can explore.</h3><div className="v3-help-row"><Factory/><p>Tap your workshop, then its machines, crew or stock. One site and one task at a time.</p></div><div className="v3-help-row"><Package/><p>Buy ingredients before production. Saved plans and purchase rules keep running until you change them.</p></div><div className="v3-help-row"><BookOpen/><p>Follow the current introduction. Travel, recipes and customers move the story forward.</p></div><div className="v3-help-row"><Globe2/><p>Travel advances trading weeks. Check stock and promises first. A later operations manager unlocks remote factory control.</p></div><div className="v3-help-row"><Newspaper/><p>Known costs are visible; retail sales remain uncertain. Read the short results and news, then adapt.</p></div><button className="v3-button secondary" onClick={()=>{apply({type:'tutorial',enabled:true},true);closePanel();}}>Resume guidance</button><p className="v3-note">There is no real-time clock. Drag to orbit, pinch to zoom. Keyboard-accessible place buttons work without gestures. Reduced-motion follows your device preference.</p></>;
 case 'settings':return <><div className="v3-settings-list"><button onClick={()=>exportSave()}><Download/>Export current save</button><button onClick={()=>file.current?.click()}><Upload/>Import save</button><button onClick={()=>{setSound(!sound);if(!sound)announce('Sound enabled. Future actions will play a short cue.');}}>{sound?<Volume2/>:<VolumeX/>}Sound {sound?'on':'off'}</button><button onClick={()=>open('help')}><HelpCircle/>Help & guidance</button><button onClick={()=>{setFounder(s.v3.identity.founder);setBusiness(s.v3.identity.business);setCrest(s.v3.identity.crest);setNameForm(true)}}><Settings/>House identity</button><button onClick={()=>{setRestart(true);setPanel(null);}}><Play/>Start a new V3 story</button>{savedItem('cacao-house-pre-v3')&&<button onClick={()=>exportSave(savedItem('cacao-house-pre-v3')!,'cacao-house-original-save')}><Download/>Export preserved pre-V3 save</button>}</div><p className="v3-note">{saved?'Saved automatically in this browser.':'Autosave is unavailable; export before leaving.'} Export/import moves a house between Mac and iPhone. Cacao House V3 · original people and businesses in real cities.</p></>;
 default:return null;}}
 const title=panel?.id==='factory'?E.FACTORIES.find(f=>f.id===factory)!.name:({explore:'Explore San Francisco',supply:'Ingredient exchange',orders:'The buyer desk',market:'Retail distribution',research:'The recipe studio',finance:'Cash & commitments',managers:'Management',reports:'Trading results',news:'The newspaper',travel:'World map',discovery:'A local discovery',acquire:'A new address',story:'Your story',office:'The house office',messages:'Messages',transit:'Your journey',advance:'Next trading week',help:'How to play',settings:'Settings & saves'} as Record<string,string>)[panel?.id||'']||'';
 return <main className={`v3-app ${s.travel.location==='sf'?'sf-trial':''} ${panel||booking||result?'has-context':''}`}>
 <V3World inactive={s.travel.location==='sf'&&!!(panel||booking||result||welcome||restart||nameForm)} s={s} location={s.travel.location} interior={interior} sceneArea={sceneArea} onInteract={interact} highlight={(!interior&&s.travel.location==='sf'&&s.v3.chapter===1&&(highlight||guide?.target)==='buyer')?'staff':highlight||guide?.target}/>
 <header className="v3-hud"><button className="v3-location" onClick={()=>{setInterior(false);closePanel();}}><Compass size={17}/><span>{CITY_NAMES[s.travel.location]}{interior&&<small>Workshop floor</small>}</span></button><button className="v3-cash" onClick={()=>open('finance')} aria-label="Cash details">{E.money(s.cash)}</button><span className="v3-week">W{s.week}</span><button className={`v3-icon ${guide?.target==='messages'?'highlight':''}`} aria-label="Messages" onClick={()=>open('messages')}><Mail size={20}/>{s.v3.enabled&&!s.v3.completed&&<i/>}</button><button className="v3-icon" aria-label="Menu" onClick={()=>open('settings')}><Menu size={21}/></button></header>
 {!panel&&!booking&&!result&&!welcome&&<><div className="v3-bottom"><button className={`v3-mission ${guide?'guided':''}`} onClick={()=>open(guide?.target==='messages'?'messages':'story')}><span className="v3-mission-icon">{guide?'?':s.v3.completed?'✓':'↗'}</span><span><small>{guide?'NADIA’S GUIDANCE':s.v3.completed?'THE STORY IS COMPLETE':s.v3.enabled?journey.title:'YOUR INDEPENDENT HOUSE'}</small><strong>{guide?.text||(s.travel.location==='sf'&&s.v3.enabled&&s.v3.chapter===1?(journey.ready?'Meet Captain Leda':'Fulfil your first order'):s.travel.location==='sf'&&s.v3.enabled&&s.v3.chapter===0?'Meet Nadia at your workshop':s.v3.enabled&&!s.v3.completed?journey.objective:'Choose the next promise your house will keep.')}</strong></span><ChevronRight size={17}/></button>{guide&&<button className="v3-skip" onClick={()=>apply({type:'tutorial',enabled:false},true)}>Skip guidance</button>}<nav className="v3-world-toolbar" aria-label="World tools">{s.travel.location==='sf'?<button onClick={()=>open('explore')}><Compass size={20}/><span>Explore</span></button>:caps.travel?<button onClick={()=>open('travel')}><Globe2 size={20}/><span>World map</span></button>:<button onClick={()=>open('story')}><BookOpen size={20}/><span>Introduction</span></button>}{s.travel.location==='sf'?<button onClick={()=>s.v3.enabled&&s.v3.chapter===0?meet():open('orders')}><Package size={20}/><span>Orders</span></button>:<button onClick={()=>open(s.reports.length?'reports':'news')}><Newspaper size={20}/><span>{s.reports.length?'Results':'News'}</span></button>}<button className={`v3-next ${guide?.target==='week'?'highlight':''}`} disabled={busy||s.status!=='playing'} onClick={()=>trip?open('transit'):s.v3.enabled&&s.v3.chapter===0?reveal('staff'):open('advance')}><Play size={18}/><span>{busy?'Travelling…':trip?'Continue journey':'Next week'}</span></button></nav></div>{trip&&<button className="v3-travel-status" onClick={()=>open('transit')}>En route to {CITY_NAMES[trip.to]} · arrives W{trip.arrival}<ArrowRight size={16}/></button>}</>}
 {panel&&<Sheet title={title} context={panel.id==='factory'?`${CITY_NAMES[placeForFactory(factory)]}${E.canManageFactory(s,factory)&&s.travel.location!==placeForFactory(factory)?' · remote management':''}`:CITY_NAMES[s.travel.location]} onClose={closePanel} wide={panel.id==='factory'} navigation={s.travel.location==='sf'&&!['settings','help','transit'].includes(panel.id)?<nav className="sf-panel-nav" aria-label="Local business actions"><button onClick={()=>{setInterior(false);closePanel()}}>City</button><button aria-current={panel.id==='factory'?'page':undefined} onClick={()=>{setInterior(true);factoryPanel()}}>Workshop</button><button aria-current={panel.id==='supply'?'page':undefined} onClick={()=>open('supply')}>Ingredients</button><button aria-current={panel.id==='orders'?'page':undefined} onClick={()=>open('orders')}>Orders</button></nav>:undefined}>{content()}</Sheet>}
 {booking&&<Sheet title={`Travel to ${CITY_NAMES[booking]}`} context="Review your route" onClose={()=>setBooking(null)}><div className="v3-route-hero"><span>{CITY_NAMES[s.travel.location]}</span><Globe2 size={40}/><strong>{CITY_NAMES[booking]}</strong></div><Metrics items={[["Fare",E.money(E.travelPreflight(s,booking).cost)],["Time",`${E.travelPreflight(s,booking).weeks} trading weeks`]]}/>{E.travelPreflight(s,booking).warnings.map((w,i)=><p className="v3-report-note" key={i}>{w}</p>)}<button className="v3-button" disabled={busy||s.cash<E.travelPreflight(s,booking).cost||!!trip} onClick={()=>void travel(booking)}>Book & travel · {E.money(E.travelPreflight(s,booking).cost)}</button><button className="v3-button secondary" onClick={()=>open('supply')}>Prepare ingredients first</button></Sheet>}
 {result&&<Sheet title={`Week ${s.reports[0]?.week} · results`} context="Your plan, in practice" onClose={()=>setResult(false)}><ReportPanel {...common}/><button className="v3-button" onClick={()=>setResult(false)}>Return to the world</button></Sheet>}
 {welcome&&<div className="v3-welcome"><div className="v3-welcome-art"/><section><small className="v3-eyebrow">CACAO HOUSE</small><h1>{s.travel.location==='sf'?'Cacao House':<>A small workshop.<br/>A bigger promise.</>}</h1><p>{s.travel.location==='sf'?'Run your San Francisco workshop. Plan chocolate batches, source ingredients and keep your first customer promise.':'Nadia has kept the ferry workshop ready. Make your first delivery, develop recipes with makers and growers, and launch your collection at a chocolate tasting in Paris.'}</p><div className="v3-welcome-buttons"><button className="v3-button" onClick={()=>start(true)}>Start with guidance <ArrowRight size={18}/></button><button className="v3-button secondary" onClick={()=>start(false)}>Play without tutorial</button></div><button className="v3-inline" onClick={()=>setNameForm(true)}>Name your house · optional</button><small className="v3-note">Plan at your own pace. Time moves only when you choose.</small></section></div>}
 {legacyInfo&&<Sheet title="V3 is here. Your house is safe." onClose={dismissLegacy}><p>Your existing factories, recipes and save are preserved. This house continues its original campaign in the new world interface.</p><p>The new ten-chapter journey begins with a fresh house. Starting it exports your current save first.</p><button className="v3-button" onClick={dismissLegacy}>Continue my existing house</button><button className="v3-button secondary" onClick={()=>{dismissLegacy();setRestart(true)}}>Start the new V3 story</button></Sheet>}
 {nameForm&&<Sheet title="Make it your house" onClose={()=>setNameForm(false)}><label className="v3-label">Founder<input maxLength={60} value={founder} onChange={e=>setFounder(e.target.value)} placeholder="Your name"/></label><label className="v3-label">Business name<input maxLength={60} value={business} onChange={e=>setBusiness(e.target.value)}/></label><div className="v3-crest-options">{[{id:'cacao',mark:'◒'},{id:'star',mark:'✦'},{id:'leaf',mark:'❧'}].map(x=><button aria-label={`${x.id} emblem`} className={crest===x.id?'selected':''} key={x.id} onClick={()=>setCrest(x.id)}>{x.mark}</button>)}</div><button className="v3-button" onClick={()=>{apply({type:'identity',founder,business,crest},true);setNameForm(false);}}>Save house identity</button></Sheet>}
 {restart&&<Sheet title="Start a new story?" onClose={()=>setRestart(false)}><p>Your current house will be exported before the new story begins. Its save can be imported later.</p><button className="v3-button" onClick={reset}>Export current house & start</button><button className="v3-button secondary" onClick={()=>setRestart(false)}>Keep this house</button></Sheet>}
 {s.status!=='playing'&&!welcome&&!restart&&<Sheet title={s.status==='won'?s.v3.enabled?'A place at the table.':'Your house earned its future.':'The workshop needs a new start.'} context={s.v3.identity.business} onClose={()=>{}}><div className="v3-ending-seal">{s.status==='won'?'✦':'◒'}</div><p className="v3-story-copy">{s.ending}</p>{s.status==='won'?<button className="v3-button" onClick={()=>{dispatch({type:'continue'});closePanel();setInterior(false);}}>Continue with this house</button>:<button className="v3-button" onClick={()=>{setRestart(true);}}>Export & start again</button>}<button className="v3-button secondary" onClick={()=>exportSave()}>Export this house</button></Sheet>}
 {s.v3.enabled&&s.cash<1000&&!s.v3.recoveryUsed&&s.status==='playing'&&panel?.id==='finance'&&<div className="v3-recovery"><strong>A one-time bridge is available.</strong><button onClick={()=>dispatch({type:'recovery',choice:'bridge'})}>+$1,800 cash · +$1,980 loan</button><button onClick={()=>dispatch({type:'recovery',choice:'sell-stock'})}>+$1,200 rescue licence · reputation −8</button></div>}
 {message&&<div className="v3-toast" role="status"><span>{message}</span><button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 <input ref={file} hidden type="file" accept="application/json,.json" onChange={e=>void importSave(e.target.files?.[0])}/>
 </main>;
}
