import * as E from '../game/engine';
import type {Action,State,Recipe,Ingredient} from '../game/engine';
type Dispatch=(a:Action,quiet?:boolean)=>unknown;
export function IngredientControls({s,r,dispatch}:{s:State;r:Recipe;dispatch:Dispatch}){const p=E.productPreview(s,r),rank=s.productionPriority.indexOf(r.id);return <details className="ingredient-policy"><summary>Ingredient grades & allocation <span>{p.fallback?'Fallback in use':'Saved preferences'}</span></summary><p>Preferred grades are reserved for every product first. Remaining stock then follows the priority below. “Any grade” blends available stock.</p><div className="priority-control"><span>Allocation priority <b>{rank+1} of 6</b></span><button aria-label={`Prioritize ${r.name}`} disabled={rank===0} onClick={()=>dispatch({type:'priority',recipe:r.id,direction:-1},true)}>↑ Higher</button><button aria-label={`Lower priority ${r.name}`} disabled={rank===5} onClick={()=>dispatch({type:'priority',recipe:r.id,direction:1},true)}>↓ Lower</button></div>{E.INGREDIENTS.filter(i=>r.ingredients[i]).map(i=>{const policy=s.ingredientPolicy[r.id][i];return <div className="grade-row" key={i}><strong>{i}</strong><label>Preferred<select aria-label={`${r.name} ${i} preferred grade`} value={policy.preferred} onChange={e=>dispatch({type:'policy',recipe:r.id,ingredient:i,...policy,preferred:e.target.value as E.Grade|'any'},true)}><option value="any">Any grade / blend</option>{E.GRADES.map(g=><option key={g}>{g}</option>)}</select></label><label>If unavailable<select aria-label={`${r.name} ${i} fallback`} value={policy.fallback} disabled={policy.preferred==='any'} onChange={e=>dispatch({type:'policy',recipe:r.id,ingredient:i,...policy,fallback:e.target.value as E.IngredientPolicy['fallback']},true)}><option value="any">Any other grade</option><option value="lower">Lower grades only</option><option value="none">Stop production</option></select></label></div>})}<p><b>Plan preview: {p.quality}/100 quality · ${p.cost.toFixed(2)} per case</b>{!s.plan[r.id]?' (one-case preview)':''}. {p.fallback?'Allowed fallback stock is included.':'Uses your allocated ingredients.'}</p>{p.shortages.map(x=><p className="bad" key={x}>{x} Cost estimates missing stock at its last average acquisition price. Buy stock to confirm the final cost.</p>)}{E.gradeWarnings(s).filter(x=>x.startsWith(r.name+':')).map(x=><p className="bad" key={x}>{x}</p>)}<p>Cocoa quality determines the base chocolate quality. Standard: below 75; select: 75–89; premium: 90+. Other purchased ingredients are select quality at every supplier.</p></details>}
export function RepeatOrders({s,dispatch}:{s:State;dispatch:Dispatch}){return <div className="panel repeat-orders"><h3>Repeat an ingredient order</h3><p className="muted">One click buys your last successful quantity from the same supplier at today’s price. Each ingredient saves its own preset.</p>{E.INGREDIENTS.map(i=>{const p=s.repeatOrders[i],vendor=p&&E.SUPPLIERS.find(x=>x.id===p.supplier)!;return <div className="repeat-row" key={i}><div><strong>{i}</strong><small>{p&&vendor?`${p.qty} kg · ${vendor.name} · ${E.gradeFor(i==='cocoa'?vendor.quality:75)} grade`:'Place an order to save a preset.'}</small>{p&&<small>{E.lead(s,p.supplier)?`Available week ${s.week+E.lead(s,p.supplier)}`:'Available immediately'} · {E.money(E.orderTotal(s,p.supplier,i,p.qty))} today</small>}</div><button className="secondary" disabled={!p||s.status!=='playing'||s.cash<E.orderTotal(s,p.supplier,i,p.qty)} onClick={()=>dispatch({type:'repeat',ingredient:i})}>Repeat {i}</button></div>})}</div>}
export function GuidedStart({s,tab,panelOpen,open,dispatch,closeWeek}:{s:State;tab:string;panelOpen:boolean;open:(t:string)=>void;dispatch:Dispatch;closeWeek:()=>void}){
 if(!s.tutorial.enabled||s.tutorial.completed.includes('result2')||s.week>3||s.status!=='playing')return null;
 const done=s.tutorial.completed,report=s.reports.find(r=>r.week===(s.week===2?1:2));let person='Nadia',title='',text='',button='',action=()=>{};
 if(s.week>=3){title='Two weeks complete';text=report?`You made ${report.produced} cases and collected ${E.money(report.retail)} in retail sales. Trading profit: ${E.money(report.profit)}. Check delivery dates before your next production run.`:'Your plan repeats each week. Check stock, cash and contract deadlines before closing.';button='Finish guided start';action=()=>dispatch({type:'tutorial',complete:'result2'},true)}
 else if(s.week===2&&!done.includes('result1')){title='Your first week, explained';text=report?`${report.produced} cases made; ${report.sold} sold to shops. Contracts booked ${E.money(report.contractRevenue)}; retail brought ${E.money(report.retail)}. Cash ended at ${E.money(report.closingCash)} after wages and overhead. Finished stock is different from raw ingredients.`:'';button=panelOpen&&tab==='finance'?'Continue to suppliers':'Review week 1 results';action=()=>{if(panelOpen&&tab==='finance'){dispatch({type:'tutorial',complete:'result1'},true);open('supply')}else open('finance')}}
 else if(s.week===2){person='Rafi';const needs=E.needed(s),missing=E.INGREDIENTS.filter(i=>needs[i]>s.stock[i].qty+.001),i=missing[0];title=i?'Restock for this week':!done.includes('supply')?'Plan a future delivery':'Ready for week two';text=i?`Your repeating plan needs ${Math.ceil(needs[i]-s.stock[i].qty)} kg more ${i}. Dock orders can be used immediately. Cooperative orders take ${E.lead(s,'coop')} weeks and cannot cover this shortage.`:!done.includes('supply')?'Your immediate stock is ready. Try a 40 kg cooperative cocoa order: pay now, receive select quality at the start of week 4. It stays separate from standard cocoa.':'Your current plan is covered and your future delivery is scheduled. Close week 2 to see production, sales and the shipment timeline.';button=!panelOpen||tab!=='supply'?'Open suppliers':i?`Buy ${Math.ceil(needs[i]-s.stock[i].qty)} kg ${i} now`:!done.includes('supply')?'Order 40 kg cocoa for week 4':'Close week 2';action=()=>{if(!panelOpen||tab!=='supply')open('supply');else if(i)dispatch({type:'buy',supplier:'dock',ingredient:i,qty:Math.ceil(needs[i]-s.stock[i].qty)});else if(!done.includes('supply'))dispatch({type:'buy',supplier:'coop',ingredient:'cocoa',qty:40});else closeWeek()}}
 else if(!done.includes('production')){title='Start with your production plan';text='I’ve planned 55 dark and 35 milk cases: 98 of 100 factory hours, including changeover. Check the unit costs, prices and expected demand. One case holds 20 bars.';button=panelOpen&&tab==='workshop'?'Plan reviewed · find a buyer':'Review production';action=()=>{if(panelOpen&&tab==='workshop'){dispatch({type:'tutorial',complete:'production'},true);open('orders')}else open('workshop')}}
 else if(!s.contracts.some(c=>c.id==='ferry')){person='Mara';title='Get your first customer';text='The ferry needs 35 dark cases at quality 50+. Your current plan qualifies. Accepting pays a $193 deposit now; the remaining balance arrives when the cases ship.';button='View ferry order';action=()=>open('orders')}
 else {title='Run your first week';text='Your ferry order is accepted. Closing the week makes your planned chocolate, ships qualifying orders first, sells remaining stock, and pays wages and overhead.';button='Review & close week 1';action=closeWeek}
 const blocks=E.blockers(s);if((title==='Ready for week two'||button==='Review & close week 1')&&blocks.length){title='Adjust the production plan';text=blocks.slice(0,2).join(' ')+' Review quantities, grades and available cash before closing.';button='Review production blockers';action=()=>open('workshop')}
 return <aside className={`guided-start ${panelOpen?'inline-guide':'world-guide'}`} aria-label="Guided start"><div className="guide-heading"><span>{person} · {s.week<=2?`Week ${s.week} guide`:'Results'}</span><button onClick={()=>dispatch({type:'tutorial',enabled:false},true)}>Hide guide</button></div><h3>{title}</h3><p>{text}</p><button className="primary" onClick={action}>{button}</button></aside>
}
export function PositionPreview({s,r}:{s:State;r:Recipe}){return <div className="position-preview"><strong>Target audience: {r.segment}</strong><p>{r.segment==='Everyday'?'Everyday buyers favor value positioning. Premium can sell fewer cases at the same price.':'Gift and connoisseur buyers favor premium positioning.'} Production cost affects margin; it does not lower demand.</p><table aria-label={`${r.name} positioning comparison`}><thead><tr><th>Position</th><th>Cost</th><th>Margin</th><th>Demand</th></tr></thead><tbody>{(['value','balanced','premium'] as const).map(p=>{const preview={...s,position:{...s.position,[r.id]:p}},cost=E.unitCost(preview,r);return <tr key={p} className={s.position[r.id]===p?'current':''}><th>{p==='balanced'?'Standard':p==='value'?'Value':'Premium'}</th><td>${cost.toFixed(2)}</td><td>${(s.prices[r.id]-cost).toFixed(2)}</td><td>~{E.demand(preview,r)}</td></tr>})}</tbody></table><small>At your current ${s.prices[r.id].toFixed(2)} selling price · per case · margin before overhead</small></div>}
